<?php
/**
 * SMS 2 - Sample uploaded documents  [TEST DATA ONLY]
 *
 * ============================================================================
 * THIS SCRIPT GENERATES PLACEHOLDER FILES. They are not real documents.
 * Each generated PNG says so across its face. Do not run this against a live
 * BCP database.
 * ============================================================================
 *
 * Why it exists: the Registrar verification screens cannot be tested until
 * documents exist, and the applicant upload page is a later task. This attaches
 * documents to the SAMPLE- applicants so the whole portal can be clicked
 * through: verify, request replacement, reject, and watch completeness change.
 *
 * The generated files are real, valid PNGs written to the same storage
 * directory a genuine upload uses, so the file-serving endpoint and the preview
 * are exercised properly rather than faked.
 *
 * CLI:  php modules/enrollment/database/seed_sample_documents.php
 *       php modules/enrollment/database/seed_sample_documents.php --purge
 */

declare(strict_types=1);

require_once dirname(__DIR__, 3) . '/config/config.php';
require_once ROOT_PATH . '/config/database.php';
require_once ROOT_PATH . '/includes/uploads.php';
require_once dirname(__DIR__) . '/config/enrollment.php';
require_once dirname(__DIR__) . '/includes/docs-workflow.php';
require_once dirname(__DIR__) . '/includes/docs-repository.php';

if (PHP_SAPI !== 'cli') {
    http_response_code(403);
    header('Content-Type: text/plain; charset=utf-8');
    echo "Forbidden. Run from CLI only.\n";
    exit(1);
}

const SAMPLE_APP_PREFIX = 'SAMPLE-';

function docSeedOut(string $message = ''): void
{
    echo $message . PHP_EOL;
}

try {
    $pdo = getDatabaseConnection();
} catch (Throwable $e) {
    docSeedOut('FAILED: ' . $e->getMessage());
    exit(1);
}

if (!enrDocSchemaInstalled($pdo)) {
    docSeedOut('FAILED: the document tables do not exist yet.');
    docSeedOut('Run: php modules/enrollment/database/install_document_upload.php');
    exit(1);
}

smsUploadEnsureDirs();
$docDir = smsUploadRoot() . '/' . ENR_DOC_SUBDIR;
if (!is_dir($docDir)) {
    @mkdir($docDir, 0750, true);
}

// ---------------------------------------------------------------------------
// Purge
// ---------------------------------------------------------------------------
if (in_array('--purge', $argv ?? [], true)) {
    $stmt = $pdo->prepare(
        'SELECT d.id, d.stored_name
           FROM enr_application_documents d
           JOIN enr_applications a ON a.id = d.application_id
          WHERE a.reference_no LIKE ?'
    );
    $stmt->execute([SAMPLE_APP_PREFIX . '%']);
    $rows = $stmt->fetchAll() ?: [];

    $filesRemoved = 0;
    foreach ($rows as $row) {
        $path = $docDir . '/' . basename((string) $row['stored_name']);
        if (is_file($path) && @unlink($path)) {
            $filesRemoved++;
        }
    }

    // The verification rows go with the documents through ON DELETE CASCADE.
    $del = $pdo->prepare(
        'DELETE d FROM enr_application_documents d
           JOIN enr_applications a ON a.id = d.application_id
          WHERE a.reference_no LIKE ?'
    );
    $del->execute([SAMPLE_APP_PREFIX . '%']);

    docSeedOut('Removed ' . $del->rowCount() . ' sample document row(s) and ' . $filesRemoved . ' file(s).');
    exit(0);
}

// ---------------------------------------------------------------------------
// Generate a placeholder PNG that is obviously not a real document
// ---------------------------------------------------------------------------
function docSeedMakePng(string $documentName, string $applicantName, string $reference, bool $blurry): string
{
    $width  = 700;
    $height = 460;
    $image  = imagecreatetruecolor($width, $height);

    $paper = imagecolorallocate($image, 250, 250, 247);
    $ink   = imagecolorallocate($image, 30, 41, 59);
    $muted = imagecolorallocate($image, 130, 140, 155);
    $rule  = imagecolorallocate($image, 205, 212, 222);
    $stamp = imagecolorallocate($image, 200, 60, 60);

    imagefilledrectangle($image, 0, 0, $width, $height, $paper);
    imagerectangle($image, 12, 12, $width - 13, $height - 13, $rule);

    imagestring($image, 5, 40, 45,  'BESTLINK COLLEGE OF THE PHILIPPINES', $ink);
    imagestring($image, 3, 40, 70,  'SAMPLE DOCUMENT - NOT A REAL RECORD', $stamp);
    imageline($image, 40, 95, $width - 40, 95, $rule);

    imagestring($image, 4, 40, 125, 'Document: ' . $documentName, $ink);
    imagestring($image, 4, 40, 155, 'Name:     ' . $applicantName, $ink);
    imagestring($image, 4, 40, 185, 'Ref No.:  ' . $reference, $ink);
    imagestring($image, 3, 40, 225, 'Generated by seed_sample_documents.php for testing only.', $muted);
    imagestring($image, 3, 40, 245, 'This file contains no real personal data.', $muted);

    for ($y = 300; $y < 400; $y += 22) {
        imageline($image, 40, $y, $width - 60, $y, $rule);
    }
    imagestring($image, 2, 40, 415, 'Placeholder body text area', $muted);

    // One sample is deliberately unreadable so the "Needs Replacement" path has
    // a genuine reason to exist rather than a made-up one.
    if ($blurry) {
        for ($pass = 0; $pass < 12; $pass++) {
            imagefilter($image, IMG_FILTER_GAUSSIAN_BLUR);
        }
        imagestring($image, 5, 200, 210, 'INTENTIONALLY BLURRED', $stamp);
    }

    ob_start();
    imagepng($image);
    $binary = (string) ob_get_clean();
    imagedestroy($image);

    return $binary;
}

// ---------------------------------------------------------------------------
// Seed
// ---------------------------------------------------------------------------
$applications = $pdo->prepare(
    'SELECT id, reference_no, first_name, last_name, applicant_type
       FROM enr_applications
      WHERE reference_no LIKE ?
      ORDER BY reference_no'
);
$applications->execute([SAMPLE_APP_PREFIX . '%']);
$rows = $applications->fetchAll() ?: [];

if ($rows === []) {
    docSeedOut('No sample applications found.');
    docSeedOut('Run this first: php modules/enrollment/database/seed_sample_applications.php');
    exit(1);
}

if (!function_exists('imagecreatetruecolor')) {
    docSeedOut('FAILED: the PHP GD extension is not enabled, so placeholder images cannot be generated.');
    docSeedOut('Enable extension=gd in php.ini and restart Apache.');
    exit(1);
}

/**
 * How complete each sample applicant should be, so the queue shows a spread of
 * states rather than six identical rows.
 *   full    - every required document uploaded
 *   partial - one required document deliberately left missing
 *   blurry  - complete, but one file is unreadable and should be replaced
 *   none    - nothing uploaded at all
 */
$plan = [
    1 => 'full',
    2 => 'partial',
    3 => 'blurry',
    4 => 'partial',
    5 => 'none',
    6 => 'full',
];

$created = 0;
$skipped = 0;
$index   = 0;

foreach ($rows as $application) {
    $index++;
    $mode = $plan[$index] ?? 'partial';

    $applicationId = (int) $application['id'];
    $reference     = (string) $application['reference_no'];
    $applicantName = trim($application['first_name'] . ' ' . $application['last_name']);

    if ($mode === 'none') {
        docSeedOut('  --    ' . $reference . ' — left with no documents (tests the empty state)');
        continue;
    }

    $existing = $pdo->prepare('SELECT COUNT(*) FROM enr_application_documents WHERE application_id = ?');
    $existing->execute([$applicationId]);
    if ((int) $existing->fetchColumn() > 0) {
        docSeedOut('  SKIP  ' . $reference . ' — already has documents');
        $skipped++;
        continue;
    }

    $requirements = enrDocRequirements($pdo, (string) $application['applicant_type']);
    $required = array_values(array_filter(
        $requirements,
        static fn (array $r): bool => (int) $r['is_required'] === 1
    ));

    // "partial" leaves the last required document missing on purpose.
    $target = $mode === 'partial'
        ? array_slice($required, 0, max(1, count($required) - 1))
        : $required;

    $blurryIndex = $mode === 'blurry' ? 1 : -1;
    $position = 0;

    foreach ($target as $requirement) {
        $documentName = (string) $requirement['document_name'];
        $isBlurry     = ($position === $blurryIndex);

        $binary = docSeedMakePng($documentName, $applicantName, $reference, $isBlurry);
        $stored = 'sample_' . bin2hex(random_bytes(12)) . '.png';

        if (file_put_contents($docDir . '/' . $stored, $binary) === false) {
            docSeedOut('  FAIL  could not write ' . $stored);
            continue;
        }
        @chmod($docDir . '/' . $stored, 0640);

        $slug = strtolower(preg_replace('/[^a-z0-9]+/i', '_', $documentName) ?? 'document');

        enrDocStoreUpload(
            $pdo,
            $applicationId,
            (int) $requirement['id'],
            $documentName,
            [
                'original_name' => $slug . '_' . strtolower(str_replace('-', '', $reference)) . '.png',
                'stored_name'   => $stored,
                'mime'          => 'image/png',
                'size'          => strlen($binary),
            ],
            null
        );

        $created++;
        $position++;
    }

    $label = match ($mode) {
        'full'    => 'all required documents uploaded',
        'partial' => 'one required document deliberately missing',
        'blurry'  => 'complete, but one file is unreadable',
        default   => '',
    };
    docSeedOut('  OK    ' . $reference . ' — ' . $label);
}

docSeedOut();
docSeedOut($created . ' sample document(s) created, ' . $skipped . ' applicant(s) skipped.');
docSeedOut();
docSeedOut('Every file is a generated placeholder stamped "SAMPLE DOCUMENT".');
docSeedOut('Remove them all with:');
docSeedOut('  php modules/enrollment/database/seed_sample_documents.php --purge');
