<?php
require_once __DIR__ . '/../../../config/config.php';
$pageTitle='Conflict Checker';$activeModule='scheduling';$activePage='conflict-checker';
$breadcrumbs=[['label'=>'Class Scheduling','url'=>BASE_URL.'/modules/scheduling/index.php'],['label'=>'Conflict Checker','url'=>null]];
$hideModulePageBanner=true;
require_once __DIR__ . '/../../../includes/breadcrumbs.php';
require_once __DIR__ . '/../../../includes/layout-start.php';
renderBreadcrumbs($breadcrumbs);
?>

<style>
.ccx{--navy:#07315f;--blue:#0d6efd;--line:#dbe7f5;--soft:#f4f8fd;color:#163b68}.ccx-hero{background:linear-gradient(115deg,#052a54,#0c6dc2);color:#fff;border-radius:1rem;padding:1.15rem 1.45rem;display:flex;align-items:center;justify-content:space-between;gap:1rem;box-shadow:0 10px 28px rgba(4,48,94,.18)}.ccx-hero h1{margin:0;font-size:1.5rem}.ccx-hero p{margin:.25rem 0 0;color:#dceeff}.ccx-hero-tag{border-left:1px solid rgba(255,255,255,.45);padding-left:1rem;font-size:.82rem}
.ccx-steps{display:grid;grid-template-columns:repeat(7,minmax(120px,1fr));gap:.55rem;margin:1rem 0;overflow-x:auto;padding-bottom:.25rem}.ccx-step{min-width:120px;border:1px solid var(--line);border-radius:.8rem;background:#fff;padding:.65rem;text-align:left;color:#687d99;cursor:pointer;transition:.18s}.ccx-step:hover{border-color:#8eb8eb}.ccx-step.active{background:#eaf3ff;border-color:#3381e6;color:#0753ad;box-shadow:inset 0 -3px #0d6efd}.ccx-step.done{border-color:#a8dbc9;color:#087b52}.ccx-step-icon{width:2rem;height:2rem;border-radius:50%;display:grid;place-items:center;background:#e8eef7;margin-bottom:.35rem}.active .ccx-step-icon{background:#0d6efd;color:#fff}.done .ccx-step-icon{background:#dcf5e9;color:#087b52}.ccx-step small,.ccx-step b{display:block}.ccx-step small{font-size:.65rem}.ccx-step b{font-size:.75rem;line-height:1.15}
.ccx-page{display:none}.ccx-page.active{display:block}.ccx-card{border:1px solid var(--line);border-radius:.9rem;background:#fff;box-shadow:0 3px 14px rgba(22,59,104,.06)}.ccx-head{padding:1rem 1.15rem;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center;gap:1rem}.ccx-head h2{font-size:1.05rem;margin:0;color:#0b376d}.ccx-body{padding:1.15rem}.ccx-title-icon{width:2.35rem;height:2.35rem;display:inline-grid;place-items:center;background:#e8f2ff;color:#075fc7;border-radius:.65rem;font-size:1.15rem;margin-right:.55rem}
.ccx-stat{border:1px solid var(--line);border-radius:.8rem;background:#fff;padding:1rem;display:flex;align-items:center;gap:.85rem;height:100%}.ccx-stat i{width:2.7rem;height:2.7rem;border-radius:.7rem;display:grid;place-items:center;font-size:1.3rem}.ccx-stat b{font-size:1.5rem;display:block;line-height:1}.ccx-stat small{color:#70829a}.st-blue i{background:#e4efff;color:#0a63ca}.st-red i{background:#ffe7e8;color:#c3313c}.st-amber i{background:#fff1cf;color:#956300}.st-green i{background:#dcf5e8;color:#087a50}.st-purple i{background:#eee7ff;color:#6744b5}
.ccx-toolbar{display:flex;justify-content:space-between;align-items:center;gap:.7rem;flex-wrap:wrap;margin-top:1rem;padding-top:1rem;border-top:1px solid var(--line)}.ccx-table{font-size:.79rem}.ccx-table thead th{background:#f3f8fe;color:#365a82;white-space:nowrap;border-bottom-color:var(--line)}.ccx-table td{vertical-align:middle}.ccx-pill{display:inline-flex;align-items:center;gap:.28rem;border-radius:999px;padding:.22rem .55rem;font-size:.69rem;font-weight:700;white-space:nowrap}.p-red{background:#ffe4e6;color:#b62530}.p-amber{background:#fff0cd;color:#835c00}.p-green{background:#dcf5e8;color:#08784e}.p-blue{background:#e4efff;color:#0b5db8}.p-gray{background:#edf1f5;color:#566579}.p-purple{background:#eee7ff;color:#6744b5}.ccx-empty{text-align:center;padding:2.4rem;color:#74859a}.ccx-empty i{font-size:2rem;display:block;margin-bottom:.4rem}.ccx-filter{background:#f5f9fe;border:1px solid var(--line);border-radius:.8rem;padding:1rem}.ccx-filter label{font-size:.75rem;font-weight:700;color:#426183}
.ccx-type-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:.65rem}.ccx-type{border:1px solid var(--line);border-radius:.7rem;padding:.75rem;background:#fff}.ccx-type i{font-size:1.15rem}.ccx-type b{display:block;font-size:1.05rem}.ccx-type small{font-size:.7rem;color:#70829a}.ccx-result{border-left:4px solid;border-radius:.65rem;padding:.7rem .8rem;background:#fff;margin-bottom:.6rem}.ccx-result.error{border-color:#cf3540;background:#fff4f4}.ccx-result.warning{border-color:#e2a51d;background:#fff9ea}.ccx-result.pass{border-color:#1b9b67;background:#effaf5}.ccx-result b{font-size:.82rem}.ccx-result p{font-size:.76rem;margin:.12rem 0 0}.ccx-note{background:#eef6ff;border:1px solid #c8dff8;border-radius:.7rem;padding:.8rem;font-size:.8rem;color:#31577e}
.ccx-conflict-title{border:1px solid #f0c6ca;background:#fff2f3;border-radius:.8rem;padding:1rem;display:flex;gap:.9rem;align-items:center;color:#a5242f}.ccx-conflict-title i{font-size:2rem}.ccx-record{border:1px solid var(--line);border-radius:.75rem;overflow:hidden;height:100%}.ccx-record-head{background:#f3f8fe;padding:.7rem .85rem;font-weight:700}.ccx-record-body{padding:.8rem}.ccx-dl{display:grid;grid-template-columns:110px 1fr;gap:.35rem .6rem;font-size:.79rem}.ccx-dl dt{color:#71849b}.ccx-dl dd{margin:0;font-weight:600;color:#183d69}.ccx-explain{border:1px solid #f0c6ca;border-radius:.75rem;padding:1rem;background:#fffafa}.ccx-action{display:flex;align-items:center;gap:.8rem;border:1px solid var(--line);border-radius:.7rem;padding:.8rem;background:#fff;color:#17426f;text-decoration:none}.ccx-action:hover{border-color:#7aacdf;background:#f2f7ff}.ccx-action i:first-child{font-size:1.35rem;color:#0d6efd}.ccx-action span{flex:1}.ccx-action b{display:block;font-size:.82rem}.ccx-action small{font-size:.72rem;color:#70829a}.ccx-compare{border:1px solid var(--line);border-radius:.75rem;overflow:hidden}.ccx-compare .before{padding:.85rem;background:#fff3f3}.ccx-compare .after{padding:.85rem;background:#effaf5;border-top:1px solid var(--line)}.ccx-progress{height:.65rem;border-radius:999px;overflow:hidden;background:#e5edf7}.ccx-progress span{display:block;height:100%;background:linear-gradient(90deg,#0d6efd,#20b77a);width:0;transition:width .6s}.ccx-success{text-align:center;padding:2rem}.ccx-success-icon{width:5rem;height:5rem;border-radius:50%;background:#daf6e7;color:#07925d;display:grid;place-items:center;font-size:2.8rem;margin:0 auto 1rem}
@media(max-width:992px){.ccx-steps{grid-template-columns:repeat(7,135px)}.ccx-type-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:576px){.ccx-hero{display:block}.ccx-hero-tag{margin-top:.8rem}.ccx-type-grid{grid-template-columns:1fr 1fr}.ccx-dl{grid-template-columns:1fr}.ccx-toolbar .btn{flex:1}}
@media print{body *{visibility:hidden!important}#ccxPage7,#ccxPage7 *{visibility:visible!important}#ccxPage7{position:absolute;inset:0}.ccx-no-print{display:none!important}}
</style>

<div class="ccx">
  <header class="ccx-hero"><div><h1><i class="ti ti-shield-check me-2"></i>Conflict Checker</h1><p>Detect · Explain · Resolve · Recheck</p></div><div class="ccx-hero-tag"><i class="ti ti-link me-1"></i> Connected to every scheduling subsystem</div></header>
  <div id="ccxAlert" class="alert d-none mt-3" role="alert"></div>
  <nav id="ccxSteps" class="ccx-steps ccx-no-print" aria-label="Conflict validation workflow"></nav>

  <section class="ccx-page active" id="ccxPage1"><div class="ccx-card"><div class="ccx-head"><div><span class="ccx-title-icon"><i class="ti ti-layout-dashboard"></i></span><h2 class="d-inline">Conflict Checker Dashboard</h2></div><button class="btn btn-primary btn-sm" id="ccxLoadQueue"><i class="ti ti-database-search me-1"></i>Load Validation Queue</button></div><div class="ccx-body">
    <div class="row g-3 mb-3"><div class="col-6 col-xl"><div class="ccx-stat st-blue"><i class="ti ti-database"></i><div><b id="statRecords">0</b><small>Total Records</small></div></div></div><div class="col-6 col-xl"><div class="ccx-stat st-red"><i class="ti ti-alert-triangle"></i><div><b id="statConflicts">0</b><small>Findings</small></div></div></div><div class="col-6 col-xl"><div class="ccx-stat st-amber"><i class="ti ti-shield-x"></i><div><b id="statUnresolved">0</b><small>Critical</small></div></div></div><div class="col-6 col-xl"><div class="ccx-stat st-green"><i class="ti ti-circle-check"></i><div><b id="statResolved">0</b><small>Resolved</small></div></div></div><div class="col-6 col-xl"><div class="ccx-stat st-purple"><i class="ti ti-clipboard-check"></i><div><b id="statValidated">0</b><small>Validated</small></div></div></div></div>
    <div class="ccx-filter"><h6><i class="ti ti-filter me-1"></i>Queue Filters</h6><div class="row g-2"><div class="col-md-3"><label>Academic Year</label><select id="ccxAY" class="form-select"></select></div><div class="col-md-3"><label>Semester</label><select id="ccxSemester" class="form-select"></select></div><div class="col-md-3"><label>Schedule Type</label><select id="ccxType" class="form-select"></select></div><div class="col-md-3"><label>Status</label><select id="ccxStatus" class="form-select"></select></div></div></div>
    <div class="row g-3 mt-1"><div class="col-lg-7"><div class="ccx-card h-100"><div class="ccx-head"><h2><i class="ti ti-list-check me-1"></i>Recent Validation Runs</h2><button class="btn btn-link btn-sm" id="ccxRefreshHistory">Refresh</button></div><div class="table-responsive"><table class="table ccx-table mb-0"><thead><tr><th>Run</th><th>Records</th><th>Critical</th><th>Status</th><th>Created</th><th></th></tr></thead><tbody id="ccxHistoryRows"></tbody></table></div></div></div><div class="col-lg-5"><div class="ccx-card h-100"><div class="ccx-head"><h2><i class="ti ti-plug-connected me-1"></i>Connected Sources</h2></div><div class="ccx-body"><div class="ccx-note"><i class="ti ti-check me-1"></i>Regular class schedules<br><i class="ti ti-check me-1"></i>Special class schedules<br><i class="ti ti-check me-1"></i>Exam timetables<br><i class="ti ti-check me-1"></i>Faculty qualifications and availability<br><i class="ti ti-check me-1"></i>Rooms, time blocks, and section assignments</div></div></div></div></div>
  </div></div></section>

  <section class="ccx-page" id="ccxPage2"><div class="ccx-card"><div class="ccx-head"><div><span class="ccx-title-icon"><i class="ti ti-database-search"></i></span><h2 class="d-inline">Load Validation Queue</h2></div><span class="ccx-pill p-blue" id="ccxSelectedCount"><i class="ti ti-checkbox"></i>0 selected</span></div><div class="ccx-body">
    <div class="d-flex gap-2 flex-wrap mb-3"><div class="input-group" style="max-width:400px"><span class="input-group-text"><i class="ti ti-search"></i></span><input id="ccxSearch" class="form-control" placeholder="Search section, subject, faculty, or room"></div><button class="btn btn-outline-primary" id="ccxRefreshQueue"><i class="ti ti-refresh me-1"></i>Refresh</button><button class="btn btn-outline-secondary" id="ccxSelectAll"><i class="ti ti-checkbox me-1"></i>Select All Visible</button></div>
    <div class="table-responsive"><table class="table ccx-table"><thead><tr><th><input type="checkbox" id="ccxMaster"></th><th>Section</th><th>Subject</th><th>Faculty / Proctor</th><th>Room</th><th>Day / Date</th><th>Time</th><th>Type</th><th>Status</th></tr></thead><tbody id="ccxQueueRows"></tbody></table></div>
    <div class="ccx-toolbar"><button class="btn btn-outline-primary" data-back="1"><i class="ti ti-arrow-left me-1"></i>Dashboard</button><button class="btn btn-primary" id="ccxRun"><i class="ti ti-player-play me-1"></i>Run Conflict Check</button></div>
  </div></div></section>

  <section class="ccx-page" id="ccxPage3"><div class="ccx-card"><div class="ccx-head"><div><span class="ccx-title-icon"><i class="ti ti-shield-search"></i></span><h2 class="d-inline">Run Rule Check / Findings</h2></div><span id="ccxRunBadge" class="ccx-pill p-gray"></span></div><div class="ccx-body">
    <div id="ccxFindingsBanner" class="ccx-note mb-3"></div><div class="ccx-type-grid mb-3" id="ccxTypeGrid"></div>
    <div class="d-flex gap-2 flex-wrap mb-2"><button class="btn btn-sm btn-primary" data-find-filter="All">All Findings</button><button class="btn btn-sm btn-outline-danger" data-find-filter="Error">Critical</button><button class="btn btn-sm btn-outline-warning" data-find-filter="Warning">Warnings</button></div>
    <div class="table-responsive"><table class="table ccx-table"><thead><tr><th>#</th><th>Type</th><th>Affected Record</th><th>What Conflicted</th><th>Severity</th><th>Status</th><th></th></tr></thead><tbody id="ccxFindingRows"></tbody></table></div>
    <div class="ccx-toolbar"><button class="btn btn-outline-primary" data-back="2"><i class="ti ti-arrow-left me-1"></i>Back to Queue</button><div class="d-flex gap-2"><button class="btn btn-outline-secondary" id="ccxRecheckTop"><i class="ti ti-refresh me-1"></i>Recheck</button><button class="btn btn-success" id="ccxProceed" disabled><i class="ti ti-check me-1"></i>Continue to Complete</button></div></div>
  </div></div></section>

  <section class="ccx-page" id="ccxPage4"><div class="ccx-card"><div class="ccx-head"><div><span class="ccx-title-icon"><i class="ti ti-file-search"></i></span><h2 class="d-inline">Conflict Details</h2></div><button class="btn btn-outline-primary btn-sm" data-back="3"><i class="ti ti-arrow-left me-1"></i>All Findings</button></div><div class="ccx-body"><div id="ccxConflictTitle" class="ccx-conflict-title mb-3"></div><div class="row g-3" id="ccxAffectedRecords"></div><div class="ccx-explain mt-3"><h6><i class="ti ti-bulb me-1"></i>Why this happened</h6><p id="ccxExplanation" class="mb-0 small"></p></div><div class="ccx-note mt-3"><b><i class="ti ti-tools me-1"></i>Suggested fix:</b> <span id="ccxSuggestedFix"></span></div><div class="ccx-toolbar"><button class="btn btn-outline-primary" data-back="3"><i class="ti ti-arrow-left me-1"></i>Back</button><button class="btn btn-primary" id="ccxResolve"><i class="ti ti-tool me-1"></i>Resolve Conflict</button></div></div></div></section>

  <section class="ccx-page" id="ccxPage5"><div class="ccx-card"><div class="ccx-head"><div><span class="ccx-title-icon"><i class="ti ti-tool"></i></span><h2 class="d-inline">Resolve Conflict</h2></div><span class="ccx-pill p-red" id="ccxResolveStatus"></span></div><div class="ccx-body"><div class="row g-3"><div class="col-lg-5"><div class="ccx-record"><div class="ccx-record-head"><i class="ti ti-alert-triangle me-1"></i>Conflict Information</div><div class="ccx-record-body" id="ccxResolveInfo"></div></div></div><div class="col-lg-7"><h6><i class="ti ti-bolt me-1"></i>Quick Actions</h6><div class="d-grid gap-2" id="ccxQuickActions"></div><div class="ccx-note mt-3"><i class="ti ti-info-circle me-1"></i>Critical findings cannot be manually dismissed. Correct the source schedule, then return and recheck.</div></div></div><div class="ccx-toolbar"><button class="btn btn-outline-primary" data-back="4"><i class="ti ti-arrow-left me-1"></i>Conflict Details</button><button class="btn btn-primary" id="ccxFixedRecheck"><i class="ti ti-refresh me-1"></i>I Fixed It — Recheck</button></div></div></div></section>

  <section class="ccx-page" id="ccxPage6"><div class="ccx-card"><div class="ccx-head"><div><span class="ccx-title-icon"><i class="ti ti-refresh"></i></span><h2 class="d-inline">Recheck Validation</h2></div><span class="ccx-pill p-blue"><i class="ti ti-shield-check"></i>Fresh database check</span></div><div class="ccx-body"><div class="row g-3"><div class="col-lg-6"><div class="ccx-record"><div class="ccx-record-head">Validation Progress</div><div class="ccx-record-body"><div id="ccxRecheckTasks"></div><div class="ccx-progress mt-3"><span id="ccxProgressBar"></span></div></div></div></div><div class="col-lg-6"><div class="ccx-compare"><div class="before" id="ccxBefore"></div><div class="after" id="ccxAfter"></div></div></div></div><div id="ccxRecheckResult" class="mt-3"></div><div class="ccx-toolbar"><button class="btn btn-outline-primary" data-back="3"><i class="ti ti-arrow-left me-1"></i>Findings</button><button class="btn btn-success" id="ccxSaveResult" disabled><i class="ti ti-device-floppy me-1"></i>Save Validation Result</button></div></div></div></section>

  <section class="ccx-page" id="ccxPage7"><div class="ccx-card"><div class="ccx-body ccx-success"><div class="ccx-success-icon"><i class="ti ti-check"></i></div><h2>Validation Complete</h2><p class="text-muted">Critical conflicts are clear and the validation result has been saved.</p><div class="row g-3 justify-content-center my-3" id="ccxCompleteStats"></div><div class="ccx-note text-start mx-auto" style="max-width:760px"><i class="ti ti-clipboard-check me-1"></i><b>Validated / Ready for Review.</b> Conflict-free draft schedules were advanced to Validated; publishing remains a separate authorized action.</div><div class="d-flex gap-2 flex-wrap justify-content-center mt-4 ccx-no-print"><button class="btn btn-outline-primary" id="ccxExport"><i class="ti ti-file-download me-1"></i>Export Report</button><button class="btn btn-outline-secondary" id="ccxPrint"><i class="ti ti-printer me-1"></i>Print Report</button><a class="btn btn-outline-primary" href="<?= BASE_URL ?>/modules/scheduling/index.php"><i class="ti ti-arrow-left me-1"></i>Back to Scheduling</a><a class="btn btn-primary" href="<?= BASE_URL ?>/modules/scheduling/pages/calendar-integration.php"><i class="ti ti-arrow-right me-1"></i>Continue to Review</a></div></div></div></section>
</div>

<script>
(()=>{'use strict';
const API='<?= BASE_URL ?>/api/scheduling/conflict-check.php';const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const steps=[['layout-dashboard','Dashboard'],['database-search','Load Queue'],['shield-search','Run Check'],['file-search','Conflict Details'],['tool','Resolve'],['refresh','Recheck'],['circle-check','Complete']];
const S={step:1,options:null,queue:[],selected:[],run:null,previousRun:null,finding:null,filter:'All'};
function alertMsg(m,t='danger'){const e=$('ccxAlert');e.className='alert alert-'+t+' mt-3';e.innerHTML=`<i class="ti ti-${t==='success'?'circle-check':'alert-circle'} me-1"></i>${esc(m)}`;e.scrollIntoView({behavior:'smooth',block:'center'})}function clearAlert(){$('ccxAlert').className='alert d-none mt-3'}
async function request(url,opt={}){const r=await fetch(url,opt),j=await r.json().catch(()=>({}));if(!r.ok||!j.ok)throw new Error(j.error||'Request failed.');return j}
function renderSteps(){$('ccxSteps').innerHTML=steps.map((s,i)=>`<button type="button" class="ccx-step ${S.step===i+1?'active':''} ${i+1<S.step?'done':''}" data-step="${i+1}"><span class="ccx-step-icon"><i class="ti ti-${s[0]}"></i></span><small>Step ${i+1}</small><b>${s[1]}</b></button>`).join('');$('ccxSteps').querySelectorAll('button').forEach(b=>b.onclick=()=>{const n=+b.dataset.step;if(n<=S.step||(n===2&&S.options))go(n)})}
function go(n){S.step=n;document.querySelectorAll('.ccx-page').forEach((p,i)=>p.classList.toggle('active',i===n-1));renderSteps();clearAlert();if(n===1){loadDashboard();loadHistory()}if(n===2)loadQueue();window.scrollTo({top:0,behavior:'smooth'})}
function fill(id,items,first){$(id).innerHTML=`<option value="">${esc(first)}</option>`+items.map(x=>`<option>${esc(x)}</option>`).join('')}
async function init(){try{S.options=await request(API+'?action=dashboard');fill('ccxAY',S.options.academic_years,'All academic years');fill('ccxSemester',S.options.semesters,'All semesters');$('ccxType').innerHTML=S.options.schedule_types.map(x=>`<option>${esc(x)}</option>`).join('');$('ccxStatus').innerHTML=S.options.statuses.map(x=>`<option>${esc(x)}</option>`).join('');renderDashboard(S.options.stats);renderSteps();loadHistory()}catch(e){alertMsg(e.message)}}
function renderDashboard(s){$('statRecords').textContent=s.records;$('statConflicts').textContent=s.conflicts;$('statUnresolved').textContent=s.unresolved;$('statResolved').textContent=s.resolved;$('statValidated').textContent=s.validated}
async function loadDashboard(){try{S.options=await request(API+'?action=dashboard');renderDashboard(S.options.stats)}catch(e){alertMsg(e.message)}}
async function loadHistory(){try{const j=await request(API+'?action=history');$('ccxHistoryRows').innerHTML=j.runs.length?j.runs.slice(0,8).map(r=>`<tr><td><b>${esc(r.run_id)}</b></td><td>${r.selected_count}</td><td><span class="ccx-pill ${+r.critical_count?'p-red':'p-green'}">${r.critical_count}</span></td><td>${statusPill(r.status)}</td><td>${esc(r.created_at)}</td><td><button class="btn btn-sm btn-outline-primary" data-history="${esc(r.run_id)}"><i class="ti ti-eye"></i></button></td></tr>`).join(''):'<tr><td colspan="6" class="ccx-empty"><i class="ti ti-history-off"></i>No validation runs yet.</td></tr>';$('ccxHistoryRows').querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>openRun(b.dataset.history))}catch(e){alertMsg(e.message)}}
function statusPill(s){const c=['Valid','Completed','Validated','Published','Ready to Publish'].includes(s)?'p-green':s==='Has Conflicts'?'p-red':s==='Draft'?'p-amber':'p-gray';return `<span class="ccx-pill ${c}">${esc(s)}</span>`}
function filters(){return{academic_year:$('ccxAY').value,semester:$('ccxSemester').value,schedule_type:$('ccxType').value,status:$('ccxStatus').value,search:$('ccxSearch')?.value||''}}
async function loadQueue(){try{const q=new URLSearchParams({action:'queue',...filters()});const j=await request(API+'?'+q);S.queue=j.records;S.selected=S.selected.filter(k=>S.queue.some(r=>r.key===k));renderQueue()}catch(e){alertMsg(e.message)}}
function renderQueue(){const rows=S.queue;$('ccxQueueRows').innerHTML=rows.length?rows.map(r=>`<tr><td><input class="form-check-input" type="checkbox" data-record="${esc(r.key)}" ${S.selected.includes(r.key)?'checked':''}></td><td><b>${esc(r.section_code||'Selected Students')}</b></td><td><b>${esc(r.subject_code||'—')}</b><small class="d-block text-muted">${esc(r.subject_name||'')}</small></td><td>${esc(r.teacher_name||'Unassigned')}</td><td>${esc(r.room_code||'Unassigned')}</td><td>${esc(r.date||r.day_of_week||'—')}</td><td>${esc((r.start_time||'').slice(0,5)+' – '+(r.end_time||'').slice(0,5))}</td><td><span class="ccx-pill ${r.schedule_type==='Regular'?'p-blue':r.schedule_type==='Special'?'p-purple':'p-amber'}">${esc(r.schedule_type)}</span></td><td>${statusPill(r.status)}</td></tr>`).join(''):'<tr><td colspan="9" class="ccx-empty"><i class="ti ti-database-off"></i>No schedule records match the filters.</td></tr>';$('ccxQueueRows').querySelectorAll('[data-record]').forEach(c=>c.onchange=()=>{S.selected=c.checked?[...new Set([...S.selected,c.dataset.record])]:S.selected.filter(k=>k!==c.dataset.record);updateSelected()});updateSelected()}
function updateSelected(){$('ccxSelectedCount').innerHTML=`<i class="ti ti-checkbox"></i>${S.selected.length} selected`;if($('ccxMaster'))$('ccxMaster').checked=S.queue.length>0&&S.queue.every(r=>S.selected.includes(r.key))}
async function runCheck(recheck=false){if(!S.selected.length){alertMsg('Select at least one schedule record.','warning');return}const btn=recheck?$('ccxFixedRecheck'):$('ccxRun');btn.disabled=true;try{const f=filters();const body={action:recheck?'recheck':'run',record_keys:S.selected,previous_run_id:recheck?(S.run?.run_id||''):'',academic_year:f.academic_year,semester:f.semester,schedule_type:f.schedule_type};const j=await request(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(recheck){S.previousRun=S.run;S.run=j.run;renderRecheck();go(6)}else{S.run=j.run;S.previousRun=null;renderFindings();go(3)}alertMsg(j.message,j.run.critical_count>0?'warning':'success')}catch(e){alertMsg(e.message)}finally{btn.disabled=false}}
async function openRun(id){try{const j=await request(API+'?action=run&run_id='+encodeURIComponent(id));S.run=j.run;S.selected=j.run.records.map(r=>r.record_key);renderFindings();go(3)}catch(e){alertMsg(e.message)}}
function renderFindings(){const r=S.run;$('ccxRunBadge').textContent=r.run_id;$('ccxRunBadge').className='ccx-pill '+(+r.critical_count?'p-red':'p-green');$('ccxFindingsBanner').className='alert alert-'+(+r.critical_count?'danger':'success')+' mb-3';$('ccxFindingsBanner').innerHTML=+r.critical_count?`<i class="ti ti-shield-x me-1"></i><b>${r.critical_count} critical finding(s).</b> They must be corrected and rechecked before completion.`:`<i class="ti ti-shield-check me-1"></i><b>No critical conflicts.</b> Review ${r.warning_count} warning(s), then continue.`;const counts={};r.findings.forEach(f=>counts[f.conflict_type]=(counts[f.conflict_type]||0)+1);const icons={'Faculty':'user-exclamation','Room':'door','Student/Section':'users','Time':'clock-exclamation','Capacity':'building','Duplicate':'copy','Eligibility':'certificate','Configured Rule':'settings','Availability':'calendar-off','Load':'scale'};$('ccxTypeGrid').innerHTML=Object.entries(counts).map(([k,v])=>`<div class="ccx-type"><i class="ti ti-${icons[k]||'alert-triangle'} text-primary"></i><b>${v}</b><small>${esc(k)}</small></div>`).join('')||'<div class="ccx-result pass"><i class="ti ti-circle-check"></i><b>No findings</b></div>';renderFindingRows();$('ccxProceed').disabled=+r.critical_count>0}
function renderFindingRows(){const fs=S.run.findings.filter(f=>S.filter==='All'||f.severity===S.filter);$('ccxFindingRows').innerHTML=fs.length?fs.map((f,i)=>{const p=f.affected_records.primary||{};return `<tr><td>${i+1}</td><td><span class="ccx-pill p-blue">${esc(f.conflict_type)}</span></td><td><b>${esc(p.section_code||p.schedule_type||'Record')}</b><small class="d-block text-muted">${esc(p.subject_code||'')} · ${esc(p.schedule_type||'')}</small></td><td>${esc(f.message)}<small class="d-block text-muted">${esc(f.explanation||'')}</small></td><td><span class="ccx-pill ${f.severity==='Error'?'p-red':f.severity==='Warning'?'p-amber':'p-blue'}">${f.severity==='Error'?'Critical':esc(f.severity)}</span></td><td><span class="ccx-pill ${+f.is_resolved?'p-green':'p-red'}">${+f.is_resolved?'Resolved':'Unresolved'}</span></td><td><button class="btn btn-sm btn-primary" data-view="${f.id}"><i class="ti ti-eye me-1"></i>View</button></td></tr>`}).join(''):'<tr><td colspan="7" class="ccx-empty"><i class="ti ti-shield-check"></i>No findings in this filter.</td></tr>';$('ccxFindingRows').querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>viewFinding(+b.dataset.view))}
async function viewFinding(id){try{const j=await request(API+'?action=conflict&id='+id);S.finding=j.finding;renderDetail();go(4)}catch(e){alertMsg(e.message)}}
function recordCard(r,label){if(!r)return'';return `<div class="col-lg-6"><div class="ccx-record"><div class="ccx-record-head"><i class="ti ti-calendar-event me-1"></i>${label}</div><div class="ccx-record-body"><dl class="ccx-dl"><dt>Schedule Type</dt><dd>${esc(r.schedule_type)}</dd><dt>Section</dt><dd>${esc(r.section_code||'Selected Students')}</dd><dt>Subject</dt><dd>${esc(r.subject_code)} — ${esc(r.subject_name)}</dd><dt>Faculty</dt><dd>${esc(r.teacher_name||'Unassigned')}</dd><dt>Day / Date</dt><dd>${esc(r.date||r.day_of_week)}</dd><dt>Time</dt><dd>${esc((r.start_time||'').slice(0,5)+' – '+(r.end_time||'').slice(0,5))}</dd><dt>Room</dt><dd>${esc(r.room_code||'Unassigned')}</dd></dl></div></div></div>`}
function renderDetail(){const f=S.finding,ar=f.affected_records||{},critical=f.severity==='Error';$('ccxConflictTitle').innerHTML=`<i class="ti ti-alert-triangle"></i><div><h5 class="mb-1">${esc(f.conflict_type)} Conflict</h5><span class="small">${esc(f.message)}</span></div><span class="ccx-pill ${critical?'p-red':'p-amber'} ms-auto">${critical?'Critical':esc(f.severity)}</span>`;$('ccxAffectedRecords').innerHTML=recordCard(ar.primary,'Affected Schedule')+recordCard(ar.related,'Conflicting Schedule');$('ccxExplanation').textContent=f.explanation||f.message;$('ccxSuggestedFix').textContent=f.recommended_action||'Review the source schedule.';renderResolve()}
function renderResolve(){const f=S.finding;if(!f)return;const p=f.affected_records?.primary||{};$('ccxResolveStatus').textContent=+f.is_resolved?'Resolved':'Unresolved';$('ccxResolveStatus').className='ccx-pill '+(+f.is_resolved?'p-green':'p-red');$('ccxResolveInfo').innerHTML=`<dl class="ccx-dl"><dt>Type</dt><dd>${esc(f.conflict_type)}</dd><dt>Section</dt><dd>${esc(p.section_code||'Selected Students')}</dd><dt>Subject</dt><dd>${esc(p.subject_code||'—')}</dd><dt>Faculty</dt><dd>${esc(p.teacher_name||'—')}</dd><dt>Schedule</dt><dd>${esc(p.schedule_label||'—')}</dd><dt>Room</dt><dd>${esc(p.room_code||'—')}</dd><dt>Status</dt><dd>${+f.is_resolved?'Resolved':'Unresolved'}</dd></dl>`;const actions=[['user-cog','Go to Teacher Mapping','Update teacher assignment','teacher-mapping'],['building','Go to Room Availability','Find and assign an available room','room-availability'],['users-group','Go to Section Assignment','Correct the section-subject assignment','section-assignment']];if(p.schedule_type==='Special')actions.unshift(['calendar-plus','Go to Special Class Scheduler','Edit this special class','special-class']);if(p.schedule_type==='Exam')actions.unshift(['calendar-stats','Go to Exam Timetable','Edit this exam schedule','exam-timetable']);$('ccxQuickActions').innerHTML=actions.map(a=>`<a class="ccx-action" href="${routeFor(a[3],p)}"><i class="ti ti-${a[0]}"></i><span><b>${a[1]}</b><small>${a[2]}</small></span><i class="ti ti-arrow-right"></i></a>`).join('')}
function routeFor(m,p){const paths={'teacher-mapping':'teacher-schedule-mapping.php','room-availability':'room-availability-checker.php','section-assignment':'section-assignment-tool.php','special-class':'special-class-scheduler.php','exam-timetable':'exam-timetable-generator.php'};return `<?= BASE_URL ?>/modules/scheduling/pages/${paths[m]}?record_id=${encodeURIComponent(p.id||'')}&section_code=${encodeURIComponent(p.section_code||'')}`}
function renderRecheck(){const before=S.previousRun,after=S.run;const tasks=['Load updated schedule records','Check faculty conflicts and eligibility','Check room availability and capacity','Check student / section conflicts','Check time blocks and duplicates','Apply configured rules','Save comparison'];$('ccxRecheckTasks').innerHTML=tasks.map(t=>`<div class="small mb-2"><i class="ti ti-circle-check text-success me-1"></i>${t}</div>`).join('');setTimeout(()=>$('ccxProgressBar').style.width='100%',80);$('ccxBefore').innerHTML=`<b><i class="ti ti-history me-1"></i>Before</b><p class="small mb-0 mt-2">Status: ${statusPill(before.status)}<br>Critical conflicts: <b>${before.critical_count}</b><br>Findings: ${before.findings_count}</p>`;$('ccxAfter').innerHTML=`<b><i class="ti ti-refresh me-1"></i>After Recheck</b><p class="small mb-0 mt-2">Status: ${statusPill(after.status)}<br>Critical conflicts: <b>${after.critical_count}</b><br>Resolved since previous: <b>${after.resolved_count}</b></p>`;$('ccxRecheckResult').className='ccx-result '+(+after.critical_count?'error':'pass');$('ccxRecheckResult').innerHTML=+after.critical_count?`<i class="ti ti-shield-x"></i><b>${after.critical_count} critical conflict(s) remain.</b><p>Return to the findings, resolve them in the owning module, then recheck again.</p>`:`<i class="ti ti-shield-check"></i><b>Conflict check passed.</b><p>The latest data has no critical conflicts and can be saved as Validated / Ready for Review.</p>`;$('ccxSaveResult').disabled=+after.critical_count>0}
async function complete(){const b=$('ccxSaveResult');b.disabled=true;try{const j=await request(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'complete',run_id:S.run.run_id})});S.run=j.run;renderComplete();go(7);alertMsg(j.message,'success')}catch(e){alertMsg(e.message)}finally{b.disabled=false}}
function renderComplete(){const r=S.run;$('ccxCompleteStats').innerHTML=[['database','Selected',r.selected_count,'st-blue'],['alert-triangle','Findings',r.findings_count,'st-red'],['circle-check','Resolved',r.resolved_count,'st-green'],['alert-circle','Warnings',r.warning_count,'st-amber']].map(x=>`<div class="col-6 col-md-3"><div class="ccx-stat ${x[3]}"><i class="ti ti-${x[0]}"></i><div><b>${x[2]}</b><small>${x[1]}</small></div></div></div>`).join('')}
function exportReport(){if(!S.run)return;const lines=[['Run ID','Type','Severity','Status','Affected Record','What Conflicted','Why','Suggested Action'],...S.run.findings.map(f=>{const p=f.affected_records?.primary||{};return[S.run.run_id,f.conflict_type,f.severity,+f.is_resolved?'Resolved':'Unresolved',`${p.schedule_type||''} ${p.section_code||''} ${p.subject_code||''}`,f.message,f.explanation,f.recommended_action]})];const csv=lines.map(row=>row.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\r\n'),blob=new Blob([csv],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`conflict-report-${S.run.run_id}.csv`;a.click();URL.revokeObjectURL(a.href)}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>go(+b.dataset.back));$('ccxLoadQueue').onclick=()=>go(2);$('ccxRefreshHistory').onclick=loadHistory;$('ccxRefreshQueue').onclick=loadQueue;$('ccxSearch').oninput=()=>{clearTimeout(window.ccxTimer);window.ccxTimer=setTimeout(loadQueue,250)};['ccxAY','ccxSemester','ccxType','ccxStatus'].forEach(id=>$(id).onchange=()=>{if(S.step===2)loadQueue()});$('ccxMaster').onchange=e=>{S.selected=e.target.checked?S.queue.map(r=>r.key):[];renderQueue()};$('ccxSelectAll').onclick=()=>{S.selected=S.queue.map(r=>r.key);renderQueue()};$('ccxRun').onclick=()=>runCheck(false);document.querySelectorAll('[data-find-filter]').forEach(b=>b.onclick=()=>{S.filter=b.dataset.findFilter;renderFindingRows()});$('ccxResolve').onclick=()=>go(5);$('ccxFixedRecheck').onclick=()=>runCheck(true);$('ccxRecheckTop').onclick=()=>{S.previousRun=S.run;runCheck(true)};$('ccxProceed').onclick=()=>{S.previousRun=S.run;S.run={...S.run,resolved_count:0};renderRecheck();go(6)};$('ccxSaveResult').onclick=complete;$('ccxExport').onclick=exportReport;$('ccxPrint').onclick=()=>window.print();init()});
})();
</script>
<?php require_once __DIR__ . '/../../../includes/layout-end.php'; ?>
