<?php
require_once __DIR__ . '/../../../config/config.php';
$pageTitle = 'Special Class Scheduler';
$activeModule = 'scheduling';
$activePage = 'special-class-scheduler';
$breadcrumbs = [
    ['label' => 'Class Scheduling', 'url' => BASE_URL . '/modules/scheduling/index.php'],
    ['label' => 'Special Class Scheduler', 'url' => null],
];
$hideModulePageBanner = true;
require_once __DIR__ . '/../../../includes/breadcrumbs.php';
require_once __DIR__ . '/../../../includes/layout-start.php';
renderBreadcrumbs($breadcrumbs);
?>

<style>
.spc-shell{--spc-navy:#082d5b;--spc-blue:#0d6efd;--spc-soft:#f4f8fd;--spc-border:#dce7f5;color:#15345e}
.spc-hero{display:flex;justify-content:space-between;gap:2rem;align-items:center;background:linear-gradient(120deg,#06284f,#0c4b7a);color:#fff;padding:1.35rem 1.6rem;border-radius:1rem;margin-bottom:1rem;box-shadow:0 10px 28px rgba(8,45,91,.16)}
.spc-hero h1{font-size:1.55rem;margin:0 0 .25rem}.spc-hero p{margin:0;color:#d9eaff}.spc-hero-note{font-size:.84rem;border-left:1px solid rgba(255,255,255,.45);padding-left:1rem;max-width:260px}
.spc-steps{display:grid;grid-template-columns:repeat(8,minmax(105px,1fr));gap:.5rem;margin-bottom:1rem;overflow-x:auto;padding-bottom:.25rem}
.spc-step{border:1px solid var(--spc-border);background:#fff;border-radius:.75rem;padding:.65rem .55rem;min-width:105px;color:#657995;text-align:left;transition:.18s;cursor:pointer}
.spc-step:hover{border-color:#9fc1ef}.spc-step.active{background:#eaf3ff;border-color:#3984eb;color:#084aa5;box-shadow:inset 0 -3px #0d6efd}.spc-step.done{color:#0a7a52;border-color:#a6dbc9}.spc-step-icon{width:2rem;height:2rem;display:grid;place-items:center;border-radius:50%;background:#e7eef8;margin-bottom:.4rem;font-size:1rem}.active .spc-step-icon{background:#0d6efd;color:#fff}.done .spc-step-icon{background:#d9f5e9;color:#08784e}.spc-step b{display:block;font-size:.76rem;line-height:1.15}.spc-step small{font-size:.66rem}
.spc-page{display:none}.spc-page.active{display:block}.spc-card{background:#fff;border:1px solid var(--spc-border);border-radius:.9rem;box-shadow:0 3px 14px rgba(30,65,105,.06)}.spc-card-head{padding:1rem 1.2rem;border-bottom:1px solid var(--spc-border);display:flex;justify-content:space-between;align-items:center;gap:1rem}.spc-card-head h2{font-size:1.05rem;margin:0;color:#092d63}.spc-card-body{padding:1.2rem}.spc-title-icon{width:2.35rem;height:2.35rem;display:inline-grid;place-items:center;background:#eaf3ff;color:#075fc7;border-radius:.65rem;margin-right:.65rem;font-size:1.2rem}
.spc-toolbar{display:flex;justify-content:space-between;gap:.75rem;align-items:center;margin-top:1rem;padding-top:1rem;border-top:1px solid var(--spc-border)}
.spc-choice{border:1px solid var(--spc-border);border-radius:.75rem;padding:1rem;background:#fff;cursor:pointer}.spc-choice.active{border:2px solid #0d6efd;background:#f3f8ff}.spc-choice i{font-size:1.35rem;color:#0d6efd}.spc-note{background:#eef6ff;border:1px solid #c9e0fb;border-radius:.7rem;padding:.8rem;font-size:.82rem;color:#31557c}.spc-muted{font-size:.77rem;color:#6d809a}.spc-pill{display:inline-flex;align-items:center;gap:.28rem;border-radius:999px;padding:.22rem .55rem;font-size:.7rem;font-weight:700}.pill-green{background:#dff5e9;color:#08784e}.pill-red{background:#ffe4e5;color:#b4232d}.pill-amber{background:#fff1cf;color:#8a5b00}.pill-blue{background:#e5f0ff;color:#095ebc}.pill-gray{background:#edf1f5;color:#586779}
.spc-table{font-size:.8rem}.spc-table thead th{background:#f4f8fd;color:#35577c;border-bottom-color:#dce7f5;white-space:nowrap}.spc-table td{vertical-align:middle}.spc-empty{text-align:center;padding:2.2rem;color:#73839a}.spc-empty i{font-size:2rem;display:block;margin-bottom:.4rem}
.spc-selection{border:1px solid #bed8f8;background:#f5f9ff;border-radius:.8rem;padding:1rem}.spc-avatar{width:2.8rem;height:2.8rem;border-radius:50%;display:grid;place-items:center;background:#dcecff;color:#075fc7;font-size:1.35rem}.spc-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:.85rem}.spc-stat{border:1px solid var(--spc-border);background:#fff;border-radius:.7rem;padding:.8rem}.spc-stat small{display:block;color:#71839b}.spc-stat b{font-size:.86rem;color:#173d6f}
.spc-result{display:flex;gap:.8rem;padding:.85rem;border-radius:.7rem;margin-bottom:.65rem;border:1px solid}.spc-result i{font-size:1.15rem;margin-top:.08rem}.spc-result.error{background:#fff4f4;border-color:#f4cccc;color:#8e2730}.spc-result.warning{background:#fff9e9;border-color:#f2dda5;color:#75550b}.spc-result.pass{background:#effaf5;border-color:#bfe5d3;color:#176747}.spc-result b{display:block;font-size:.84rem}.spc-result p{margin:.12rem 0 0;font-size:.79rem}.spc-result button{margin-left:auto;align-self:center;white-space:nowrap}
.spc-review{border:1px solid var(--spc-border);border-radius:.8rem;overflow:hidden;height:100%}.spc-review-head{display:flex;justify-content:space-between;align-items:center;background:#f4f8fd;padding:.75rem .9rem;font-weight:700;color:#173d6f}.spc-review-body{padding:.85rem}.spc-dl{display:grid;grid-template-columns:120px 1fr;gap:.38rem .65rem;font-size:.8rem}.spc-dl dt{color:#71839b;font-weight:600}.spc-dl dd{margin:0;color:#183d68;font-weight:600}
.spc-confirm{text-align:center;max-width:760px;margin:auto}.spc-confirm-icon{width:5rem;height:5rem;border-radius:50%;display:grid;place-items:center;background:#dff7e9;color:#06925d;font-size:2.8rem;margin:0 auto 1rem}.spc-reference{display:inline-flex;align-items:center;gap:.45rem;background:#eef5ff;color:#0b58b1;border-radius:999px;padding:.42rem .85rem;font-weight:700}
.spc-status-Draft{background:#e7eef8;color:#425c7f}.spc-status-Ready-to-Publish{background:#fff0ca;color:#7c5800}.spc-status-Published{background:#dff5e9;color:#08784e}.spc-status-Cancelled{background:#eceff3;color:#646e7a}.spc-detail-panel{border-left:4px solid #0d6efd}.spc-week{display:grid;grid-template-columns:repeat(6,1fr);gap:.5rem}.spc-day{border:1px solid var(--spc-border);border-radius:.65rem;min-height:125px;padding:.55rem;background:#fafcff}.spc-day b{font-size:.75rem}.spc-class-chip{display:block;background:#dcecff;color:#0b58b1;border-radius:.4rem;padding:.32rem;margin-top:.4rem;font-size:.68rem}
@media(max-width:992px){.spc-steps{grid-template-columns:repeat(8,130px)}.spc-grid{grid-template-columns:1fr 1fr}.spc-week{grid-template-columns:repeat(3,1fr)}}
@media(max-width:576px){.spc-hero{display:block}.spc-hero-note{margin-top:1rem}.spc-grid,.spc-week{grid-template-columns:1fr}.spc-dl{grid-template-columns:1fr}.spc-toolbar{flex-wrap:wrap}}
@media print{body *{visibility:hidden!important}#spcPage7,#spcPage7 *{visibility:visible!important}#spcPage7{position:absolute;inset:0}.spc-no-print{display:none!important}}
</style>

<div class="spc-shell">
  <header class="spc-hero">
    <div><h1><i class="ti ti-calendar-plus me-2"></i>Special Class Scheduler</h1><p>Create, validate, save, and publish non-regular classes through one controlled workflow.</p></div>
    <div class="spc-hero-note"><i class="ti ti-sparkles me-1"></i> Flexible schedules. Clear checks. Separate saving and publishing.</div>
  </header>

  <div id="spcAlert" class="alert d-none" role="alert"></div>
  <nav class="spc-steps spc-no-print" id="spcSteps" aria-label="Special class workflow"></nav>

  <section class="spc-page active" id="spcPage1">
    <div class="spc-card"><div class="spc-card-head"><div><span class="spc-title-icon"><i class="ti ti-file-description"></i></span><span><h2 class="d-inline">Class Details</h2><span class="spc-muted d-block ms-5">Define the special class and academic context.</span></span></div><span class="spc-pill pill-blue"><i class="ti ti-number-1"></i> Step 1</span></div>
      <div class="spc-card-body"><div class="row g-3">
        <div class="col-md-4"><label class="form-label fw-semibold"><i class="ti ti-category me-1"></i>Class Type *</label><select id="spcType" class="form-select"></select></div>
        <div class="col-md-8"><label class="form-label fw-semibold"><i class="ti ti-heading me-1"></i>Class Title *</label><input id="spcTitle" class="form-control" maxlength="150" placeholder="e.g. IT301 Remedial Class"></div>
        <div class="col-md-3"><label class="form-label fw-semibold"><i class="ti ti-school me-1"></i>Program *</label><select id="spcProgram" class="form-select"></select></div>
        <div class="col-md-3"><label class="form-label fw-semibold"><i class="ti ti-calendar-stats me-1"></i>Academic Year *</label><select id="spcAcademicYear" class="form-select"></select></div>
        <div class="col-md-3"><label class="form-label fw-semibold"><i class="ti ti-calendar-event me-1"></i>Semester *</label><select id="spcSemester" class="form-select"></select></div>
        <div class="col-md-3"><label class="form-label fw-semibold"><i class="ti ti-book-2 me-1"></i>Subject *</label><select id="spcSubject" class="form-select"></select></div>
        <div class="col-12"><label class="form-label fw-semibold"><i class="ti ti-notes me-1"></i>Description / Remarks</label><textarea id="spcRemarks" class="form-control" rows="3" maxlength="255" placeholder="Purpose, scope, or staff notes"></textarea></div>
      </div><div class="spc-toolbar"><button class="btn btn-outline-secondary" type="button" id="spcNewBtn"><i class="ti ti-refresh me-1"></i>Clear</button><button class="btn btn-primary" type="button" data-next="2">Assign Students / Section <i class="ti ti-arrow-right ms-1"></i></button></div></div>
    </div>
  </section>

  <section class="spc-page" id="spcPage2">
    <div class="spc-card"><div class="spc-card-head"><div><span class="spc-title-icon"><i class="ti ti-users"></i></span><h2 class="d-inline">Assign Students / Section</h2></div><span class="spc-pill pill-blue"><i class="ti ti-number-2"></i> Step 2</span></div>
      <div class="spc-card-body"><div class="row g-3 mb-3">
        <div class="col-md-6"><div class="spc-choice active" data-mode="Section"><i class="ti ti-users-group"></i><b class="d-block mt-1">Whole Section</b><span class="spc-muted">Assign every active student represented by one section.</span></div></div>
        <div class="col-md-6"><div class="spc-choice" data-mode="Students"><i class="ti ti-user-check"></i><b class="d-block mt-1">Selected Students</b><span class="spc-muted">Build a targeted roster from enrollment records.</span></div></div>
      </div>
      <div id="spcSectionMode"><label class="form-label fw-semibold"><i class="ti ti-layout-list me-1"></i>Select Section *</label><select id="spcSection" class="form-select"></select><div id="spcSectionInfo" class="spc-note mt-3"></div></div>
      <div id="spcStudentMode" class="d-none"><div class="d-flex justify-content-between gap-2 flex-wrap mb-2"><div class="input-group" style="max-width:380px"><span class="input-group-text"><i class="ti ti-search"></i></span><input id="spcStudentSearch" class="form-control" placeholder="Search student name or number"></div><span class="spc-pill pill-blue" id="spcStudentCount"><i class="ti ti-user-check"></i> 0 selected</span></div>
        <div class="table-responsive"><table class="table spc-table"><thead><tr><th></th><th><i class="ti ti-id"></i> Student No.</th><th><i class="ti ti-user"></i> Name</th><th><i class="ti ti-school"></i> Program</th><th><i class="ti ti-progress-check"></i> Record</th><th><i class="ti ti-shield-check"></i> Eligibility</th></tr></thead><tbody id="spcStudentRows"></tbody></table></div>
      </div>
      <div class="spc-toolbar"><button class="btn btn-outline-primary" data-back="1"><i class="ti ti-arrow-left me-1"></i>Back</button><button class="btn btn-primary" data-next="3">Assign Faculty <i class="ti ti-arrow-right ms-1"></i></button></div></div>
    </div>
  </section>

  <section class="spc-page" id="spcPage3">
    <div class="spc-card"><div class="spc-card-head"><div><span class="spc-title-icon"><i class="ti ti-user-check"></i></span><h2 class="d-inline">Assign Faculty</h2></div><span class="spc-pill pill-blue"><i class="ti ti-number-3"></i> Step 3</span></div>
      <div class="spc-card-body"><div id="spcFacultySelected" class="spc-selection mb-3 d-none"></div><div class="d-flex gap-2 flex-wrap mb-2"><div class="input-group" style="max-width:380px"><span class="input-group-text"><i class="ti ti-search"></i></span><input id="spcTeacherSearch" class="form-control" placeholder="Search teacher or specialization"></div><select id="spcTeacherDepartment" class="form-select" style="max-width:260px"><option value="">All departments</option></select></div>
        <div class="table-responsive"><table class="table spc-table"><thead><tr><th><i class="ti ti-id"></i> Faculty ID</th><th><i class="ti ti-user"></i> Teacher</th><th><i class="ti ti-building-community"></i> Department</th><th><i class="ti ti-certificate"></i> Specialization</th><th><i class="ti ti-scale"></i> Current / Projected / Max</th><th><i class="ti ti-activity"></i> Status</th><th></th></tr></thead><tbody id="spcTeacherRows"></tbody></table></div>
        <div class="mt-3"><h6><i class="ti ti-calendar-week me-1 text-primary"></i>Teacher's Existing Weekly Schedule</h6><div class="spc-week" id="spcTeacherWeek"></div></div>
        <div class="spc-toolbar"><button class="btn btn-outline-primary" data-back="2"><i class="ti ti-arrow-left me-1"></i>Back</button><button class="btn btn-primary" data-next="4">Schedule & Room <i class="ti ti-arrow-right ms-1"></i></button></div></div>
    </div>
  </section>

  <section class="spc-page" id="spcPage4">
    <div class="spc-card"><div class="spc-card-head"><div><span class="spc-title-icon"><i class="ti ti-calendar-time"></i></span><h2 class="d-inline">Schedule & Room</h2></div><span class="spc-pill pill-blue"><i class="ti ti-number-4"></i> Step 4</span></div>
      <div class="spc-card-body"><div class="row g-3">
        <div class="col-lg-5"><div class="spc-card h-100"><div class="spc-card-head"><h2><i class="ti ti-clock-edit me-1"></i>Schedule Details</h2></div><div class="spc-card-body"><label class="form-label fw-semibold"><i class="ti ti-calendar me-1"></i>Date *</label><input type="date" id="spcClassDate" class="form-control mb-3"><label class="form-label fw-semibold"><i class="ti ti-clock-hour-4 me-1"></i>Configured Time Block *</label><select id="spcTimeBlock" class="form-select"></select><div id="spcSchedulePreview" class="spc-note mt-3"><i class="ti ti-info-circle me-1"></i>Select a date and configured class time block.</div></div></div></div>
        <div class="col-lg-7"><div class="spc-card h-100"><div class="spc-card-head"><h2><i class="ti ti-door me-1"></i>Available Rooms</h2><span class="spc-muted">Capacity uses the selected roster/section.</span></div><div class="spc-card-body"><div class="table-responsive"><table class="table spc-table"><thead><tr><th></th><th>Room</th><th>Building</th><th>Type</th><th>Capacity</th><th>Status</th></tr></thead><tbody id="spcRoomRows"></tbody></table></div><div id="spcRoomSelected" class="spc-selection d-none"></div></div></div></div>
      </div><div class="spc-toolbar"><button class="btn btn-outline-primary" data-back="3"><i class="ti ti-arrow-left me-1"></i>Back</button><button class="btn btn-primary" data-next="5"><i class="ti ti-shield-search me-1"></i>Check Conflicts</button></div></div>
    </div>
  </section>

  <section class="spc-page" id="spcPage5">
    <div class="spc-card"><div class="spc-card-head"><div><span class="spc-title-icon"><i class="ti ti-shield-search"></i></span><h2 class="d-inline">Check Conflicts</h2></div><button class="btn btn-outline-primary btn-sm" id="spcRecheck"><i class="ti ti-refresh me-1"></i>Run Check Again</button></div>
      <div class="spc-card-body"><div id="spcValidationBanner" class="spc-note mb-3"><i class="ti ti-loader-2 me-1"></i>Validation has not run yet.</div><div class="row g-3"><div class="col-lg-7"><h6><i class="ti ti-alert-triangle me-1 text-danger"></i>Issues to Resolve</h6><div id="spcValidationIssues"></div></div><div class="col-lg-5"><h6><i class="ti ti-circle-check me-1 text-success"></i>Checks Passed</h6><div id="spcValidationPasses"></div></div></div>
      <div class="spc-toolbar"><button class="btn btn-outline-primary" data-back="4"><i class="ti ti-arrow-left me-1"></i>Resolve Schedule</button><button class="btn btn-primary" id="spcToReview" disabled>Review & Save <i class="ti ti-arrow-right ms-1"></i></button></div></div>
    </div>
  </section>

  <section class="spc-page" id="spcPage6">
    <div class="spc-card"><div class="spc-card-head"><div><span class="spc-title-icon"><i class="ti ti-clipboard-check"></i></span><h2 class="d-inline">Review & Save</h2></div><span class="spc-pill pill-amber"><i class="ti ti-lock-check"></i> Final recheck occurs on save</span></div>
      <div class="spc-card-body"><div class="row g-3" id="spcReviewGrid"></div><div class="spc-note mt-3"><i class="ti ti-info-circle me-1"></i><b>Save Draft</b> stores the work without publishing. <b>Confirm & Save</b> rechecks all critical data and marks the class Ready to Publish.</div>
      <div class="spc-toolbar"><button class="btn btn-outline-primary" data-back="5"><i class="ti ti-arrow-left me-1"></i>Back</button><div class="d-flex gap-2"><button class="btn btn-outline-secondary" id="spcSaveDraft"><i class="ti ti-device-floppy me-1"></i>Save Draft</button><button class="btn btn-success" id="spcConfirmSave"><i class="ti ti-circle-check me-1"></i>Confirm & Save</button></div></div></div>
    </div>
  </section>

  <section class="spc-page" id="spcPage7">
    <div class="spc-card"><div class="spc-card-body spc-confirm py-5"><div class="spc-confirm-icon"><i class="ti ti-check"></i></div><h2>Special Class Saved Successfully</h2><p class="text-muted">The class was saved separately from publication.</p><div class="spc-reference mb-3" id="spcConfirmationRef"></div><div class="spc-review text-start" id="spcConfirmationDetails"></div><div class="d-flex justify-content-center flex-wrap gap-2 mt-4 spc-no-print"><button class="btn btn-outline-primary" id="spcViewDetails"><i class="ti ti-eye me-1"></i>View Details</button><button class="btn btn-outline-secondary" id="spcPrint"><i class="ti ti-printer me-1"></i>Print</button><button class="btn btn-primary" id="spcCreateAnother"><i class="ti ti-plus me-1"></i>Create Another</button><button class="btn btn-outline-primary" id="spcBackList"><i class="ti ti-list me-1"></i>Back to List</button></div></div></div>
  </section>

  <section class="spc-page" id="spcPage8">
    <div class="spc-card"><div class="spc-card-head"><div><span class="spc-title-icon"><i class="ti ti-speakerphone"></i></span><h2 class="d-inline">Manage & Publish Special Classes</h2></div><button class="btn btn-primary btn-sm" id="spcCreateFromList"><i class="ti ti-plus me-1"></i>Create Special Class</button></div>
      <div class="spc-card-body"><div class="d-flex gap-2 flex-wrap mb-3"><div class="input-group" style="max-width:360px"><span class="input-group-text"><i class="ti ti-search"></i></span><input id="spcListSearch" class="form-control" placeholder="Search reference, class, subject, teacher"></div><select id="spcListStatus" class="form-select" style="max-width:220px"><option value="">All statuses</option></select><button class="btn btn-outline-primary" id="spcListRefresh"><i class="ti ti-refresh"></i></button></div>
        <div class="table-responsive"><table class="table spc-table"><thead><tr><th>Reference</th><th>Class</th><th>Schedule</th><th>Faculty / Room</th><th>Participants</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody id="spcListRows"></tbody></table></div><div id="spcManageDetail" class="spc-card spc-detail-panel mt-3 d-none"></div>
      </div>
    </div>
  </section>
</div>

<script>
(() => {
'use strict';
const API='<?= BASE_URL ?>/api/scheduling/special-class.php';
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const steps=[['file-description','Class Details'],['users','Students / Section'],['user-check','Faculty'],['calendar-time','Schedule & Room'],['shield-search','Conflicts'],['clipboard-check','Review & Save'],['circle-check','Confirmation'],['speakerphone','Publish']];
const S={step:1,data:null,id:0,mode:'Section',studentKeys:[],teacherId:null,roomId:null,lastValidation:null,saved:null};
function alertMsg(message,type='danger'){const el=$('spcAlert');el.className='alert alert-'+type;el.innerHTML='<i class="ti ti-'+(type==='success'?'circle-check':'alert-circle')+' me-1"></i>'+esc(message);el.scrollIntoView({behavior:'smooth',block:'center'});}function clearAlert(){$('spcAlert').className='alert d-none';}
async function request(url,opt={}){const r=await fetch(url,opt),j=await r.json().catch(()=>({}));if(!r.ok||!j.ok)throw new Error(j.error||'Request failed.');return j;}
function renderSteps(){ $('spcSteps').innerHTML=steps.map((s,i)=>`<button class="spc-step ${S.step===i+1?'active':''} ${i+1<S.step?'done':''}" data-step="${i+1}" type="button"><span class="spc-step-icon"><i class="ti ti-${s[0]}"></i></span><small>Step ${i+1}</small><b>${s[1]}</b></button>`).join('');$('spcSteps').querySelectorAll('button').forEach(b=>b.onclick=()=>{const n=+b.dataset.step;if(n<=S.step||n===8)go(n,false)});}
function go(n,guard=true){if(guard&&!validateStep(S.step))return;S.step=n;document.querySelectorAll('.spc-page').forEach((p,i)=>p.classList.toggle('active',i===n-1));renderSteps();clearAlert();if(n===5)runValidation();if(n===6)renderReview();if(n===8)loadList();window.scrollTo({top:0,behavior:'smooth'});}
function value(id){return $(id).value.trim()}function selectedSubject(){return S.data.subjects.find(x=>+x.id===+value('spcSubject'))}function selectedTeacher(){return S.data.teachers.find(x=>+x.id===+S.teacherId)}function selectedRoom(){return S.data.rooms.find(x=>+x.id===+S.roomId)}function selectedSection(){return S.data.sections.find(x=>+x.id===+value('spcSection'))}function selectedBlock(){return S.data.time_blocks.find(x=>+x.id===+value('spcTimeBlock'))}
function validateStep(step){let message='';if(step===1&&!value('spcTitle'))message='Enter a class title.';else if(step===1&&(!value('spcProgram')||!value('spcAcademicYear')||!value('spcSemester')||!value('spcSubject')))message='Complete the academic year, semester, program, and subject.';else if(step===2&&S.mode==='Section'&&!value('spcSection'))message='Select a section.';else if(step===2&&S.mode==='Students'&&!S.studentKeys.length)message='Select at least one student.';else if(step===3&&!S.teacherId)message='Select a faculty member.';else if(step===4&&(!value('spcClassDate')||!value('spcTimeBlock')||!S.roomId))message='Select a date, configured time block, and room.';if(message){alertMsg(message,'warning');return false}return true}
function fill(id,items,placeholder,render){$(id).innerHTML=`<option value="">${esc(placeholder)}</option>`+items.map(render).join('')}
async function load(){try{S.data=await request(API+'?action=options');fill('spcType',S.data.types,'Select type',x=>`<option>${esc(x)}</option>`);fill('spcProgram',S.data.programs,'Select program',x=>`<option>${esc(x)}</option>`);fill('spcAcademicYear',S.data.academic_years,'Select academic year',x=>`<option>${esc(x)}</option>`);fill('spcSemester',S.data.semesters,'Select semester',x=>`<option>${esc(x)}</option>`);fill('spcTimeBlock',S.data.time_blocks,'Select configured block',x=>`<option value="${x.id}">${esc(x.code+' · '+x.label)}</option>`);$('spcListStatus').innerHTML='<option value="">All statuses</option>'+S.data.statuses.map(x=>`<option>${esc(x)}</option>`).join('');$('spcType').value='Remedial';const depts=[...new Set(S.data.teachers.map(t=>t.department).filter(Boolean))];$('spcTeacherDepartment').innerHTML='<option value="">All departments</option>'+depts.map(x=>`<option>${esc(x)}</option>`).join('');renderSubjects();renderSections();renderStudents();renderTeachers();renderRooms();renderWeek();renderSteps();}catch(e){alertMsg(e.message)}}
function renderSubjects(){if(!S.data)return;const p=value('spcProgram'),sem=value('spcSemester');const list=S.data.subjects.filter(s=>(!p||s.program===p||s.program==='ALL')&&(!sem||!s.semester||s.semester===sem));const old=value('spcSubject');fill('spcSubject',list,'Select subject',s=>`<option value="${s.id}">${esc(s.code+' — '+s.name)}</option>`);if(list.some(x=>String(x.id)===old))$('spcSubject').value=old;renderTeachers()}
function renderSections(){if(!S.data)return;const p=value('spcProgram'),ay=value('spcAcademicYear'),sem=value('spcSemester');const list=S.data.sections.filter(s=>(!p||s.program===p)&&(!ay||s.academic_year===ay)&&(!sem||s.semester===sem));const old=value('spcSection');fill('spcSection',list,'Select section',s=>`<option value="${s.id}">${esc(s.code+' — '+s.name+' ('+s.current_students+' students)')}</option>`);if(list.some(x=>String(x.id)===old))$('spcSection').value=old;renderSectionInfo()}
function setMode(mode){S.mode=mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x.dataset.mode===mode));$('spcSectionMode').classList.toggle('d-none',mode!=='Section');$('spcStudentMode').classList.toggle('d-none',mode!=='Students');renderRooms()}
async function refreshStudents(){try{const j=await request(API+'?action=students&subject_id='+encodeURIComponent(value('spcSubject')));S.data.students=j.students;renderStudents()}catch(e){alertMsg(e.message)}}
function renderStudents(){if(!S.data)return;const q=value('spcStudentSearch').toLowerCase();const rows=S.data.students.filter(s=>!q||`${s.student_ref} ${s.name} ${s.program}`.toLowerCase().includes(q));$('spcStudentRows').innerHTML=rows.length?rows.map(s=>{const sel=S.studentKeys.includes(s.key),bad=s.eligibility_status==='Not Eligible';const cls=bad?'pill-red':s.eligibility_status==='Eligible'?'pill-green':s.eligibility_status==='Conditional'?'pill-amber':'pill-gray';return `<tr><td><input class="form-check-input" type="checkbox" data-student="${esc(s.key)}" ${sel?'checked':''} ${bad?'disabled':''}></td><td><b>${esc(s.student_ref)}</b></td><td>${esc(s.name)}<small class="d-block text-muted">${esc(s.email||'')}</small></td><td>${esc(s.program||'—')}${s.year_level?` · Year ${s.year_level}`:''}</td><td>${esc(s.record_status)}</td><td><span class="spc-pill ${cls}" title="${esc(s.eligibility_note)}"><i class="ti ti-shield-check"></i>${esc(s.eligibility_status)}</span></td></tr>`}).join(''):'<tr><td colspan="6" class="spc-empty"><i class="ti ti-user-off"></i>No matching enrollment records.</td></tr>';$('spcStudentRows').querySelectorAll('[data-student]').forEach(c=>c.onchange=()=>{S.studentKeys=c.checked?[...new Set([...S.studentKeys,c.dataset.student])]:S.studentKeys.filter(k=>k!==c.dataset.student);$('spcStudentCount').innerHTML=`<i class="ti ti-user-check"></i> ${S.studentKeys.length} selected`;renderRooms()});$('spcStudentCount').innerHTML=`<i class="ti ti-user-check"></i> ${S.studentKeys.length} selected`;}
function renderSectionInfo(){const s=selectedSection();$('spcSectionInfo').innerHTML=s?`<i class="ti ti-info-circle me-1"></i><b>${esc(s.code)}</b> · ${esc(s.program)} Year ${s.year_level} · ${s.current_students}/${s.max_students||'—'} students · ${esc(s.academic_year)} ${esc(s.semester)}`:'<i class="ti ti-info-circle me-1"></i>Choose an active section from the shared Section Assignment data.';renderRooms()}
function teacherQualification(t){if(!S.data.qualification_configured)return{eligible:true,label:'Not configured'};const sid=+value('spcSubject'),q=(t.qualifications||[]).find(x=>+x.subject_id===sid);return{eligible:!!q,label:q?(q.specialization_label||q.subject_code):'Not qualified'}}
function renderTeachers(){if(!S.data)return;const q=value('spcTeacherSearch').toLowerCase(),dept=value('spcTeacherDepartment'),sub=selectedSubject(),units=+(sub?.units||0);const rows=S.data.teachers.filter(t=>(!q||`${t.full_name} ${t.employee_no} ${t.department} ${(t.qualifications||[]).map(x=>x.specialization_label).join(' ')}`.toLowerCase().includes(q))&&(!dept||t.department===dept));$('spcTeacherRows').innerHTML=rows.length?rows.map(t=>{const qual=teacherQualification(t),current=+t.current_load_units,projected=current+units,max=+t.max_load_units,over=max>0&&projected>max,active=t.status==='Active',disabled=!active||!qual.eligible||over,sel=+S.teacherId===+t.id;return `<tr><td><b>${esc(t.employee_no||'—')}</b></td><td>${esc(t.full_name)}</td><td>${esc(t.department||'—')}</td><td>${esc(qual.label)}</td><td><b>${current} / ${projected} / ${max||'—'}</b> units</td><td><span class="spc-pill ${active&&!over?'pill-green':'pill-red'}">${over?'Overload':esc(t.status)}</span></td><td class="text-end"><button class="btn btn-sm btn-${sel?'success':'primary'}" data-teacher="${t.id}" ${disabled?'disabled':''}><i class="ti ti-${sel?'check':'user-plus'} me-1"></i>${sel?'Selected':'Select'}</button></td></tr>`}).join(''):'<tr><td colspan="7" class="spc-empty"><i class="ti ti-user-off"></i>No faculty match the filters.</td></tr>';$('spcTeacherRows').querySelectorAll('[data-teacher]').forEach(b=>b.onclick=()=>{S.teacherId=+b.dataset.teacher;renderTeachers();renderSelectedTeacher();renderWeek()});renderSelectedTeacher()}
function renderSelectedTeacher(){const t=selectedTeacher();$('spcFacultySelected').classList.toggle('d-none',!t);if(!t)return;const q=teacherQualification(t);$('spcFacultySelected').innerHTML=`<div class="d-flex align-items-center gap-3 flex-wrap"><span class="spc-avatar"><i class="ti ti-user"></i></span><div class="me-auto"><b>${esc(t.full_name)}</b><span class="spc-muted d-block">${esc(t.employee_no||'—')} · ${esc(t.department||'No department')}</span></div><div><small class="spc-muted">Specialization</small><b class="d-block">${esc(q.label)}</b></div><div><small class="spc-muted">Current / Max Load</small><b class="d-block">${esc(t.current_load_units)} / ${esc(t.max_load_units)} units</b></div></div>`}
function renderWeek(){if(!S.data)return;const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];const ay=value('spcAcademicYear'),sem=value('spcSemester');$('spcTeacherWeek').innerHTML=days.map(day=>{const entries=S.data.schedule_entries.filter(e=>+e.teacher_id===+S.teacherId&&e.day_of_week===day&&(!ay||e.academic_year===ay)&&(!sem||e.semester===sem));return `<div class="spc-day"><b>${day.slice(0,3)}</b>${entries.length?entries.map(e=>`<span class="spc-class-chip"><i class="ti ti-lock me-1"></i>${esc(e.subject_code)}<br>${esc(e.start_time.slice(0,5)+'–'+e.end_time.slice(0,5))}</span>`).join(''):'<span class="spc-muted d-block mt-2"><i class="ti ti-circle-check me-1"></i>No occupied slot</span>'}</div>`}).join('')}
function participantCount(){return S.mode==='Section'?+(selectedSection()?.current_students||0):S.studentKeys.length}
function renderRooms(){if(!S.data)return;const count=participantCount();$('spcRoomRows').innerHTML=S.data.rooms.map(r=>{const ok=r.status==='Available'&&+r.capacity>=count,sel=+S.roomId===+r.id;return `<tr><td><input class="form-check-input" type="radio" name="spcRoom" data-room="${r.id}" ${sel?'checked':''} ${ok?'':'disabled'}></td><td><b>${esc(r.room_code)}</b></td><td>${esc(r.building||'—')}</td><td>${esc(r.room_type)}</td><td>${r.capacity} ${+r.capacity<count?'<small class="text-danger d-block">Too small</small>':''}</td><td><span class="spc-pill ${ok?'pill-green':'pill-red'}">${ok?'Available':esc(r.status==='Available'?'Insufficient capacity':r.status)}</span></td></tr>`}).join('');$('spcRoomRows').querySelectorAll('[data-room]').forEach(r=>r.onchange=()=>{S.roomId=+r.dataset.room;renderRooms();renderRoomSelected()});renderRoomSelected()}
function renderRoomSelected(){const r=selectedRoom();$('spcRoomSelected').classList.toggle('d-none',!r);if(r)$('spcRoomSelected').innerHTML=`<b><i class="ti ti-door me-1"></i>${esc(r.room_code)}</b><span class="spc-muted d-block">${esc(r.building||'No building')} · ${esc(r.room_type)} · Capacity ${r.capacity}</span>`}
function updateSchedulePreview(){const d=value('spcClassDate'),b=selectedBlock();$('spcSchedulePreview').innerHTML=d&&b?`<i class="ti ti-calendar-check me-1"></i><b>${esc(new Date(d+'T00:00:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'}))}</b><br><span class="ms-4">${esc(b.label)} · Shared Time Block ${esc(b.code)}</span>`:'<i class="ti ti-info-circle me-1"></i>Select a date and configured class time block.'}
function payload(){const b=selectedBlock();return{action:'save',id:S.id,title:value('spcTitle'),special_type:value('spcType'),program:value('spcProgram'),academic_year:value('spcAcademicYear'),semester:value('spcSemester'),subject_id:+value('spcSubject'),assignment_mode:S.mode,section_id:S.mode==='Section'?+value('spcSection'):null,student_keys:S.mode==='Students'?S.studentKeys:[],teacher_id:S.teacherId,room_id:S.roomId,time_block_id:b?+b.id:null,class_date:value('spcClassDate'),start_time:b?b.start_time:'',end_time:b?b.end_time:'',remarks:value('spcRemarks')}}
async function runValidation(){if(!validateStep(4))return;const p=payload(),qs=new URLSearchParams({...p,action:'check',student_keys:p.student_keys.join(',')});$('spcValidationBanner').innerHTML='<i class="ti ti-loader-2 me-1"></i>Rechecking shared schedules, faculty, students, time block, and room data…';try{const j=await request(API+'?'+qs);S.lastValidation=j.validation;renderValidation()}catch(e){alertMsg(e.message);$('spcValidationBanner').innerHTML='<i class="ti ti-alert-circle me-1"></i>Validation could not complete.'}}
function issueHtml(x){const icon=x.level==='warning'?'alert-triangle':'alert-circle';return `<div class="spc-result ${x.level}"><i class="ti ti-${icon}"></i><div><b>${esc(x.label)}</b><p>${esc(x.message)}</p></div>${x.action?`<button class="btn btn-sm btn-outline-secondary" data-fix="${esc(x.key)}">${esc(x.action)}</button>`:''}</div>`}
function renderValidation(){const v=S.lastValidation,issues=[...v.errors,...v.warnings];$('spcValidationBanner').className='mb-3 alert alert-'+(v.valid?'success':'danger');$('spcValidationBanner').innerHTML=v.valid?`<i class="ti ti-circle-check me-1"></i><b>No critical conflicts found.</b> ${v.warnings.length} review warning(s) remain and are shown transparently.`:`<i class="ti ti-shield-x me-1"></i><b>${v.errors.length} critical issue(s) found.</b> Resolve them and run the check again.`;$('spcValidationIssues').innerHTML=issues.length?issues.map(issueHtml).join(''):'<div class="spc-result pass"><i class="ti ti-circle-check"></i><div><b>All clear</b><p>No issues require action.</p></div></div>';$('spcValidationPasses').innerHTML=v.passes.map(x=>`<div class="spc-result pass"><i class="ti ti-circle-check"></i><div><b>${esc(x.label)}</b><p>${esc(x.message)}</p></div></div>`).join('');$('spcToReview').disabled=!v.valid;$('spcValidationIssues').querySelectorAll('[data-fix]').forEach(b=>b.onclick=()=>{const k=b.dataset.fix;go(k.includes('student')||k.includes('section')?2:k.includes('teacher')?3:k.includes('subject')?1:4,false)})}
function reviewCard(icon,title,step,body){return `<div class="col-lg-6"><div class="spc-review"><div class="spc-review-head"><span><i class="ti ti-${icon} me-1"></i>${title}</span><button class="btn btn-sm btn-outline-primary" data-edit="${step}"><i class="ti ti-edit"></i> Edit</button></div><div class="spc-review-body">${body}</div></div></div>`}
function renderReview(){const sub=selectedSubject(),t=selectedTeacher(),r=selectedRoom(),sec=selectedSection(),b=selectedBlock(),students=S.data.students.filter(s=>S.studentKeys.includes(s.key));$('spcReviewGrid').innerHTML=reviewCard('file-description','Class Details',1,`<dl class="spc-dl"><dt>Type</dt><dd>${esc(value('spcType'))}</dd><dt>Title</dt><dd>${esc(value('spcTitle'))}</dd><dt>Subject</dt><dd>${esc(sub?.code)} — ${esc(sub?.name)}</dd><dt>Term</dt><dd>${esc(value('spcAcademicYear'))} · ${esc(value('spcSemester'))}</dd><dt>Program</dt><dd>${esc(value('spcProgram'))}</dd></dl>`)+reviewCard('users','Students / Section',2,`<dl class="spc-dl"><dt>Mode</dt><dd>${esc(S.mode)}</dd><dt>Participants</dt><dd>${S.mode==='Section'?esc(sec?.code)+' · '+participantCount()+' students':students.map(s=>esc(s.name)).join(', ')}</dd></dl>`)+reviewCard('user-check','Faculty',3,`<dl class="spc-dl"><dt>Teacher</dt><dd>${esc(t?.full_name)}</dd><dt>Faculty ID</dt><dd>${esc(t?.employee_no||'—')}</dd><dt>Department</dt><dd>${esc(t?.department||'—')}</dd></dl>`)+reviewCard('calendar-time','Schedule & Room',4,`<dl class="spc-dl"><dt>Date</dt><dd>${esc(value('spcClassDate'))}</dd><dt>Time block</dt><dd>${esc(b?.code)} · ${esc(b?.label)}</dd><dt>Room</dt><dd>${esc(r?.room_code)} · ${esc(r?.room_type)}</dd><dt>Capacity</dt><dd>${r?.capacity} for ${participantCount()} participant(s)</dd></dl>`);$('spcReviewGrid').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>go(+b.dataset.edit,false))}
async function save(mode){const button=mode==='confirm'?$('spcConfirmSave'):$('spcSaveDraft');button.disabled=true;try{const p={...payload(),save_mode:mode};const j=await request(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});S.id=+j.record.id;S.saved=j.record;renderConfirmation();go(7,false);alertMsg(j.message,'success')}catch(e){alertMsg(e.message)}finally{button.disabled=false}}
function detailsDl(r){return `<div class="spc-review-head"><span><i class="ti ti-calendar-check me-1"></i>${esc(r.title)}</span><span class="spc-pill spc-status-${esc(r.status).replaceAll(' ','-')}">${esc(r.status)}</span></div><div class="spc-review-body"><dl class="spc-dl"><dt>Subject</dt><dd>${esc(r.subject_code)} — ${esc(r.subject_name)}</dd><dt>Participants</dt><dd>${r.assignment_mode==='Section'?esc(r.section_code)+' · '+esc(r.current_students)+' students':r.students.length+' selected student(s)'}</dd><dt>Faculty</dt><dd>${esc(r.teacher_name)} (${esc(r.employee_no||'—')})</dd><dt>Schedule</dt><dd>${esc(r.weekday)}, ${esc(r.class_date)} · ${esc(r.time_label)}</dd><dt>Room</dt><dd>${esc(r.room_code)} · ${esc(r.building||'—')} · Capacity ${esc(r.capacity)}</dd><dt>Remarks</dt><dd>${esc(r.remarks||'—')}</dd></dl></div>`}
function renderConfirmation(){const r=S.saved;$('spcConfirmationRef').innerHTML=`<i class="ti ti-hash"></i>${esc(r.reference_no||'Draft #'+r.id)}`;$('spcConfirmationDetails').innerHTML=detailsDl(r)}
async function loadList(){try{const qs=new URLSearchParams({action:'list',status:value('spcListStatus'),search:value('spcListSearch')});const j=await request(API+'?'+qs);renderList(j.records)}catch(e){alertMsg(e.message)}}
function renderList(rows){$('spcListRows').innerHTML=rows.length?rows.map(r=>{const participants=r.assignment_mode==='Section'?(r.section_code||'Section'):(r.student_count+' students');return `<tr><td><b>${esc(r.reference_no||'#'+r.id)}</b></td><td><b>${esc(r.title)}</b><small class="d-block text-muted">${esc(r.special_type)} · ${esc(r.subject_code||'—')}</small></td><td>${esc(r.weekday+', '+r.class_date)}<small class="d-block text-muted">${esc(r.time_label)}</small></td><td>${esc(r.teacher_name||'—')}<small class="d-block text-muted"><i class="ti ti-door me-1"></i>${esc(r.room_code||'—')}</small></td><td>${esc(participants)}</td><td><span class="spc-pill spc-status-${esc(r.status).replaceAll(' ','-')}">${esc(r.status)}</span></td><td class="text-end"><button class="btn btn-sm btn-outline-primary" data-view="${r.id}" title="View details"><i class="ti ti-eye"></i></button>${r.status==='Ready to Publish'?` <button class="btn btn-sm btn-success" data-publish="${r.id}" title="Publish"><i class="ti ti-speakerphone"></i></button>`:''}${!['Published','Cancelled'].includes(r.status)?` <button class="btn btn-sm btn-outline-danger" data-cancel="${r.id}" title="Cancel"><i class="ti ti-x"></i></button>`:''}</td></tr>`}).join(''):'<tr><td colspan="7" class="spc-empty"><i class="ti ti-calendar-off"></i>No special classes match the filter.</td></tr>';$('spcListRows').querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>viewDetails(+b.dataset.view));$('spcListRows').querySelectorAll('[data-publish]').forEach(b=>b.onclick=()=>changeStatus(+b.dataset.publish,'Published'));$('spcListRows').querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>changeStatus(+b.dataset.cancel,'Cancelled'))}
async function viewDetails(id){try{const j=await request(API+'?action=details&id='+id),r=j.record;const history=r.history.length?r.history.map(h=>`<li><b>${esc(h.action)}</b> · ${esc(h.actor_name)} · ${esc(h.created_at)}<br><span class="spc-muted">${esc(h.detail)}</span></li>`).join(''):'<li>No history entries.</li>';$('spcManageDetail').innerHTML=detailsDl(r)+`<div class="spc-card-body border-top"><h6><i class="ti ti-history me-1"></i>History</h6><ul class="small mb-0">${history}</ul></div>`;$('spcManageDetail').classList.remove('d-none');$('spcManageDetail').scrollIntoView({behavior:'smooth'})}catch(e){alertMsg(e.message)}}
async function changeStatus(id,status){if(status==='Published'&&!confirm('Publish this validated special class now? Availability and conflicts will be rechecked.'))return;if(status==='Cancelled'&&!confirm('Cancel this class? It will remain in audit history.'))return;try{const j=await request(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'update_status',id,status})});alertMsg(j.message,'success');await loadList();await viewDetails(id)}catch(e){alertMsg(e.message)}}
function reset(){S.id=0;S.mode='Section';S.studentKeys=[];S.teacherId=null;S.roomId=null;S.lastValidation=null;S.saved=null;['spcTitle','spcRemarks','spcClassDate','spcTeacherSearch','spcStudentSearch'].forEach(id=>$(id).value='');$('spcType').value='Remedial';['spcProgram','spcAcademicYear','spcSemester','spcSubject','spcSection','spcTimeBlock'].forEach(id=>$(id).value='');setMode('Section');renderSubjects();renderSections();renderStudents();renderTeachers();renderRooms();renderWeek();updateSchedulePreview();go(1,false)}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-next]').forEach(b=>b.onclick=()=>go(+b.dataset.next));document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>go(+b.dataset.back,false));document.querySelectorAll('[data-mode]').forEach(x=>x.onclick=()=>setMode(x.dataset.mode));['spcProgram','spcAcademicYear','spcSemester'].forEach(id=>$(id).onchange=()=>{renderSubjects();renderSections();renderWeek()});$('spcSubject').onchange=()=>{refreshStudents();renderTeachers()};$('spcSection').onchange=renderSectionInfo;$('spcStudentSearch').oninput=renderStudents;$('spcTeacherSearch').oninput=renderTeachers;$('spcTeacherDepartment').onchange=renderTeachers;$('spcClassDate').onchange=updateSchedulePreview;$('spcTimeBlock').onchange=updateSchedulePreview;$('spcRecheck').onclick=runValidation;$('spcToReview').onclick=()=>go(6,false);$('spcSaveDraft').onclick=()=>save('draft');$('spcConfirmSave').onclick=()=>save('confirm');$('spcPrint').onclick=()=>window.print();$('spcViewDetails').onclick=()=>{go(8,false);viewDetails(S.id)};$('spcCreateAnother').onclick=reset;$('spcBackList').onclick=()=>go(8,false);$('spcCreateFromList').onclick=reset;$('spcNewBtn').onclick=reset;$('spcListRefresh').onclick=loadList;$('spcListStatus').onchange=loadList;$('spcListSearch').oninput=()=>{clearTimeout(window.spcSearchTimer);window.spcSearchTimer=setTimeout(loadList,250)};load()});
})();
</script>

<?php require_once __DIR__ . '/../../../includes/layout-end.php'; ?>
