<?php
require_once __DIR__ . '/../../../config/config.php';
$pageTitle='Time Block Generator';$activeModule='scheduling';$activePage='time-block-generator';$hideModulePageBanner=true;
$breadcrumbs=[['label'=>'Class Scheduling','url'=>BASE_URL.'/modules/scheduling/index.php'],['label'=>'Time Block Generator','url'=>null]];
require_once __DIR__ . '/../../../includes/breadcrumbs.php';
require_once __DIR__ . '/../../../includes/layout-start.php';
?>
<?php renderBreadcrumbs($breadcrumbs); ?>

<link href="<?= BASE_URL ?>/assets/vendor/fontawesome/css/all.min.css" rel="stylesheet">

<style>
:root{--tb-navy:#082c5c;--tb-blue:#0768dc;--tb-sky:#eaf4ff;--tb-line:#d9e5f3;--tb-text:#17365d;--tb-muted:#6b7b8f;--tb-green:#158657;--tb-amber:#b86d08;--tb-red:#c83b43;--tb-purple:#6f42c1}
.tb-shell{color:var(--tb-text)}.tb-hero{background:linear-gradient(125deg,#072852,#0b5dac);border-radius:18px;padding:1.25rem 1.45rem;color:#fff;position:relative;overflow:hidden;box-shadow:0 14px 35px rgba(8,44,92,.15)}
.tb-hero:after{content:"";position:absolute;width:230px;height:230px;border-radius:50%;right:-70px;top:-110px;background:rgba(255,255,255,.09)}.tb-hero h1{font-size:clamp(1.45rem,2.5vw,2rem);font-weight:800;margin:0}.tb-hero p{margin:.25rem 0 0;color:#dcecff}.tb-hero-icon{width:54px;height:54px;border-radius:15px;display:grid;place-items:center;background:rgba(255,255,255,.14);font-size:1.55rem;flex:0 0 auto}
.tb-flow{display:grid;grid-template-columns:repeat(7,minmax(115px,1fr));gap:.55rem;margin:1rem 0}.tb-step{border:1px solid var(--tb-line);background:#fff;border-radius:13px;padding:.7rem .6rem;display:flex;gap:.55rem;align-items:center;color:#59708c;cursor:pointer;transition:.18s;min-height:64px;text-align:left}.tb-step:hover{border-color:#9cc6f3;transform:translateY(-1px)}.tb-step.active{background:linear-gradient(135deg,#0b67d4,#0a4da2);color:#fff;border-color:#0b5ec0;box-shadow:0 8px 18px rgba(11,103,212,.2)}.tb-step.done{border-color:#98d7ba;background:#f2fbf7;color:#176c4c}.tb-step-no{width:30px;height:30px;display:grid;place-items:center;border-radius:50%;background:#e8f0fa;color:#164b84;font-weight:800;flex:0 0 auto}.tb-step.active .tb-step-no{background:#fff;color:#0b5ec0}.tb-step.done .tb-step-no{background:#daf3e7;color:#13724d}.tb-step strong{font-size:.78rem;line-height:1.15;display:block}.tb-step small{font-size:.66rem;opacity:.78;display:block;margin-top:.15rem}
.tb-screen{display:none}.tb-screen.active{display:block;animation:tbIn .18s ease}@keyframes tbIn{from{opacity:.3;transform:translateY(5px)}to{opacity:1;transform:none}}
.tb-card{background:#fff;border:1px solid var(--tb-line);border-radius:15px;box-shadow:0 8px 24px rgba(21,55,91,.06);overflow:hidden}.tb-card-head{padding:.95rem 1.05rem;border-bottom:1px solid var(--tb-line);display:flex;justify-content:space-between;align-items:center;gap:.75rem}.tb-card-head h2,.tb-card-head h3{font-size:1rem;font-weight:800;margin:0}.tb-card-body{padding:1rem}.tb-title-icon{width:37px;height:37px;border-radius:10px;background:var(--tb-sky);color:var(--tb-blue);display:inline-grid;place-items:center;margin-right:.55rem}
.tb-stat-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:.75rem}.tb-stat{background:#fff;border:1px solid var(--tb-line);border-radius:14px;padding:.85rem;display:flex;align-items:center;gap:.7rem}.tb-stat i{width:40px;height:40px;border-radius:11px;display:grid;place-items:center;background:#eaf4ff;color:#0966ca}.tb-stat b{display:block;font-size:1.3rem;line-height:1}.tb-stat span{font-size:.73rem;color:var(--tb-muted)}.tb-stat.green i{background:#e6f6ef;color:var(--tb-green)}.tb-stat.gray i{background:#eff2f6;color:#637085}.tb-stat.purple i{background:#f1eafd;color:var(--tb-purple)}.tb-stat.amber i{background:#fff3df;color:var(--tb-amber)}
.tb-toolbar{display:flex;gap:.6rem;flex-wrap:wrap;align-items:center}.tb-toolbar .form-control,.tb-toolbar .form-select{min-width:155px}.tb-search{position:relative;min-width:230px;flex:1}.tb-search i{position:absolute;left:.8rem;top:50%;transform:translateY(-50%);color:#8293a8}.tb-search input{padding-left:2.25rem}.tb-table thead th{font-size:.72rem;text-transform:uppercase;letter-spacing:.035em;background:#f4f8fc;color:#52677f;border-bottom:1px solid var(--tb-line);white-space:nowrap}.tb-table td{font-size:.84rem;vertical-align:middle}.tb-code{font-weight:800;color:#0a4e9a}.tb-pill{display:inline-flex;align-items:center;gap:.3rem;border-radius:999px;padding:.25rem .55rem;font-size:.69rem;font-weight:700;white-space:nowrap}.tb-pill.active,.tb-pill.ready{background:#e3f6ec;color:#14774f}.tb-pill.inactive{background:#eef1f5;color:#647083}.tb-pill.regular{background:#e8f2ff;color:#0b5cad}.tb-pill.custom{background:#fff3df;color:#9b5d04}.tb-pill.exam-specific{background:#f0e9ff;color:#673ab7}.tb-pill.break{background:#fff0e9;color:#aa4c1e}.tb-pill.issue{background:#ffe7e9;color:#b42d39}
.tb-choice-grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.tb-choice{border:2px solid var(--tb-line);border-radius:16px;padding:1.15rem;background:#fff;cursor:pointer;transition:.18s}.tb-choice:hover{border-color:#74b2ef;box-shadow:0 9px 22px rgba(11,103,212,.1)}.tb-choice i{width:48px;height:48px;border-radius:13px;display:grid;place-items:center;background:var(--tb-sky);color:var(--tb-blue);font-size:1.25rem}.tb-choice h3{font-size:1rem;font-weight:800;margin:.8rem 0 .25rem}.tb-choice p{font-size:.82rem;color:var(--tb-muted);margin:0}
.tb-form-section{border:1px solid var(--tb-line);border-radius:13px;padding:1rem;height:100%}.tb-form-section h3{font-size:.9rem;font-weight:800;margin:0 0 .9rem;color:#123d70}.tb-form-section h3 i{color:var(--tb-blue);margin-right:.4rem}.form-label{font-size:.78rem;font-weight:700;color:#425b78}.tb-duration{background:#f2f7fc;border-radius:9px;padding:.65rem .75rem;font-weight:700;color:#174b82}.tb-validation{border-radius:13px;padding:.9rem;border:1px solid #b9e4cf;background:#effaf5}.tb-validation.error{border-color:#f0b7bd;background:#fff3f4}.tb-check{display:flex;gap:.55rem;align-items:flex-start;font-size:.8rem;margin:.42rem 0}.tb-check i{margin-top:.15rem;color:var(--tb-green)}.tb-validation.error .tb-check i{color:var(--tb-red)}
.tb-preview-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:.65rem}.tb-mini{border:1px solid var(--tb-line);border-radius:11px;padding:.75rem;background:#f8fbfe}.tb-mini small{display:block;color:var(--tb-muted);font-size:.69rem}.tb-mini strong{font-size:.88rem}.tb-confirm{max-width:730px;margin:0 auto;text-align:center;padding:1.6rem}.tb-checkmark{width:82px;height:82px;margin:0 auto 1rem;border-radius:50%;display:grid;place-items:center;background:#e1f6eb;color:var(--tb-green);font-size:2.4rem}.tb-ref{background:#eef6ff;border:1px solid #cfe4fa;border-radius:12px;padding:.8rem 1rem;display:inline-block;font-weight:800;color:#0b539e}.tb-connect{display:grid;grid-template-columns:repeat(3,1fr);gap:.9rem}.tb-connect-card{border:1px solid var(--tb-line);border-radius:14px;padding:1rem;background:#fff;display:flex;gap:.85rem}.tb-connect-card i{width:44px;height:44px;display:grid;place-items:center;border-radius:12px;background:var(--tb-sky);color:var(--tb-blue);font-size:1.1rem;flex:0 0 auto}.tb-connect-card h3{font-size:.9rem;font-weight:800;margin:0 0 .25rem}.tb-connect-card p{font-size:.76rem;color:var(--tb-muted);margin:0}.tb-arrow{color:#6aa9e8}.tb-empty{text-align:center;padding:2.2rem;color:var(--tb-muted)}.tb-action-row{display:flex;justify-content:space-between;gap:.75rem;flex-wrap:wrap;margin-top:1rem}.tb-note{border-left:4px solid var(--tb-blue);background:#eff7ff;border-radius:0 10px 10px 0;padding:.75rem .9rem;font-size:.8rem;color:#345775}.tb-set-row{border:1px solid var(--tb-line);border-radius:11px;padding:.75rem;display:flex;justify-content:space-between;gap:.75rem;align-items:center;margin-bottom:.55rem}.tb-history-item{border-left:3px solid #87b9ed;padding:.25rem 0 .25rem .75rem;margin:.7rem 0}.tb-history-item strong{font-size:.8rem}.tb-history-item p{font-size:.76rem;margin:.15rem 0;color:#566b82}.tb-history-item small{color:#8391a2;font-size:.68rem}
@media(max-width:1200px){.tb-flow{grid-template-columns:repeat(4,1fr)}.tb-stat-grid{grid-template-columns:repeat(3,1fr)}.tb-connect{grid-template-columns:repeat(2,1fr)}}
@media(max-width:767px){.tb-flow{display:flex;overflow:auto;padding-bottom:.3rem}.tb-step{min-width:155px}.tb-stat-grid{grid-template-columns:1fr 1fr}.tb-choice-grid,.tb-connect,.tb-preview-summary{grid-template-columns:1fr}.tb-hero{padding:1rem}.tb-card-body{padding:.8rem}.tb-toolbar>*{width:100%;min-width:0!important}.tb-stat:last-child{grid-column:1/-1}}
@media print{.sidebar,.top-header,.breadcrumb,.tb-flow,.no-print,.btn{display:none!important}.main-content{margin:0!important}.tb-screen{display:none!important}.tb-screen.active{display:block!important}.tb-card{box-shadow:none}.tb-shell{font-size:11px}}
</style>

<div class="tb-shell">
 <div class="tb-hero d-flex align-items-center gap-3">
  <div class="tb-hero-icon"><i class="fas fa-clock-rotate-left"></i></div><div class="flex-grow-1"><h1>Time Block Generator</h1><p>Create, validate, activate, and manage the approved periods used across scheduling.</p></div>
  <div class="d-none d-lg-flex align-items-center gap-2"><i class="fas fa-shield-check"></i><small>Standardized time.<br>Safer scheduling.</small></div>
 </div>
 <div id="tbAlert" class="alert mt-3 d-none" role="alert"><i id="tbAlertIcon" class="fas fa-circle-info me-2"></i><span id="tbAlertText"></span></div>

 <div class="tb-flow no-print" id="tbFlow">
  <button class="tb-step active" data-screen="dashboard"><span class="tb-step-no">1</span><span><strong>Dashboard</strong><small>Existing blocks</small></span></button>
  <button class="tb-step" data-screen="single"><span class="tb-step-no">2</span><span><strong>Create / Edit</strong><small>Single block</small></span></button>
  <button class="tb-step" data-screen="configure"><span class="tb-step-no">3</span><span><strong>Configure Set</strong><small>Generate many</small></span></button>
  <button class="tb-step" data-screen="preview"><span class="tb-step-no">4</span><span><strong>Preview</strong><small>Validate blocks</small></span></button>
  <button class="tb-step" data-screen="confirmation"><span class="tb-step-no">5</span><span><strong>Confirmation</strong><small>Saved result</small></span></button>
  <button class="tb-step" data-screen="manage"><span class="tb-step-no">6</span><span><strong>Manage</strong><small>Lifecycle</small></span></button>
  <button class="tb-step" data-screen="connected"><span class="tb-step-no">7</span><span><strong>Connected Use</strong><small>Other modules</small></span></button>
 </div>

 <!-- 1 Dashboard -->
 <section class="tb-screen active" data-screen-panel="dashboard">
  <div class="tb-stat-grid mb-3">
   <div class="tb-stat"><i class="fas fa-layer-group"></i><div><b id="statTotal">0</b><span>Total blocks</span></div></div>
   <div class="tb-stat green"><i class="fas fa-circle-check"></i><div><b id="statActive">0</b><span>Active</span></div></div>
   <div class="tb-stat gray"><i class="fas fa-circle-pause"></i><div><b id="statInactive">0</b><span>Inactive</span></div></div>
   <div class="tb-stat purple"><i class="fas fa-file-circle-check"></i><div><b id="statExam">0</b><span>Exam-specific</span></div></div>
   <div class="tb-stat amber"><i class="fas fa-link"></i><div><b id="statUsed">0</b><span>In use</span></div></div>
  </div>
  <div class="row g-3">
   <div class="col-xl-8"><div class="tb-card h-100"><div class="tb-card-head"><h2><span class="tb-title-icon"><i class="fas fa-table-list"></i></span>Approved Time Blocks</h2><div class="d-flex gap-2 no-print"><button class="btn btn-outline-primary btn-sm" id="dashExport"><i class="fas fa-file-arrow-down me-1"></i>Export</button><button class="btn btn-outline-secondary btn-sm" id="dashPrint"><i class="fas fa-print me-1"></i>Print</button></div></div><div class="tb-card-body">
    <div class="tb-toolbar mb-3"><div class="tb-search"><i class="fas fa-magnifying-glass"></i><input id="dashSearch" class="form-control" placeholder="Search code, label, or time..."></div><select id="dashType" class="form-select"><option value="">All types</option><option>Class</option><option>Break</option><option>Exam</option></select><select id="dashStatus" class="form-select"><option value="">All statuses</option><option value="1">Active</option><option value="0">Inactive</option></select></div>
    <div class="table-responsive"><table class="table tb-table mb-0"><thead><tr><th>Code</th><th>Time</th><th>Type</th><th>Duration</th><th>Status</th><th>Used</th><th class="text-end">Action</th></tr></thead><tbody id="dashBody"></tbody></table></div>
   </div></div></div>
   <div class="col-xl-4"><div class="tb-card mb-3"><div class="tb-card-head"><h2><span class="tb-title-icon"><i class="fas fa-wand-magic-sparkles"></i></span>Create Time Blocks</h2></div><div class="tb-card-body"><div class="tb-choice-grid" style="grid-template-columns:1fr">
    <button class="tb-choice text-start" data-go="single"><i class="fas fa-plus"></i><h3>Single Time Block</h3><p>Enter one start/end period, type, label, and status.</p></button>
    <button class="tb-choice text-start" data-go="configure"><i class="fas fa-gears"></i><h3>Generate a Block Set</h3><p>Create many periods from a configurable range, interval, and break.</p></button>
   </div></div></div><div class="tb-card"><div class="tb-card-head"><h2><span class="tb-title-icon"><i class="fas fa-clock-rotate-left"></i></span>Recent Sets</h2><button class="btn btn-link btn-sm p-0" id="openHistory">History</button></div><div class="tb-card-body" id="recentSets"></div></div></div>
  </div>
 </section>

 <!-- 2 Single -->
 <section class="tb-screen" data-screen-panel="single"><div class="tb-card"><div class="tb-card-head"><h2><span class="tb-title-icon"><i class="fas fa-pen-to-square"></i></span><span id="singleTitle">Create Single Time Block</span></h2><span class="tb-pill custom"><i class="fas fa-sliders"></i> Manual / Custom</span></div><div class="tb-card-body">
  <input type="hidden" id="editId"><div class="row g-3"><div class="col-lg-8"><div class="tb-form-section"><h3><i class="fas fa-clock"></i>Block Details</h3><div class="row g-3">
   <div class="col-md-4"><label class="form-label">Block Code *</label><input id="singleCode" class="form-control" maxlength="20" placeholder="CUSTOM-01"></div><div class="col-md-4"><label class="form-label">Block Type *</label><select id="singleType" class="form-select"><option value="Class">Regular / Custom Class</option><option value="Break">Break / Exclusion</option><option value="Exam">Exam-specific</option></select></div><div class="col-md-4"><label class="form-label">Label / Description</label><input id="singleLabel" class="form-control" maxlength="60" placeholder="Afternoon class"></div>
   <div class="col-md-4"><label class="form-label">Start Time *</label><input id="singleStart" type="time" class="form-control"></div><div class="col-md-4"><label class="form-label">End Time *</label><input id="singleEnd" type="time" class="form-control"></div><div class="col-md-4"><label class="form-label">Calculated Duration</label><div class="tb-duration" id="singleDuration"><i class="fas fa-hourglass-half me-2"></i>—</div></div>
   <div class="col-md-4"><label class="form-label">Operating From</label><input id="singleOpStart" type="time" value="06:00" class="form-control"></div><div class="col-md-4"><label class="form-label">Operating Until</label><input id="singleOpEnd" type="time" value="22:00" class="form-control"></div><div class="col-md-4 d-flex align-items-end"><div class="form-check form-switch mb-2"><input id="singleActive" class="form-check-input" type="checkbox" checked><label class="form-check-label" for="singleActive">Activate when saved</label></div></div>
  </div></div></div><div class="col-lg-4"><div class="tb-form-section"><h3><i class="fas fa-shield-halved"></i>Validation</h3><div id="singleValidation" class="tb-note"><i class="fas fa-circle-info me-1"></i>Enter the block details, then run validation before saving.</div><div class="mt-3 small text-muted"><strong>Checks performed</strong><ul class="ps-3 mt-2 mb-0"><li>Required fields and duration</li><li>Configured operating hours</li><li>Duplicate code</li><li>Active time overlap</li></ul></div></div></div></div>
  <div class="tb-action-row"><button class="btn btn-outline-secondary" data-go="dashboard"><i class="fas fa-arrow-left me-1"></i>Dashboard</button><div class="d-flex gap-2"><button class="btn btn-outline-primary" id="validateSingle"><i class="fas fa-shield-check me-1"></i>Validate</button><button class="btn btn-primary" id="saveSingle"><i class="fas fa-floppy-disk me-1"></i>Validate & Save</button></div></div>
 </div></div></section>

 <!-- 3 Configure -->
 <section class="tb-screen" data-screen-panel="configure"><div class="tb-card"><div class="tb-card-head"><h2><span class="tb-title-icon"><i class="fas fa-gears"></i></span>Configure Time Block Set</h2><span class="tb-pill regular"><i class="fas fa-wand-magic-sparkles"></i>Automatic generation</span></div><div class="tb-card-body"><div class="row g-3">
  <div class="col-lg-7"><div class="tb-form-section"><h3><i class="fas fa-calendar-day"></i>Schedule Range</h3><div class="row g-3"><div class="col-md-6"><label class="form-label">Set Name *</label><input id="setName" class="form-control" maxlength="100" placeholder="Regular 90-minute blocks"></div><div class="col-md-6"><label class="form-label">Block Type *</label><select id="setType" class="form-select"><option value="Class">Regular Class</option><option value="Exam">Exam-specific</option></select></div><div class="col-md-4"><label class="form-label">Start Time *</label><input id="setStart" type="time" class="form-control" value="07:00"></div><div class="col-md-4"><label class="form-label">End Time *</label><input id="setEnd" type="time" class="form-control" value="20:00"></div><div class="col-md-4"><label class="form-label">Interval *</label><select id="setInterval" class="form-select"><option value="30">30 minutes</option><option value="45">45 minutes</option><option value="60">60 minutes</option><option value="90" selected>90 minutes</option><option value="120">120 minutes</option><option value="180">180 minutes</option></select></div></div></div></div>
  <div class="col-lg-5"><div class="tb-form-section"><h3><i class="fas fa-mug-hot"></i>Break / Exclusion</h3><div class="form-check form-switch mb-3"><input id="includeBreak" class="form-check-input" type="checkbox" checked><label for="includeBreak" class="form-check-label">Include a break in this set</label></div><div class="row g-3" id="breakFields"><div class="col-6"><label class="form-label">Break Start</label><input id="breakStart" type="time" class="form-control" value="11:30"></div><div class="col-6"><label class="form-label">Break End</label><input id="breakEnd" type="time" class="form-control" value="12:30"></div><div class="col-12"><label class="form-label">Break Label</label><input id="breakLabel" class="form-control" value="Lunch Break" maxlength="60"></div></div><hr><div class="form-check form-switch"><input id="setActivate" class="form-check-input" type="checkbox" checked><label class="form-check-label" for="setActivate">Activate all after saving</label></div></div></div>
 </div><div class="tb-note mt-3"><i class="fas fa-lightbulb me-2"></i>The range, interval, and break are configurable. The preview will identify partial blocks, duplicates, and overlaps before anything is saved.</div><div class="tb-action-row"><button class="btn btn-outline-secondary" data-go="dashboard"><i class="fas fa-arrow-left me-1"></i>Dashboard</button><button class="btn btn-primary" id="generatePreview"><i class="fas fa-wand-magic-sparkles me-1"></i>Generate & Validate Preview</button></div></div></div></section>

 <!-- 4 Preview -->
 <section class="tb-screen" data-screen-panel="preview"><div class="tb-card"><div class="tb-card-head"><h2><span class="tb-title-icon"><i class="fas fa-eye"></i></span>Preview Generated Blocks</h2><span id="previewBadge" class="tb-pill inactive"><i class="fas fa-hourglass"></i>Waiting for preview</span></div><div class="tb-card-body"><div class="tb-preview-summary mb-3"><div class="tb-mini"><small>Set</small><strong id="previewName">—</strong></div><div class="tb-mini"><small>Range</small><strong id="previewRange">—</strong></div><div class="tb-mini"><small>Interval</small><strong id="previewInterval">—</strong></div><div class="tb-mini"><small>Proposed Blocks</small><strong id="previewCount">0</strong></div></div><div id="previewIssues" class="mb-3"></div><div class="table-responsive"><table class="table tb-table mb-0"><thead><tr><th>#</th><th>Code</th><th>Start</th><th>End</th><th>Duration</th><th>Type</th><th>Validation</th></tr></thead><tbody id="previewBody"><tr><td colspan="7" class="tb-empty">Configure a set and generate a preview first.</td></tr></tbody></table></div><div class="tb-action-row"><button class="btn btn-outline-secondary" data-go="configure"><i class="fas fa-arrow-left me-1"></i>Adjust Settings</button><button class="btn btn-success" id="saveSet" disabled><i class="fas fa-floppy-disk me-1"></i>Save All Validated Blocks</button></div></div></div></section>

 <!-- 5 Confirmation -->
 <section class="tb-screen" data-screen-panel="confirmation"><div class="tb-card"><div class="tb-confirm"><div class="tb-checkmark"><i class="fas fa-check"></i></div><h2 class="fw-bold">Time Blocks Created Successfully!</h2><p class="text-muted">The validated periods were saved and are ready for connected scheduling modules.</p><div class="tb-ref my-3" id="confirmRef">No generated set yet</div><div class="tb-preview-summary text-start my-3"><div class="tb-mini"><small>Set Name</small><strong id="confirmName">—</strong></div><div class="tb-mini"><small>Blocks Created</small><strong id="confirmCount">0</strong></div><div class="tb-mini"><small>Status</small><strong id="confirmStatus">—</strong></div><div class="tb-mini"><small>Validation</small><strong class="text-success"><i class="fas fa-circle-check me-1"></i>Passed</strong></div></div><div class="d-flex gap-2 justify-content-center flex-wrap"><button class="btn btn-primary" data-go="manage"><i class="fas fa-table-list me-1"></i>View Time Blocks</button><button class="btn btn-outline-primary" data-go="configure"><i class="fas fa-plus me-1"></i>Create Another Set</button><button class="btn btn-outline-secondary" data-go="connected"><i class="fas fa-share-nodes me-1"></i>Connected Modules</button></div></div></div></section>

 <!-- 6 Manage -->
 <section class="tb-screen" data-screen-panel="manage"><div class="tb-card"><div class="tb-card-head"><h2><span class="tb-title-icon"><i class="fas fa-list-check"></i></span>View / Manage Time Blocks</h2><div class="d-flex gap-2 no-print"><button class="btn btn-outline-primary btn-sm" id="manageExport"><i class="fas fa-download me-1"></i>Export</button><button class="btn btn-outline-secondary btn-sm" id="manageHistory"><i class="fas fa-clock-rotate-left me-1"></i>History</button><button class="btn btn-primary btn-sm" data-go="single"><i class="fas fa-plus me-1"></i>Create Block</button></div></div><div class="tb-card-body"><div class="tb-note mb-3"><i class="fas fa-shield-halved me-2"></i>Blocks already used by schedules cannot be deleted. Deactivation keeps references and audit history intact; activation runs overlap checks again.</div><div class="tb-toolbar mb-3"><div class="tb-search"><i class="fas fa-magnifying-glass"></i><input id="manageSearch" class="form-control" placeholder="Search blocks..."></div><select id="manageCategory" class="form-select"><option value="">All categories</option><option>Regular</option><option>Custom</option><option>Exam-specific</option><option>Break</option></select><select id="manageStatus" class="form-select"><option value="">All statuses</option><option value="1">Active</option><option value="0">Inactive</option></select></div><div class="table-responsive"><table class="table tb-table mb-0"><thead><tr><th>#</th><th>Code / Label</th><th>Period</th><th>Category</th><th>Set</th><th>Status</th><th>Usage</th><th class="text-end">Actions</th></tr></thead><tbody id="manageBody"></tbody></table></div><div class="tb-action-row"><button class="btn btn-outline-secondary" data-go="dashboard"><i class="fas fa-arrow-left me-1"></i>Dashboard</button><button class="btn btn-outline-primary" data-go="connected"><i class="fas fa-arrow-right me-1"></i>How Blocks Are Used</button></div></div></div></section>

 <!-- 7 Connected -->
 <section class="tb-screen" data-screen-panel="connected"><div class="tb-card"><div class="tb-card-head"><h2><span class="tb-title-icon"><i class="fas fa-share-nodes"></i></span>Approved Blocks in Other Modules</h2><span class="tb-pill ready"><i class="fas fa-circle-check"></i>Shared scheduling data</span></div><div class="tb-card-body"><div class="tb-note mb-3"><i class="fas fa-database me-2"></i>This subsystem defines valid periods only. Teachers, rooms, sections, and classes are assigned by their own connected modules using the same records.</div><div class="tb-connect" id="consumerGrid"></div><div class="d-flex align-items-center justify-content-center gap-3 flex-wrap my-4 text-center"><span class="tb-pill regular fs-6"><i class="fas fa-clock"></i>Approved Time Blocks</span><i class="fas fa-arrow-right tb-arrow"></i><span class="tb-pill ready fs-6"><i class="fas fa-shield-halved"></i>Conflict Validation</span><i class="fas fa-arrow-right tb-arrow"></i><span class="tb-pill exam-specific fs-6"><i class="fas fa-calendar-check"></i>Published Schedule</span></div><div class="tb-action-row"><button class="btn btn-outline-secondary" data-go="manage"><i class="fas fa-arrow-left me-1"></i>Manage Blocks</button><a class="btn btn-primary" href="<?= BASE_URL ?>/modules/scheduling/pages/teacher-schedule-mapping.php"><i class="fas fa-chalkboard-user me-1"></i>Open Teacher Mapping</a></div></div></div></section>
</div>

<div class="modal fade" id="tbHistoryModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"><i class="fas fa-clock-rotate-left text-primary me-2"></i>Time Block History</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body" id="historyBody"></div><div class="modal-footer"><button class="btn btn-secondary" data-bs-dismiss="modal">Close</button></div></div></div></div>

<script>
(()=>{'use strict';const BASE='<?= BASE_URL ?>',API=BASE+'/api/scheduling/time-blocks.php';let state={blocks:[],summary:{},sets:[],history:[],consumers:[],preview:null,previewPayload:null,lastSet:null};const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const routes={section:BASE+'/modules/scheduling/pages/section-assignment-tool.php',teacher:BASE+'/modules/scheduling/pages/teacher-schedule-mapping.php',room:BASE+'/modules/scheduling/pages/room-availability-checker.php',special:BASE+'/modules/scheduling/pages/special-class-scheduler.php',exam:BASE+'/modules/scheduling/pages/exam-timetable-generator.php',conflict:BASE+'/modules/scheduling/pages/conflict-checker.php'};
function alertMsg(msg,kind='info'){const b=$('tbAlert');b.className='alert mt-3 alert-'+kind;$('tbAlertIcon').className='fas '+(kind==='success'?'fa-circle-check':kind==='danger'?'fa-triangle-exclamation':'fa-circle-info')+' me-2';$('tbAlertText').textContent=msg;b.classList.remove('d-none');window.scrollTo({top:0,behavior:'smooth'});}function hideAlert(){$('tbAlert').classList.add('d-none');}
async function req(body=null){const res=await fetch(body?API:API+'?action=dashboard',{method:body?'POST':'GET',credentials:'same-origin',headers:{Accept:'application/json','Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await res.json().catch(()=>({ok:false,error:'The server returned an unreadable response.'}));if(!res.ok||!data.ok)throw new Error(data.error||'Request failed.');return data;}
function go(name){document.querySelectorAll('.tb-screen').forEach(x=>x.classList.toggle('active',x.dataset.screenPanel===name));document.querySelectorAll('.tb-step').forEach((x,i)=>{x.classList.toggle('active',x.dataset.screen===name);x.classList.toggle('done',i<[...document.querySelectorAll('.tb-step')].findIndex(s=>s.dataset.screen===name));});if(name==='manage')renderManage();if(name==='connected')renderConsumers();hideAlert();window.scrollTo({top:0,behavior:'smooth'});}
function fmtTime(t){if(!t)return'—';const [h,m]=t.slice(0,5).split(':').map(Number),p=h>=12?'PM':'AM';return `${h%12||12}:${String(m).padStart(2,'0')} ${p}`;}function duration(n){if(!n)return'—';return n%60?`${Math.floor(n/60)?Math.floor(n/60)+' hr ':''}${n%60} min`:`${n/60} hr`;}
function statusPill(b){return `<span class="tb-pill ${Number(b.is_active)===1?'active':'inactive'}"><i class="fas ${Number(b.is_active)===1?'fa-circle-check':'fa-circle-pause'}"></i>${Number(b.is_active)===1?'Active':'Inactive'}</span>`;}function catPill(c){return `<span class="tb-pill ${String(c).toLowerCase().replace(/ /g,'-')}">${esc(c)}</span>`;}
function filtered(search,type,status,category){const q=(search||'').toLowerCase();return state.blocks.filter(b=>(!q||[b.code,b.label,b.start_time,b.end_time,b.set_name].join(' ').toLowerCase().includes(q))&&(!type||b.block_type===type)&&(!status||String(b.is_active)===status)&&(!category||b.category===category));}
function actionButtons(b,full=false){return `<div class="d-inline-flex gap-1"><button class="btn btn-sm btn-outline-primary" data-edit="${b.id}" title="Edit"><i class="fas fa-pen"></i>${full?' Edit':''}</button><button class="btn btn-sm btn-outline-${Number(b.is_active)===1?'warning':'success'}" data-toggle="${b.id}" title="${Number(b.is_active)===1?'Deactivate':'Activate'}"><i class="fas fa-${Number(b.is_active)===1?'pause':'play'}"></i></button><button class="btn btn-sm btn-outline-danger" data-delete="${b.id}" ${Number(b.usage_count)>0?'disabled title="Referenced by schedules"':'title="Delete unused block"'}><i class="fas fa-trash-can"></i></button></div>`;}
function renderDashboard(){const s=state.summary;$('statTotal').textContent=s.total||0;$('statActive').textContent=s.active||0;$('statInactive').textContent=s.inactive||0;$('statExam').textContent=s.exam||0;$('statUsed').textContent=s.in_use||0;const rows=filtered($('dashSearch').value,$('dashType').value,$('dashStatus').value,'');$('dashBody').innerHTML=rows.length?rows.slice(0,8).map(b=>`<tr><td><span class="tb-code">${esc(b.code)}</span><div class="text-muted small">${esc(b.label)}</div></td><td>${fmtTime(b.start_time)} – ${fmtTime(b.end_time)}</td><td>${catPill(b.category)}</td><td>${duration(Number(b.duration_minutes))}</td><td>${statusPill(b)}</td><td>${Number(b.usage_count)||'—'}</td><td class="text-end">${actionButtons(b)}</td></tr>`).join(''):`<tr><td colspan="7" class="tb-empty"><i class="fas fa-clock fa-2x d-block mb-2"></i>No blocks match the filters.</td></tr>`;$('recentSets').innerHTML=state.sets.length?state.sets.slice(0,4).map(s=>`<div class="tb-set-row"><div><strong>${esc(s.name)}</strong><div class="small text-muted">${esc(s.reference_no)} · ${s.block_count} blocks</div></div><span class="tb-pill ${s.status==='Active'?'active':'inactive'}">${esc(s.status)}</span></div>`).join(''):'<div class="text-muted small">No generated sets yet.</div>';bindRowActions($('dashBody'));}
function renderManage(){const rows=filtered($('manageSearch').value,'',$('manageStatus').value,$('manageCategory').value);$('manageBody').innerHTML=rows.length?rows.map((b,i)=>`<tr><td>${i+1}</td><td><span class="tb-code">${esc(b.code)}</span><div class="text-muted small">${esc(b.label)}</div></td><td>${fmtTime(b.start_time)} – ${fmtTime(b.end_time)}<div class="small text-muted">${duration(Number(b.duration_minutes))}</div></td><td>${catPill(b.category)}</td><td>${b.set_reference?`<strong>${esc(b.set_reference)}</strong><div class="small text-muted">${esc(b.set_name)}</div>`:'<span class="text-muted">Manual</span>'}</td><td>${statusPill(b)}</td><td><span class="tb-pill ${Number(b.usage_count)>0?'regular':'inactive'}"><i class="fas fa-link"></i>${Number(b.usage_count)}</span></td><td class="text-end">${actionButtons(b,true)}</td></tr>`).join(''):`<tr><td colspan="8" class="tb-empty">No blocks match the filters.</td></tr>`;bindRowActions($('manageBody'));}
function renderConsumers(){$('consumerGrid').innerHTML=state.consumers.map(c=>`<a href="${routes[c.key]||'#'}" class="tb-connect-card text-decoration-none text-reset"><i class="fas ${esc(c.icon)}"></i><div><h3>${esc(c.name)} <i class="fas fa-arrow-up-right-from-square ms-1 small text-primary"></i></h3><p>${esc(c.use)}</p></div></a>`).join('');}
function renderHistory(){$('historyBody').innerHTML=state.history.length?state.history.map(h=>`<div class="tb-history-item"><strong><i class="fas fa-circle-dot text-primary me-1"></i>${esc(h.action)} ${h.block_code?'· '+esc(h.block_code):h.set_reference?'· '+esc(h.set_reference):''}</strong><p>${esc(h.detail)}</p><small>${esc(h.changed_by_name)} · ${new Date(String(h.created_at).replace(' ','T')).toLocaleString()}</small></div>`).join(''):'<div class="tb-empty">No history yet.</div>';bootstrap.Modal.getOrCreateInstance($('tbHistoryModal')).show();}
async function load(show=false){try{const d=await req();state={...state,...d};renderDashboard();renderManage();renderConsumers();if(show)alertMsg('Time block data refreshed.','success');}catch(e){alertMsg(e.message,'danger');}}
function singlePayload(action){const id=Number($('editId').value)||undefined;return{action,id,code:$('singleCode').value.trim(),label:$('singleLabel').value.trim(),start_time:$('singleStart').value,end_time:$('singleEnd').value,block_type:$('singleType').value,is_active:$('singleActive').checked?1:0,operating_start:$('singleOpStart').value,operating_end:$('singleOpEnd').value};}
function updateDuration(){const s=$('singleStart').value,e=$('singleEnd').value;if(!s||!e){$('singleDuration').innerHTML='<i class="fas fa-hourglass-half me-2"></i>—';return;}const [sh,sm]=s.split(':').map(Number),[eh,em]=e.split(':').map(Number),n=eh*60+em-sh*60-sm;$('singleDuration').innerHTML=`<i class="fas fa-hourglass-half me-2"></i>${n>0?duration(n):'Invalid range'}`;}
function resetSingle(){['editId','singleCode','singleLabel','singleStart','singleEnd'].forEach(id=>$(id).value='');$('singleType').value='Class';$('singleActive').checked=true;$('singleOpStart').value='06:00';$('singleOpEnd').value='22:00';$('singleTitle').textContent='Create Single Time Block';$('singleValidation').className='tb-note';$('singleValidation').innerHTML='<i class="fas fa-circle-info me-1"></i>Enter the block details, then run validation before saving.';updateDuration();}
async function validateSingle(){try{const d=await req(singlePayload('validate_single'));$('singleValidation').className='tb-validation';$('singleValidation').innerHTML=`<strong><i class="fas fa-circle-check me-1"></i>All checks passed</strong>${d.checks.map(x=>`<div class="tb-check"><i class="fas fa-check"></i><span>${esc(x)}</span></div>`).join('')}`;return true;}catch(e){$('singleValidation').className='tb-validation error';$('singleValidation').innerHTML=`<strong><i class="fas fa-triangle-exclamation me-1"></i>Validation failed</strong><div class="tb-check"><i class="fas fa-xmark"></i><span>${esc(e.message)}</span></div>`;return false;}}
async function saveSingle(){const ok=await validateSingle();if(!ok)return;const body=singlePayload($('editId').value?'update':'create');try{const d=await req(body);resetSingle();await load();go('manage');alertMsg(d.message,'success');}catch(e){alertMsg(e.message,'danger');}}
function setPayload(action){return{action,set_name:$('setName').value.trim(),block_type:$('setType').value,start_time:$('setStart').value,end_time:$('setEnd').value,interval_minutes:Number($('setInterval').value),include_break:$('includeBreak').checked?1:0,break_start:$('breakStart').value,break_end:$('breakEnd').value,break_label:$('breakLabel').value.trim(),activate:$('setActivate').checked?1:0};}
function renderPreview(){const p=state.preview,c=p.config;$('previewName').textContent=c.set_name;$('previewRange').textContent=fmtTime(c.start_time)+' – '+fmtTime(c.end_time);$('previewInterval').textContent=duration(c.interval_minutes);$('previewCount').textContent=p.blocks.length;$('previewBadge').className='tb-pill '+(p.valid?'ready':'issue');$('previewBadge').innerHTML=`<i class="fas ${p.valid?'fa-circle-check':'fa-triangle-exclamation'}"></i>${p.valid?'Validation passed':'Adjustment required'}`;$('previewIssues').innerHTML=(p.errors.length?`<div class="alert alert-danger mb-2"><strong><i class="fas fa-triangle-exclamation me-1"></i>Cannot save yet</strong><ul class="mb-0 mt-1">${p.errors.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:'')+(p.warnings.length?`<div class="alert alert-warning mb-2"><strong><i class="fas fa-circle-info me-1"></i>Review note</strong><ul class="mb-0 mt-1">${p.warnings.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:'');$('previewBody').innerHTML=p.blocks.length?p.blocks.map((b,i)=>`<tr><td>${i+1}</td><td class="tb-code">${esc(b.code)}</td><td>${fmtTime(b.start_time)}</td><td>${fmtTime(b.end_time)}</td><td>${duration(b.duration_minutes)}</td><td>${catPill(b.block_type==='Exam'?'Exam-specific':b.block_type)}</td><td><span class="tb-pill ${b.status==='Ready'?'ready':'issue'}"><i class="fas ${b.status==='Ready'?'fa-check':'fa-xmark'}"></i>${esc(b.status)}</span>${b.issues.length?`<div class="small text-danger mt-1">${esc(b.issues.join(' '))}</div>`:''}</td></tr>`).join(''):'<tr><td colspan="7" class="tb-empty">No blocks generated.</td></tr>';$('saveSet').disabled=!p.valid;}
async function generate(){try{const payload=setPayload('preview_set'),d=await req(payload);state.preview=d.preview;state.previewPayload=payload;renderPreview();go('preview');}catch(e){alertMsg(e.message,'danger');}}
async function saveSet(){if(!state.preview||!state.preview.valid)return;const btn=$('saveSet'),old=btn.innerHTML;btn.disabled=true;btn.innerHTML='<i class="fas fa-spinner fa-spin me-1"></i>Rechecking & Saving...';try{const d=await req({...state.previewPayload,action:'save_set'});state.lastSet=d.set;$('confirmRef').textContent=d.set.reference_no;$('confirmName').textContent=d.set.name;$('confirmCount').textContent=d.set.block_count;$('confirmStatus').textContent=d.set.status;await load();go('confirmation');}catch(e){alertMsg(e.message,'danger');}finally{btn.disabled=false;btn.innerHTML=old;}}
function editBlock(id){const b=state.blocks.find(x=>Number(x.id)===Number(id));if(!b)return;$('editId').value=b.id;$('singleCode').value=b.code;$('singleLabel').value=b.label;$('singleStart').value=b.start_time.slice(0,5);$('singleEnd').value=b.end_time.slice(0,5);$('singleType').value=b.block_type;$('singleActive').checked=Number(b.is_active)===1;$('singleTitle').textContent='Edit Time Block · '+b.code;$('singleValidation').className='tb-note';$('singleValidation').innerHTML='<i class="fas fa-circle-info me-1"></i>Run validation after making changes.';updateDuration();go('single');}
async function toggleBlock(id){const b=state.blocks.find(x=>Number(x.id)===Number(id));if(!b)return;const verb=Number(b.is_active)===1?'deactivate':'activate';if(!confirm(`Are you sure you want to ${verb} ${b.code}?${Number(b.usage_count)>0?' It is referenced by '+b.usage_count+' schedule record(s).':''}`))return;try{const d=await req({action:'toggle',id:Number(id)});alertMsg(d.message,'success');await load();}catch(e){alertMsg(e.message,'danger');}}
async function deleteBlock(id){const b=state.blocks.find(x=>Number(x.id)===Number(id));if(!b||!confirm(`Delete unused block ${b.code}? This removes the block but retains its audit event.`))return;try{const d=await req({action:'delete',id:Number(id)});alertMsg(d.message,'success');await load();}catch(e){alertMsg(e.message,'danger');}}
function bindRowActions(root){root.querySelectorAll('[data-edit]').forEach(x=>x.onclick=()=>editBlock(x.dataset.edit));root.querySelectorAll('[data-toggle]').forEach(x=>x.onclick=()=>toggleBlock(x.dataset.toggle));root.querySelectorAll('[data-delete]').forEach(x=>x.onclick=()=>deleteBlock(x.dataset.delete));}
function exportCsv(){const rows=[['Code','Label','Start','End','Duration Minutes','Type','Category','Status','Usage','Set'],...state.blocks.map(b=>[b.code,b.label,b.start_time,b.end_time,b.duration_minutes,b.block_type,b.category,Number(b.is_active)===1?'Active':'Inactive',b.usage_count,b.set_reference||'Manual'])];const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='time-blocks-'+new Date().toISOString().slice(0,10)+'.csv';a.click();URL.revokeObjectURL(a.href);}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-go]').forEach(x=>x.addEventListener('click',()=>go(x.dataset.go)));document.querySelectorAll('.tb-step').forEach(x=>x.addEventListener('click',()=>go(x.dataset.screen)));['dashSearch','dashType','dashStatus'].forEach(id=>$(id).addEventListener('input',renderDashboard));['manageSearch','manageCategory','manageStatus'].forEach(id=>$(id).addEventListener('input',renderManage));['singleStart','singleEnd'].forEach(id=>$(id).addEventListener('input',updateDuration));$('includeBreak').addEventListener('change',()=>{$('breakFields').classList.toggle('opacity-50',!$('includeBreak').checked);$('breakFields').querySelectorAll('input').forEach(x=>x.disabled=!$('includeBreak').checked);});$('validateSingle').onclick=validateSingle;$('saveSingle').onclick=saveSingle;$('generatePreview').onclick=generate;$('saveSet').onclick=saveSet;$('openHistory').onclick=renderHistory;$('manageHistory').onclick=renderHistory;$('dashExport').onclick=exportCsv;$('manageExport').onclick=exportCsv;$('dashPrint').onclick=()=>window.print();load();});
})();
</script>
<?php require_once __DIR__ . '/../../../includes/layout-end.php'; ?>
