<?php
declare(strict_types=1);

/** Calendar Integration API: published schedule distribution only. */
require_once __DIR__ . '/../../config/config.php';
require_once ROOT_PATH . '/config/database.php';
require_once ROOT_PATH . '/includes/authentication.php';
require_once ROOT_PATH . '/includes/audit.php';
require_once ROOT_PATH . '/includes/crypto.php';

header('Content-Type: application/json; charset=utf-8');
if (function_exists('isAuthenticated') && !isAuthenticated()) {
    http_response_code(401); echo json_encode(['ok'=>false,'error'=>'Authentication required.']); exit;
}
if (function_exists('userCanAccessModule') && !userCanAccessModule('scheduling')) {
    http_response_code(403); echo json_encode(['ok'=>false,'error'=>'You do not have permission to access Class Scheduling.']); exit;
}

function calOut(array $data, int $status=200): never { http_response_code($status); echo json_encode($data, JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE); exit; }
function calBody(): array { $raw=file_get_contents('php://input'); if($raw===false||trim($raw)==='') return $_POST?:[]; $d=json_decode($raw,true); return is_array($d)?$d:[]; }
function calUserId(): ?int { if(function_exists('getCurrentUserId')){$id=getCurrentUserId();return $id?(int)$id:null;} return !empty($_SESSION['user_id'])?(int)$_SESSION['user_id']:null; }
function calJson(?string $value, array $fallback=[]): array { $d=$value!==null?json_decode($value,true):null; return is_array($d)?$d:$fallback; }
function calDate(string $value, string $label): string { $d=DateTimeImmutable::createFromFormat('!Y-m-d',$value); if(!$d||$d->format('Y-m-d')!==$value) throw new InvalidArgumentException("Select a valid {$label}."); return $value; }
function calEnv(array $names): string { foreach($names as $n){$v=getenv($n);if(is_string($v)&&trim($v)!=='')return trim($v);} return ''; }
function calGoogleConfig(): array {
    $client=calEnv(['SMS2_GOOGLE_CALENDAR_CLIENT_ID','GOOGLE_CALENDAR_CLIENT_ID']);
    $secret=calEnv(['SMS2_GOOGLE_CALENDAR_CLIENT_SECRET','GOOGLE_CALENDAR_CLIENT_SECRET']);
    $redirect=calEnv(['SMS2_GOOGLE_CALENDAR_REDIRECT_URI','GOOGLE_CALENDAR_REDIRECT_URI']);
    if($redirect===''){$scheme=(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https':'http';$host=(string)($_SERVER['HTTP_HOST']??'localhost');$base=preg_match('#^https?://#i',BASE_URL)?BASE_URL:$scheme.'://'.$host.'/'.ltrim(BASE_URL,'/');$redirect=rtrim($base,'/').'/api/scheduling/calendar.php?action=google_callback';}
    return ['client_id'=>$client,'client_secret'=>$secret,'redirect_uri'=>$redirect,'configured'=>$client!==''&&$secret!==''];
}
function calHistory(PDO $pdo,int $id,string $action,?string $from,?string $to,string $detail,array $meta=[]):void{
    $st=$pdo->prepare('INSERT INTO calendar_integration_history(integration_id,action,from_status,to_status,detail,metadata_json,changed_by) VALUES(?,?,?,?,?,?,?)');
    $st->execute([$id,$action,$from,$to,substr($detail,0,500),$meta?json_encode($meta,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE):null,calUserId()]);
}
function calScheduleCatalog(PDO $pdo):array{
    $out=[];
    $rows=$pdo->query("SELECT academic_year,semester,COUNT(*) event_count,COUNT(DISTINCT section_id) section_count,MIN(updated_at) first_updated,MAX(updated_at) last_updated FROM schedule_entries WHERE status='Published' AND academic_year IS NOT NULL AND semester IS NOT NULL GROUP BY academic_year,semester ORDER BY academic_year DESC,semester")->fetchAll();
    foreach($rows as $r){$key='regular:'.rawurlencode($r['academic_year']).':'.rawurlencode($r['semester']);$out[]=['key'=>$key,'type'=>'Regular','title'=>'Published Class Schedule','academic_year'=>$r['academic_year'],'semester'=>$r['semester'],'date_from'=>date('Y-m-d'),'date_to'=>date('Y-m-d',strtotime('+120 days')),'entry_count'=>(int)$r['event_count'],'scope'=>(int)$r['section_count'].' section(s)','status'=>'Published'];}
    $rows=$pdo->query("SELECT academic_year,semester,COUNT(*) event_count,MIN(class_date) date_from,MAX(class_date) date_to FROM special_classes WHERE status='Published' GROUP BY academic_year,semester ORDER BY academic_year DESC,semester")->fetchAll();
    foreach($rows as $r){$out[]=['key'=>'special:'.rawurlencode((string)$r['academic_year']).':'.rawurlencode((string)$r['semester']),'type'=>'Special','title'=>'Published Special Classes','academic_year'=>$r['academic_year'],'semester'=>$r['semester'],'date_from'=>$r['date_from'],'date_to'=>$r['date_to'],'entry_count'=>(int)$r['event_count'],'scope'=>'Special class schedule','status'=>'Published'];}
    $rows=$pdo->query("SELECT b.id,b.title,b.exam_type,b.academic_year,b.semester,b.date_from,b.date_to,COUNT(e.id) event_count FROM exam_timetable_batches b JOIN exam_schedules e ON e.batch_id=b.id AND e.status='Published' WHERE b.status='Published' GROUP BY b.id ORDER BY b.date_from DESC,b.id DESC")->fetchAll();
    foreach($rows as $r){$out[]=['key'=>'exam:'.$r['id'],'type'=>'Exam','title'=>$r['title'],'academic_year'=>$r['academic_year'],'semester'=>$r['semester'],'date_from'=>$r['date_from'],'date_to'=>$r['date_to'],'entry_count'=>(int)$r['event_count'],'scope'=>$r['exam_type'].' examinations','status'=>'Published'];}
    return $out;
}
function calFindSchedule(PDO $pdo,string $key):array{
    foreach(calScheduleCatalog($pdo) as $s) if(hash_equals($s['key'],$key)) return $s;
    throw new RuntimeException('The selected schedule is no longer published. Return to Published Schedule, validate it, and publish it before exporting.');
}
function calRecipients(PDO $pdo):array{
    $out=['Teacher'=>[],'Section'=>[],'Program'=>[],'Room'=>[]];
    foreach($pdo->query("SELECT id,full_name,email,department FROM teachers WHERE status='Active' ORDER BY full_name") as $r)$out['Teacher'][]=['key'=>'Teacher:'.$r['id'],'label'=>$r['full_name'],'detail'=>trim(($r['department']?:'Faculty').($r['email']?' · '.$r['email']:''))];
    foreach($pdo->query("SELECT id,code,name,program FROM sections WHERE status='Active' ORDER BY code") as $r)$out['Section'][]=['key'=>'Section:'.$r['id'],'label'=>$r['code'],'detail'=>$r['program'].' · '.$r['name']];
    foreach($pdo->query("SELECT DISTINCT program FROM sections WHERE status='Active' AND program<>'' ORDER BY program") as $r)$out['Program'][]=['key'=>'Program:'.$r['program'],'label'=>$r['program'],'detail'=>'All published events for this program'];
    foreach($pdo->query("SELECT id,room_code,building,capacity FROM rooms WHERE status<>'Maintenance' ORDER BY room_code") as $r)$out['Room'][]=['key'=>'Room:'.$r['id'],'label'=>$r['room_code'],'detail'=>trim(($r['building']?:'Campus').' · '.$r['capacity'].' seats')];
    return $out;
}
function calRecipientMatch(array $row,array $keys):bool{
    if(!$keys)return true;
    foreach($keys as $key){[$type,$value]=array_pad(explode(':',(string)$key,2),2,'');if($type==='Teacher'&&(string)($row['teacher_id']??'')===$value)return true;if($type==='Section'&&(string)($row['section_id']??'')===$value)return true;if($type==='Room'&&(string)($row['room_id']??'')===$value)return true;if($type==='Program'&&(string)($row['program']??'')===$value)return true;}
    return false;
}
function calEvent(array $row,string $source,int $sourceId,string $date,array $settings):array{
    $tz=(string)($settings['timezone']??'Asia/Manila'); try{$zone=new DateTimeZone($tz);}catch(Throwable){$tz='Asia/Manila';$zone=new DateTimeZone($tz);}
    $start=(new DateTimeImmutable($date.' '.substr((string)$row['start_time'],0,8),$zone))->format(DateTimeInterface::ATOM);
    $end=(new DateTimeImmutable($date.' '.substr((string)$row['end_time'],0,8),$zone))->format(DateTimeInterface::ATOM);
    $subject=trim((string)($row['subject_code']??'').' — '.(string)($row['subject_name']??''),' —');
    if($source==='Special')$subject=(string)$row['source_title'];
    if($source==='Exam')$subject=(string)$row['exam_type'].' Exam — '.$subject;
    $summary=$subject; if(!empty($settings['include_section'])&&!empty($row['section_code']))$summary.=' · '.$row['section_code'];
    $parts=[]; if(!empty($settings['include_subject']))$parts[]='Subject: '.$subject;if(!empty($settings['include_section'])&&!empty($row['section_code']))$parts[]='Section: '.$row['section_code'];if(!empty($settings['include_faculty'])&&!empty($row['teacher_name']))$parts[]='Faculty: '.$row['teacher_name'];if(!empty($settings['include_room'])&&!empty($row['room_code']))$parts[]='Room: '.$row['room_code'];if(!empty($settings['include_class_type'])&&!empty($row['class_type']))$parts[]='Type: '.$row['class_type'];if(!empty($settings['include_description'])&&!empty($row['remarks']))$parts[]=(string)$row['remarks'];
    $key=hash('sha256',$source.'|'.$sourceId.'|'.$date.'|'.$start.'|'.$end);
    $event=['event_key'=>$key,'source'=>$source,'source_id'=>$sourceId,'date'=>$date,'start'=>$start,'end'=>$end,'start_time'=>substr((string)$row['start_time'],0,5),'end_time'=>substr((string)$row['end_time'],0,5),'summary'=>$summary,'description'=>implode("\n",$parts),'location'=>!empty($settings['include_room'])?(string)($row['room_code']??''):'','section_code'=>(string)($row['section_code']??''),'teacher_name'=>(string)($row['teacher_name']??''),'room_code'=>(string)($row['room_code']??''),'timezone'=>$tz,'color'=>(string)($settings['color']??'#1769e0')];
    $event['content_hash']=hash('sha256',json_encode($event,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)); return $event;
}
function calCollectEvents(PDO $pdo,array $schedule,string $from,string $to,array $keys,array $settings):array{
    if($from>$to)throw new InvalidArgumentException('Start date must not be later than end date.');
    $events=[];$type=$schedule['type'];
    if($type==='Regular'){
        $st=$pdo->prepare("SELECT se.*,s.code section_code,s.program,sub.code subject_code,sub.name subject_name,t.full_name teacher_name,r.room_code FROM schedule_entries se JOIN sections s ON s.id=se.section_id JOIN subjects sub ON sub.id=se.subject_id LEFT JOIN teachers t ON t.id=se.teacher_id LEFT JOIN rooms r ON r.id=se.room_id WHERE se.status='Published' AND se.academic_year=? AND se.semester=?");$st->execute([$schedule['academic_year'],$schedule['semester']]);$rows=$st->fetchAll();
        $sub=$pdo->prepare("SELECT sa.schedule_entry_id,sa.absence_date,st.full_name substitute_name FROM substitute_assignments sa JOIN teachers st ON st.id=sa.substitute_teacher_id WHERE sa.status IN ('Assigned','Ongoing','Completed') AND sa.absence_date BETWEEN ? AND ?");$sub->execute([$from,$to]);$subs=[];foreach($sub as $x)$subs[$x['schedule_entry_id'].'|'.$x['absence_date']]=$x['substitute_name'];
        for($cursor=new DateTimeImmutable($from);$cursor<=new DateTimeImmutable($to);$cursor=$cursor->modify('+1 day')){$date=$cursor->format('Y-m-d');$day=$cursor->format('l');foreach($rows as $r){if($r['day_of_week']!==$day||!calRecipientMatch($r,$keys))continue;$k=$r['id'].'|'.$date;if(isset($subs[$k])){$r['teacher_name']=$subs[$k];$r['remarks']=trim((string)$r['remarks'].' Substitute faculty assignment.');}$events[]=calEvent($r,'Class',(int)$r['id'],$date,$settings);}}
    }elseif($type==='Special'){
        $st=$pdo->prepare("SELECT sc.*,s.code section_code,s.program,sub.code subject_code,sub.name subject_name,t.full_name teacher_name,r.room_code,sc.title source_title,sc.special_type class_type FROM special_classes sc LEFT JOIN sections s ON s.id=sc.section_id LEFT JOIN subjects sub ON sub.id=sc.subject_id LEFT JOIN teachers t ON t.id=sc.teacher_id LEFT JOIN rooms r ON r.id=sc.room_id WHERE sc.status='Published' AND sc.academic_year=? AND sc.semester=? AND sc.class_date BETWEEN ? AND ?");$st->execute([$schedule['academic_year'],$schedule['semester'],$from,$to]);foreach($st as $r)if(calRecipientMatch($r,$keys))$events[]=calEvent($r,'Special',(int)$r['id'],$r['class_date'],$settings);
    }else{
        $batch=(int)substr($schedule['key'],5);$st=$pdo->prepare("SELECT e.*,s.code section_code,s.program,sub.code subject_code,sub.name subject_name,t.full_name teacher_name,r.room_code,'Exam' class_type FROM exam_schedules e JOIN sections s ON s.id=e.section_id JOIN subjects sub ON sub.id=e.subject_id LEFT JOIN teachers t ON t.id=e.proctor_id LEFT JOIN rooms r ON r.id=e.room_id WHERE e.status='Published' AND e.batch_id=? AND e.exam_date BETWEEN ? AND ?");$st->execute([$batch,$from,$to]);foreach($st as $r)if(calRecipientMatch($r,$keys))$events[]=calEvent($r,'Exam',(int)$r['id'],$r['exam_date'],$settings);
    }
    usort($events,fn($a,$b)=>[$a['date'],$a['start_time'],$a['summary']]<=>[$b['date'],$b['start_time'],$b['summary']]); return $events;
}
function calPayload(PDO $pdo,array $p):array{
    $key=trim((string)($p['schedule_key']??''));$schedule=calFindSchedule($pdo,$key);$from=calDate((string)($p['date_from']??$schedule['date_from']),'start date');$to=calDate((string)($p['date_to']??$schedule['date_to']),'end date');
    if($from>$to)throw new InvalidArgumentException('Start date must not be later than end date.');if((new DateTimeImmutable($from))->diff(new DateTimeImmutable($to))->days>370)throw new InvalidArgumentException('Choose a date range of 370 days or fewer.');
    $method=(string)($p['method']??'ICS');if(!in_array($method,['ICS','Google'],true))throw new InvalidArgumentException('Select ICS Export or Google Calendar.');
    $name=trim((string)($p['name']??''));if($name==='')throw new InvalidArgumentException('Calendar name is required.');if(mb_strlen($name)>150)throw new InvalidArgumentException('Calendar name must be 150 characters or fewer.');
    $keys=array_values(array_unique(array_filter(array_map('strval',(array)($p['recipient_keys']??[])))));if(!$keys)throw new InvalidArgumentException('Select at least one recipient or calendar scope.');
    $allowed=[];foreach(calRecipients($pdo) as $group)foreach($group as $r)$allowed[$r['key']]=true;foreach($keys as $k)if(!isset($allowed[$k]))throw new InvalidArgumentException('One of the selected recipients is no longer available.');
    $settings=(array)($p['settings']??[]);$settings=array_merge(['include_subject'=>true,'include_section'=>true,'include_room'=>true,'include_faculty'=>true,'include_class_type'=>true,'include_description'=>true,'timezone'=>'Asia/Manila','color'=>'#1769e0'],$settings);
    $events=calCollectEvents($pdo,$schedule,$from,$to,$keys,$settings);if(!$events)throw new RuntimeException('No published schedule events match the selected date range and recipients.');
    return compact('schedule','from','to','method','name','keys','settings','events');
}
function calIntegration(PDO $pdo,int $id):array{
    $st=$pdo->prepare("SELECT ci.*,COALESCE(u.full_name,u.username,'System') created_by_name FROM calendar_integrations ci LEFT JOIN users u ON u.id=ci.created_by WHERE ci.id=?");$st->execute([$id]);$r=$st->fetch();if(!$r)throw new RuntimeException('Calendar integration was not found.');unset($r['access_token_encrypted'],$r['refresh_token_encrypted']);$r['recipient_keys']=calJson($r['recipient_keys_json']);$r['settings']=calJson($r['settings_json']);unset($r['recipient_keys_json'],$r['settings_json']);return $r;
}
function calList(PDO $pdo):array{
    $rows=$pdo->query("SELECT ci.id,ci.reference_no,ci.name,ci.method,ci.schedule_type,ci.academic_year,ci.semester,ci.status,ci.event_count,ci.google_account_email,ci.last_sync_at,ci.last_error,ci.updated_at,COALESCE(u.full_name,u.username,'System') created_by_name FROM calendar_integrations ci LEFT JOIN users u ON u.id=ci.created_by ORDER BY ci.updated_at DESC,ci.id DESC")->fetchAll();$stats=['total'=>count($rows),'synced'=>0,'pending'=>0,'failed'=>0];foreach($rows as $r){if($r['status']==='Synced')$stats['synced']++;elseif($r['status']==='Failed')$stats['failed']++;else$stats['pending']++;}return [$rows,$stats];
}
function calIcsEscape(string $v):string{return str_replace(["\\",";",",","\r\n","\r","\n"],["\\\\","\\;","\\,","\\n","\\n","\\n"],$v);}
function calIcs(array $integration,array $events):string{
    $lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Bestlink College//SMS2 Calendar Integration//EN','CALSCALE:GREGORIAN','METHOD:PUBLISH','X-WR-CALNAME:'.calIcsEscape($integration['name'])];
    foreach($events as $e){$start=new DateTimeImmutable($e['start']);$end=new DateTimeImmutable($e['end']);$lines=array_merge($lines,['BEGIN:VEVENT','UID:'.$e['event_key'].'@sms2.local','DTSTAMP:'.gmdate('Ymd\THis\Z'),'DTSTART;TZID='.$e['timezone'].':'.$start->format('Ymd\THis'),'DTEND;TZID='.$e['timezone'].':'.$end->format('Ymd\THis'),'SUMMARY:'.calIcsEscape($e['summary']),'DESCRIPTION:'.calIcsEscape($e['description']),'LOCATION:'.calIcsEscape($e['location']),'END:VEVENT']);}
    $lines[]='END:VCALENDAR';return implode("\r\n",$lines)."\r\n";
}
function calHttp(string $method,string $url,array $headers=[],?string $body=null):array{
    if(!function_exists('curl_init'))throw new RuntimeException('PHP cURL is required for Google Calendar synchronization.');$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_HTTPHEADER=>$headers,CURLOPT_TIMEOUT=>35]);if($body!==null)curl_setopt($ch,CURLOPT_POSTFIELDS,$body);$raw=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);$err=curl_error($ch);curl_close($ch);if($raw===false)throw new RuntimeException('Google Calendar request failed: '.$err);$data=json_decode($raw,true);if($status<200||$status>=300){$message=is_array($data)?($data['error']['message']??$data['error_description']??'Google Calendar request failed.'):'Google Calendar request failed.';throw new RuntimeException($message);}return is_array($data)?$data:[];
}
function calToken(PDO $pdo,array $row):string{
    $token=smsSecretDecrypt((string)($row['access_token_encrypted']??''));$expires=!empty($row['token_expires_at'])?strtotime($row['token_expires_at']):0;if($token!==''&&$expires>time()+90)return $token;$refresh=smsSecretDecrypt((string)($row['refresh_token_encrypted']??''));if($refresh==='')throw new RuntimeException('Google authorization expired. Connect the Google account again.');$cfg=calGoogleConfig();if(!$cfg['configured'])throw new RuntimeException('Google Calendar credentials are not configured.');$data=calHttp('POST','https://oauth2.googleapis.com/token',['Content-Type: application/x-www-form-urlencoded'],http_build_query(['client_id'=>$cfg['client_id'],'client_secret'=>$cfg['client_secret'],'refresh_token'=>$refresh,'grant_type'=>'refresh_token']));$token=(string)($data['access_token']??'');if($token==='')throw new RuntimeException('Google did not return a new access token.');$pdo->prepare('UPDATE calendar_integrations SET access_token_encrypted=?,token_expires_at=? WHERE id=?')->execute([smsSecretEncrypt($token),date('Y-m-d H:i:s',time()+(int)($data['expires_in']??3600)),(int)$row['id']]);return $token;
}
function calGoogleEvent(array $e):array{return ['summary'=>$e['summary'],'description'=>$e['description'],'location'=>$e['location'],'start'=>['dateTime'=>$e['start'],'timeZone'=>$e['timezone']],'end'=>['dateTime'=>$e['end'],'timeZone'=>$e['timezone']],'extendedProperties'=>['private'=>['sms2EventKey'=>$e['event_key'],'sms2Source'=>$e['source'].':'.$e['source_id']]]];}

try{
    $pdo=getDatabaseConnection();$action=trim((string)($_GET['action']??'bootstrap'));
    if($action==='google_callback'){
        $state=(string)($_GET['state']??'');$saved=(array)($_SESSION['calendar_oauth']??[]);unset($_SESSION['calendar_oauth']);if($state===''||empty($saved['state'])||!hash_equals($saved['state'],$state))throw new RuntimeException('Google authorization state is invalid or expired.');if(!empty($_GET['error']))throw new RuntimeException('Google authorization was cancelled: '.(string)$_GET['error']);$code=(string)($_GET['code']??'');if($code==='')throw new RuntimeException('Google did not return an authorization code.');$cfg=calGoogleConfig();if(!$cfg['configured'])throw new RuntimeException('Google Calendar credentials are not configured.');$tok=calHttp('POST','https://oauth2.googleapis.com/token',['Content-Type: application/x-www-form-urlencoded'],http_build_query(['code'=>$code,'client_id'=>$cfg['client_id'],'client_secret'=>$cfg['client_secret'],'redirect_uri'=>$cfg['redirect_uri'],'grant_type'=>'authorization_code']));$access=(string)($tok['access_token']??'');if($access==='')throw new RuntimeException('Google did not return an access token.');$email='Authorized Google account';if(!empty($tok['id_token'])){$bits=explode('.',(string)$tok['id_token']);if(count($bits)>=2){$payload=json_decode(base64_decode(strtr($bits[1],'-_','+/'))?:'',true);if(is_array($payload)&&!empty($payload['email']))$email=(string)$payload['email'];}}
        $id=(int)$saved['integration_id'];$old=$pdo->prepare('SELECT status,refresh_token_encrypted FROM calendar_integrations WHERE id=?');$old->execute([$id]);$previous=$old->fetch();if(!$previous)throw new RuntimeException('Calendar integration was not found.');$refresh=(string)($tok['refresh_token']??'');if($refresh==='')$refresh=smsSecretDecrypt((string)$previous['refresh_token_encrypted']);$pdo->prepare("UPDATE calendar_integrations SET google_calendar_id='primary',google_account_email=?,access_token_encrypted=?,refresh_token_encrypted=?,token_expires_at=?,status='Connected',last_error=NULL WHERE id=?")->execute([$email,smsSecretEncrypt($access),smsSecretEncrypt($refresh),date('Y-m-d H:i:s',time()+(int)($tok['expires_in']??3600)),$id]);calHistory($pdo,$id,'Google Connected',$previous['status'],'Connected','Google Calendar account authorized.');header('Location: '.rtrim(BASE_URL,'/').'/modules/scheduling/pages/calendar-integration.php?connected=1&integration='.$id);exit;
    }
    if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='bootstrap'){[$integrations,$stats]=calList($pdo);$cfg=calGoogleConfig();calOut(['ok'=>true,'schedules'=>calScheduleCatalog($pdo),'recipients'=>calRecipients($pdo),'integrations'=>$integrations,'stats'=>$stats,'google'=>['configured'=>$cfg['configured'],'redirect_uri'=>$cfg['redirect_uri']],'timezones'=>['Asia/Manila','Australia/Perth','UTC']]);}
    if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='integration'){$id=(int)($_GET['id']??0);$row=calIntegration($pdo,$id);$h=$pdo->prepare("SELECT h.*,COALESCE(u.full_name,u.username,'System') changed_by_name FROM calendar_integration_history h LEFT JOIN users u ON u.id=h.changed_by WHERE h.integration_id=? ORDER BY h.created_at DESC,h.id DESC LIMIT 100");$h->execute([$id]);calOut(['ok'=>true,'integration'=>$row,'history'=>$h->fetchAll()]);}
    if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='export'){
        $id=(int)($_GET['id']??0);$row=calIntegration($pdo,$id);$schedule=calFindSchedule($pdo,$row['schedule_key']);$events=calCollectEvents($pdo,$schedule,$row['date_from'],$row['date_to'],$row['recipient_keys'],$row['settings']);if(!$events)throw new RuntimeException('No current published events are available for this export.');$fingerprint=hash('sha256',json_encode(array_column($events,'content_hash')));$pdo->prepare("UPDATE calendar_integrations SET status='Synced',event_count=?,source_fingerprint=?,last_sync_at=NOW(),last_error=NULL WHERE id=?")->execute([count($events),$fingerprint,$id]);calHistory($pdo,$id,'ICS Exported',$row['status'],'Synced',count($events).' published event(s) exported.',['event_count'=>count($events)]);logActivity('Calendar export',$row['reference_no'].' exported as ICS.','Scheduling');header_remove('Content-Type');header('Content-Type: text/calendar; charset=utf-8');header('Content-Disposition: attachment; filename="'.preg_replace('/[^A-Za-z0-9_-]+/','-',strtolower($row['name'])).'.ics"');echo calIcs($row,$events);exit;
    }
    $p=calBody();
    if($_SERVER['REQUEST_METHOD']==='POST'&&$action==='preview'){$v=calPayload($pdo,$p);calOut(['ok'=>true,'schedule'=>$v['schedule'],'events'=>$v['events'],'summary'=>['events'=>count($v['events']),'from'=>$v['from'],'to'=>$v['to'],'recipients'=>count($v['keys'])]]);}
    if($_SERVER['REQUEST_METHOD']==='POST'&&$action==='save'){
        $v=calPayload($pdo,$p);$id=(int)($p['id']??0);$fingerprint=hash('sha256',json_encode(array_column($v['events'],'content_hash')));$pdo->beginTransaction();if($id){$lock=$pdo->prepare('SELECT * FROM calendar_integrations WHERE id=? FOR UPDATE');$lock->execute([$id]);$old=$lock->fetch();if(!$old)throw new RuntimeException('Calendar integration was not found.');$status=$old['status']==='Synced'?'Needs Resync':($old['status']==='Failed'?'Draft':$old['status']);$methodChanged=$old['method']!==$v['method'];if($methodChanged)$status='Draft';$sql="UPDATE calendar_integrations SET name=?,method=?,schedule_key=?,schedule_type=?,academic_year=?,semester=?,date_from=?,date_to=?,recipient_keys_json=?,settings_json=?,source_fingerprint=?,status=?,event_count=?,last_error=NULL".($methodChanged?",google_calendar_id=NULL,google_account_email=NULL,access_token_encrypted=NULL,refresh_token_encrypted=NULL,token_expires_at=NULL":"")." WHERE id=?";$pdo->prepare($sql)->execute([$v['name'],$v['method'],$v['schedule']['key'],$v['schedule']['type'],$v['schedule']['academic_year'],$v['schedule']['semester'],$v['from'],$v['to'],json_encode($v['keys']),json_encode($v['settings']),$fingerprint,$status,count($v['events']),$id]);calHistory($pdo,$id,'Configuration Updated',$old['status'],$status,'Calendar export settings updated.');}
        else{$pdo->prepare("INSERT INTO calendar_integrations(name,method,schedule_key,schedule_type,academic_year,semester,date_from,date_to,recipient_keys_json,settings_json,source_fingerprint,status,event_count,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)")->execute([$v['name'],$v['method'],$v['schedule']['key'],$v['schedule']['type'],$v['schedule']['academic_year'],$v['schedule']['semester'],$v['from'],$v['to'],json_encode($v['keys']),json_encode($v['settings']),$fingerprint,'Draft',count($v['events']),calUserId()]);$id=(int)$pdo->lastInsertId();$ref='CAL-'.date('Y').'-'.str_pad((string)$id,5,'0',STR_PAD_LEFT);$pdo->prepare('UPDATE calendar_integrations SET reference_no=? WHERE id=?')->execute([$ref,$id]);calHistory($pdo,$id,'Created',null,'Draft','Calendar integration created from published schedule data.',['event_count'=>count($v['events'])]);}$pdo->commit();logActivity('Calendar integration',($id?'Saved calendar integration #'.$id:'Calendar integration saved.'),'Scheduling');calOut(['ok'=>true,'message'=>'Calendar integration saved.','integration'=>calIntegration($pdo,$id),'events'=>$v['events']]);
    }
    if($_SERVER['REQUEST_METHOD']==='GET'&&$action==='google_auth_url'){
        $id=(int)($_GET['id']??0);$row=calIntegration($pdo,$id);if($row['method']!=='Google')throw new RuntimeException('This integration is configured for ICS export.');$cfg=calGoogleConfig();if(!$cfg['configured'])throw new RuntimeException('Google Calendar is not configured. Set SMS2_GOOGLE_CALENDAR_CLIENT_ID and SMS2_GOOGLE_CALENDAR_CLIENT_SECRET on the server first.');$state=bin2hex(random_bytes(24));$_SESSION['calendar_oauth']=['state'=>$state,'integration_id'=>$id,'created_at'=>time()];$url='https://accounts.google.com/o/oauth2/v2/auth?'.http_build_query(['client_id'=>$cfg['client_id'],'redirect_uri'=>$cfg['redirect_uri'],'response_type'=>'code','scope'=>'openid email https://www.googleapis.com/auth/calendar.events','access_type'=>'offline','prompt'=>'consent','state'=>$state,'include_granted_scopes'=>'true']);calOut(['ok'=>true,'url'=>$url]);
    }
    if($_SERVER['REQUEST_METHOD']==='POST'&&$action==='sync'){
        $id=(int)($p['id']??0);$raw=$pdo->prepare('SELECT * FROM calendar_integrations WHERE id=?');$raw->execute([$id]);$row=$raw->fetch();if(!$row)throw new RuntimeException('Calendar integration was not found.');if($row['method']!=='Google')throw new RuntimeException('This integration is configured for ICS export.');if(in_array($row['status'],['Draft','Disconnected'],true))throw new RuntimeException('Connect a Google account before synchronizing.');$schedule=calFindSchedule($pdo,$row['schedule_key']);$keys=calJson($row['recipient_keys_json']);$settings=calJson($row['settings_json']);$events=calCollectEvents($pdo,$schedule,$row['date_from'],$row['date_to'],$keys,$settings);if(!$events)throw new RuntimeException('No current published events are available to synchronize.');$token=calToken($pdo,$row);$map=$pdo->prepare('SELECT * FROM calendar_integration_events WHERE integration_id=?');$map->execute([$id]);$existing=[];foreach($map as $m)$existing[$m['event_key']]=$m;$created=0;$updated=0;$unchanged=0;$failed=0;$pdo->beginTransaction();
        foreach($events as $e){try{$m=$existing[$e['event_key']]??null;$body=json_encode(calGoogleEvent($e),JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);$calendar=rawurlencode((string)($row['google_calendar_id']?:'primary'));if($m&&!empty($m['google_event_id'])){if(hash_equals((string)$m['content_hash'],$e['content_hash'])){$status='Unchanged';$unchanged++;}else{$data=calHttp('PUT','https://www.googleapis.com/calendar/v3/calendars/'.$calendar.'/events/'.rawurlencode($m['google_event_id']),['Authorization: Bearer '.$token,'Content-Type: application/json'],$body);$m['google_event_id']=$data['id']??$m['google_event_id'];$status='Updated';$updated++;}}else{$data=calHttp('POST','https://www.googleapis.com/calendar/v3/calendars/'.$calendar.'/events',['Authorization: Bearer '.$token,'Content-Type: application/json'],$body);$m=['google_event_id'=>$data['id']??null];$status='Created';$created++;}$up=$pdo->prepare("INSERT INTO calendar_integration_events(integration_id,event_key,source_type,source_id,occurrence_date,google_event_id,content_hash,sync_status,error_message,synced_at) VALUES(?,?,?,?,?,?,?,?,NULL,NOW()) ON DUPLICATE KEY UPDATE google_event_id=VALUES(google_event_id),content_hash=VALUES(content_hash),sync_status=VALUES(sync_status),error_message=NULL,synced_at=NOW()");$up->execute([$id,$e['event_key'],$e['source'],$e['source_id'],$e['date'],$m['google_event_id'],$e['content_hash'],$status]);}catch(Throwable $eventError){$failed++;$up=$pdo->prepare("INSERT INTO calendar_integration_events(integration_id,event_key,source_type,source_id,occurrence_date,content_hash,sync_status,error_message,synced_at) VALUES(?,?,?,?,?,?,'Failed',?,NOW()) ON DUPLICATE KEY UPDATE content_hash=VALUES(content_hash),sync_status='Failed',error_message=VALUES(error_message),synced_at=NOW()");$up->execute([$id,$e['event_key'],$e['source'],$e['source_id'],$e['date'],$e['content_hash'],substr($eventError->getMessage(),0,500)]);}}
        $newStatus=$failed?'Failed':'Synced';$fingerprint=hash('sha256',json_encode(array_column($events,'content_hash')));$pdo->prepare('UPDATE calendar_integrations SET status=?,event_count=?,source_fingerprint=?,last_sync_at=NOW(),last_error=? WHERE id=?')->execute([$newStatus,count($events),$fingerprint,$failed?$failed.' event(s) failed to synchronize.':null,$id]);calHistory($pdo,$id,'Google Synced',$row['status'],$newStatus,'Google Calendar synchronization completed.',['created'=>$created,'updated'=>$updated,'unchanged'=>$unchanged,'failed'=>$failed]);$pdo->commit();logActivity('Calendar sync',$row['reference_no'].' synchronized to Google Calendar.','Scheduling');calOut(['ok'=>$failed===0,'message'=>$failed?'Synchronization finished with errors.':'Calendar synchronized successfully.','result'=>compact('created','updated','unchanged','failed'),'integration'=>calIntegration($pdo,$id)],$failed?207:200);
    }
    if($_SERVER['REQUEST_METHOD']==='POST'&&$action==='disconnect'){
        $id=(int)($p['id']??0);$st=$pdo->prepare('SELECT status FROM calendar_integrations WHERE id=?');$st->execute([$id]);$old=$st->fetchColumn();if($old===false)throw new RuntimeException('Calendar integration was not found.');$pdo->prepare("UPDATE calendar_integrations SET status='Disconnected',access_token_encrypted=NULL,refresh_token_encrypted=NULL,token_expires_at=NULL,last_error=NULL WHERE id=?")->execute([$id]);calHistory($pdo,$id,'Disconnected',(string)$old,'Disconnected','Google authorization removed. Existing external calendar events were left unchanged.');logActivity('Calendar disconnect','Calendar integration #'.$id.' disconnected.','Scheduling');calOut(['ok'=>true,'message'=>'Google account disconnected. Existing Google Calendar events were not deleted.']);
    }
    calOut(['ok'=>false,'error'=>'Unsupported Calendar Integration action.'],404);
}catch(InvalidArgumentException $e){if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack();calOut(['ok'=>false,'error'=>$e->getMessage()],422);}catch(Throwable $e){if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack();error_log('Calendar integration: '.$e->getMessage());calOut(['ok'=>false,'error'=>$e->getMessage()],500);}
