<?php
declare(strict_types=1);

/** Connected, draft-first Exam Timetable Generator workflow API. */
require_once __DIR__ . '/../../config/config.php';
require_once ROOT_PATH . '/config/database.php';
require_once ROOT_PATH . '/includes/authentication.php';
require_once ROOT_PATH . '/includes/audit.php';
header('Content-Type: application/json; charset=utf-8');
if(function_exists('isAuthenticated')&&!isAuthenticated()){http_response_code(401);echo json_encode(['ok'=>false,'error'=>'Authentication required.']);exit;}
if(function_exists('userCanAccessModule')&&!userCanAccessModule('scheduling')){http_response_code(403);echo json_encode(['ok'=>false,'error'=>'You do not have permission to access Class Scheduling.']);exit;}

const EXW_TYPES=['Prelim','Midterm','Semi-Final','Final','Special'];
const EXW_TERMS=['1st Semester','2nd Semester','Summer'];
function exwOut(array $d,int $s=200):never{http_response_code($s);echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function exwBody():array{$x=json_decode((string)file_get_contents('php://input'),true);if(!is_array($x))$x=$_POST?:[];return $x;}
function exwActor():?int{return function_exists('getCurrentUserId')?getCurrentUserId():null;}
function exwDate(string $v,string $label):string{$v=trim($v);if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$v))throw new InvalidArgumentException("{$label} must use YYYY-MM-DD.");[$y,$m,$d]=array_map('intval',explode('-',$v));if(!checkdate($m,$d,$y))throw new InvalidArgumentException("{$label} is not a valid date.");return $v;}
function exwHistory(PDO $pdo,int $batch,?int $exam,string $action,?string $from,?string $to,string $detail,array $snapshot=[]):void{$s=$pdo->prepare('INSERT INTO exam_timetable_history(batch_id,exam_schedule_id,action,from_status,to_status,detail,snapshot_json,changed_by) VALUES(?,?,?,?,?,?,?,?)');$s->execute([$batch,$exam,$action,$from,$to,$detail,$snapshot?json_encode($snapshot,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE):null,exwActor()]);}
function exwBatch(PDO $pdo,int $id):?array{
 $s=$pdo->prepare("SELECT b.*,COALESCE(u.full_name,u.username,'System') created_by_name FROM exam_timetable_batches b LEFT JOIN users u ON u.id=b.created_by WHERE b.id=?");$s->execute([$id]);$b=$s->fetch(PDO::FETCH_ASSOC);if(!$b)return null;$b['id']=(int)$b['id'];$b['options']=json_decode((string)$b['options_json'],true)?:[];$b['validation_summary']=json_decode((string)$b['validation_summary_json'],true)?:null;
 $r=$pdo->prepare("SELECT ex.*,sec.code section_code,sec.name section_name,sec.program,sec.current_students,sub.code subject_code,sub.name subject_name,t.full_name proctor_name,t.employee_no,r.room_code,r.room_type,r.building,r.capacity,tb.code time_block_code,tb.label time_block_label FROM exam_schedules ex JOIN sections sec ON sec.id=ex.section_id JOIN subjects sub ON sub.id=ex.subject_id LEFT JOIN teachers t ON t.id=ex.proctor_id LEFT JOIN rooms r ON r.id=ex.room_id LEFT JOIN time_blocks tb ON tb.id=ex.time_block_id WHERE ex.batch_id=? ORDER BY ex.exam_date IS NULL,ex.exam_date,ex.start_time,sec.code,sub.code");$r->execute([$id]);$b['records']=$r->fetchAll(PDO::FETCH_ASSOC);
 $h=$pdo->prepare("SELECT h.*,COALESCE(u.full_name,u.username,'System') changed_by_name FROM exam_timetable_history h LEFT JOIN users u ON u.id=h.changed_by WHERE h.batch_id=? ORDER BY h.created_at DESC,h.id DESC");$h->execute([$id]);$b['history']=$h->fetchAll(PDO::FETCH_ASSOC);
 $sh=$pdo->prepare("SELECT s.*,COALESCE(u.full_name,u.username,'System') sent_by_name FROM exam_timetable_shares s LEFT JOIN users u ON u.id=s.sent_by WHERE s.batch_id=? ORDER BY s.created_at DESC,s.id DESC");$sh->execute([$id]);$b['shares']=$sh->fetchAll(PDO::FETCH_ASSOC);return $b;
}
function exwDashboard(PDO $pdo):array{
 $rows=$pdo->query("SELECT b.*,COUNT(ex.id) entry_count,SUM(ex.exam_date IS NULL) unscheduled_count,SUM(ex.status='Published') published_count,COALESCE(u.full_name,u.username,'System') created_by_name FROM exam_timetable_batches b LEFT JOIN exam_schedules ex ON ex.batch_id=b.id LEFT JOIN users u ON u.id=b.created_by GROUP BY b.id ORDER BY b.updated_at DESC,b.id DESC")->fetchAll(PDO::FETCH_ASSOC);
 $summary=['total'=>count($rows),'draft'=>0,'validation'=>0,'ready'=>0,'published'=>0];foreach($rows as &$r){$status=$r['status'];if($status==='Published')$summary['published']++;elseif($status==='Ready to Publish')$summary['ready']++;elseif(in_array($status,['For Validation','Validated'],true))$summary['validation']++;else$summary['draft']++;}unset($r);return ['batches'=>$rows,'summary'=>$summary];
}
function exwOptions(PDO $pdo):array{
 $sections=$pdo->query("SELECT id,code,name,program,year_level,semester,academic_year,current_students FROM sections WHERE status='Active' ORDER BY code")->fetchAll(PDO::FETCH_ASSOC);
 $years=array_values(array_unique(array_filter(array_column($sections,'academic_year'))));rsort($years);
 return ['types'=>EXW_TYPES,'semesters'=>EXW_TERMS,'academic_years'=>$years,'programs'=>array_values(array_unique(array_filter(array_column($sections,'program')))),
  'sections'=>$sections,
  'time_blocks'=>$pdo->query("SELECT id,code,label,start_time,end_time FROM time_blocks WHERE is_active=1 AND block_type='Exam' ORDER BY start_time")->fetchAll(PDO::FETCH_ASSOC),
  'rooms'=>$pdo->query("SELECT id,room_code,room_type,building,capacity,status FROM rooms ORDER BY room_code")->fetchAll(PDO::FETCH_ASSOC),
  'teachers'=>$pdo->query("SELECT id,employee_no,full_name,department,status FROM teachers ORDER BY full_name")->fetchAll(PDO::FETCH_ASSOC),
  'engine'=>['preferred'=>'Google OR-Tools CP-SAT','available'=>false,'active'=>'Explainable deterministic fallback','note'=>'OR-Tools is not installed on this host. Generation remains constraint-aware and reviewable.']];
}
function exwSetup(array $p):array{
 $title=trim((string)($p['title']??''));if($title===''||mb_strlen($title)>150)throw new InvalidArgumentException('Exam title is required and must be 150 characters or fewer.');
 $type=trim((string)($p['exam_type']??''));if(!in_array($type,EXW_TYPES,true))throw new InvalidArgumentException('Select a valid exam type.');
 $ay=trim((string)($p['academic_year']??''));if($ay==='')throw new InvalidArgumentException('Academic Year is required.');$sem=trim((string)($p['semester']??''));if(!in_array($sem,EXW_TERMS,true))throw new InvalidArgumentException('Select a valid semester.');
 $from=exwDate((string)($p['date_from']??''),'Start date');$to=exwDate((string)($p['date_to']??''),'End date');if($from>$to)throw new InvalidArgumentException('Start date must not be after end date.');if((strtotime($to)-strtotime($from))>86400*60)throw new InvalidArgumentException('The exam date range may not exceed 60 days.');
 return ['title'=>$title,'exam_type'=>$type,'academic_year'=>$ay,'semester'=>$sem,'date_from'=>$from,'date_to'=>$to];
}
function exwOptionsPayload(PDO $pdo,array $p):array{
 $ids=array_values(array_unique(array_map('intval',$p['time_block_ids']??[])));if(!$ids)throw new InvalidArgumentException('Select at least one active exam-specific time block.');$ph=implode(',',array_fill(0,count($ids),'?'));$s=$pdo->prepare("SELECT id FROM time_blocks WHERE id IN ($ph) AND is_active=1 AND block_type='Exam'");$s->execute($ids);$valid=array_map('intval',$s->fetchAll(PDO::FETCH_COLUMN));if(count($valid)!==count($ids))throw new RuntimeException('One or more selected exam time blocks are inactive or invalid. Refresh and choose again.');
 $excluded=array_values(array_intersect(['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],array_map('strval',$p['excluded_weekdays']??[])));
 return ['include_regular'=>!empty($p['include_regular']),'include_special'=>!empty($p['include_special']),'reuse_rooms'=>!empty($p['reuse_rooms']),'auto_rooms'=>!empty($p['auto_rooms']),'time_block_ids'=>$ids,'min_gap_minutes'=>max(0,min(1440,(int)($p['min_gap_minutes']??0))),'max_per_day'=>max(1,min(6,(int)($p['max_per_day']??2))),'balance_days'=>!empty($p['balance_days']),'minimize_room_changes'=>!empty($p['minimize_room_changes']),'excluded_weekdays'=>$excluded,'program'=>trim((string)($p['program']??''))];
}
function exwOverlap(string $as,string $ae,string $bs,string $be):bool{return $as<$be&&$ae>$bs;}
function exwGenerate(PDO $pdo,array $batch,array $opt):array{
 $params=['ay'=>$batch['academic_year'],'sem'=>$batch['semester']];$programSql='';if($opt['program']!==''){$programSql=' AND sec.program=:program';$params['program']=$opt['program'];}
 $pool=[];
 if($opt['include_regular']){$s=$pdo->prepare("SELECT sec.id section_id,sub.id subject_id,sec.code section_code,sec.current_students,sub.code subject_code FROM section_subjects ss JOIN sections sec ON sec.id=ss.section_id JOIN subjects sub ON sub.id=ss.subject_id WHERE ss.status='Assigned' AND sec.status='Active' AND sub.status='Active' AND sec.academic_year=:ay AND sec.semester=:sem $programSql ORDER BY sec.code,sub.code");$s->execute($params);foreach($s->fetchAll(PDO::FETCH_ASSOC) as $x)$pool[$x['section_id'].':'.$x['subject_id']]=$x;}
 if($opt['include_special']){$s=$pdo->prepare("SELECT sec.id section_id,sub.id subject_id,sec.code section_code,sec.current_students,sub.code subject_code FROM special_classes sc JOIN sections sec ON sec.id=sc.section_id JOIN subjects sub ON sub.id=sc.subject_id WHERE sc.status<>'Cancelled' AND sec.academic_year=:ay AND sec.semester=:sem $programSql");$s->execute($params);foreach($s->fetchAll(PDO::FETCH_ASSOC) as $x)$pool[$x['section_id'].':'.$x['subject_id']]=$x;}
 if(!$pool)throw new RuntimeException('No eligible section-subject records were found. Check Section Assignment and the selected term/program.');
 $blockPh=implode(',',array_fill(0,count($opt['time_block_ids']),'?'));$s=$pdo->prepare("SELECT id,code,label,start_time,end_time FROM time_blocks WHERE id IN ($blockPh) AND is_active=1 AND block_type='Exam' ORDER BY start_time");$s->execute($opt['time_block_ids']);$blocks=$s->fetchAll(PDO::FETCH_ASSOC);if(!$blocks)throw new RuntimeException('No active exam-specific time blocks are available.');
 $slots=[];$cursor=strtotime($batch['date_from']);$end=strtotime($batch['date_to']);while($cursor<=$end){$day=date('l',$cursor);if(!in_array($day,$opt['excluded_weekdays'],true))foreach($blocks as $b)$slots[]=['date'=>date('Y-m-d',$cursor),'day'=>$day,'block'=>$b];$cursor=strtotime('+1 day',$cursor);}if(!$slots)throw new RuntimeException('The selected range has no usable date after applying excluded weekdays.');
 $rooms=$pdo->query("SELECT id,room_code,capacity FROM rooms WHERE status='Available' ORDER BY capacity,room_code")->fetchAll(PDO::FETCH_ASSOC);if(!$rooms)throw new RuntimeException('No rooms are currently Available.');
 $map=$pdo->prepare("SELECT teacher_id,room_id FROM schedule_entries WHERE section_id=? AND subject_id=? AND status IN ('Published','Validated','Draft') ORDER BY FIELD(status,'Published','Validated','Draft'),updated_at DESC LIMIT 1");
 $regular=$pdo->query("SELECT section_id,teacher_id,room_id,day_of_week,NULL on_date,start_time,end_time FROM schedule_entries WHERE status IN ('Published','Validated')")->fetchAll(PDO::FETCH_ASSOC);
 $special=$pdo->prepare("SELECT section_id,teacher_id,room_id,NULL day_of_week,class_date on_date,start_time,end_time FROM special_classes WHERE status<>'Cancelled' AND class_date BETWEEN ? AND ?");$special->execute([$batch['date_from'],$batch['date_to']]);$commit=array_merge($regular,$special->fetchAll(PDO::FETCH_ASSOC));
 $other=$pdo->prepare("SELECT section_id,proctor_id teacher_id,room_id,NULL day_of_week,exam_date on_date,start_time,end_time FROM exam_schedules WHERE status<>'Cancelled' AND batch_id<>? AND exam_date BETWEEN ? AND ?");$other->execute([$batch['id'],$batch['date_from'],$batch['date_to']]);$commit=array_merge($commit,$other->fetchAll(PDO::FETCH_ASSOC));
 $pdo->prepare("DELETE FROM exam_schedules WHERE batch_id=? AND status<>'Published'")->execute([$batch['id']]);
 $insert=$pdo->prepare("INSERT INTO exam_schedules(batch_id,section_id,subject_id,proctor_id,room_id,time_block_id,exam_type,exam_date,start_time,end_time,status,source,academic_year,semester,remarks,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,'Draft','Optimizer',?,?,?,?)");
 $assigned=[];$daily=[];$lastRoom=[];$applied=0;$unscheduled=0;$decisions=[];
 foreach($pool as $x){$map->execute([(int)$x['section_id'],(int)$x['subject_id']]);$m=$map->fetch(PDO::FETCH_ASSOC)?:[];$teacher=!empty($m['teacher_id'])?(int)$m['teacher_id']:null;$preferred=!empty($m['room_id'])?(int)$m['room_id']:null;$slotList=$slots;if($opt['balance_days'])usort($slotList,fn($a,$b)=>(($daily[$a['date']]??0)<=>($daily[$b['date']]??0))?:strcmp($a['date'].' '.$a['block']['start_time'],$b['date'].' '.$b['block']['start_time']));$choice=null;
  foreach($slotList as $slot){$dayKey=$x['section_id'].':'.$slot['date'];if(($daily[$dayKey]??0)>=$opt['max_per_day'])continue;$busy=false;foreach(array_merge($commit,$assigned) as $c){$sameDate=!empty($c['on_date'])?$c['on_date']===$slot['date']:$c['day_of_week']===$slot['day'];if(!$sameDate||!exwOverlap($slot['block']['start_time'],$slot['block']['end_time'],$c['start_time'],$c['end_time']))continue;if((int)($c['section_id']??0)===(int)$x['section_id']||($teacher&&(int)($c['teacher_id']??0)===$teacher)){$busy=true;break;}}if($busy)continue;
   if($opt['min_gap_minutes']>0){foreach($assigned as $c)if((int)$c['section_id']===(int)$x['section_id']&&$c['on_date']===$slot['date']){$gap=min(abs(strtotime($slot['block']['start_time'])-strtotime($c['end_time'])),abs(strtotime($c['start_time'])-strtotime($slot['block']['end_time'])))/60;if($gap<$opt['min_gap_minutes']){$busy=true;break;}}if($busy)continue;}
   $roomCandidates=$rooms;if($opt['minimize_room_changes']&&!empty($lastRoom[$x['section_id']]))usort($roomCandidates,fn($a,$b)=>(($a['id']==$lastRoom[$x['section_id']]?0:1)<=>($b['id']==$lastRoom[$x['section_id']]?0:1)));if($opt['reuse_rooms']&&$preferred)usort($roomCandidates,fn($a,$b)=>(($a['id']===$preferred?0:1)<=>($b['id']===$preferred?0:1)));if(!$opt['auto_rooms']&&$preferred)$roomCandidates=array_values(array_filter($roomCandidates,fn($r)=>(int)$r['id']===$preferred));$room=null;foreach($roomCandidates as $r){if((int)$r['capacity']>0&&(int)$r['capacity']<(int)$x['current_students'])continue;$taken=false;foreach(array_merge($commit,$assigned) as $c){$sameDate=!empty($c['on_date'])?$c['on_date']===$slot['date']:$c['day_of_week']===$slot['day'];if($sameDate&&(int)($c['room_id']??0)===(int)$r['id']&&exwOverlap($slot['block']['start_time'],$slot['block']['end_time'],$c['start_time'],$c['end_time'])){$taken=true;break;}}if(!$taken){$room=$r;break;}}if($room){$choice=['slot'=>$slot,'room'=>$room];break;}
  }
  if($choice){$sl=$choice['slot'];$room=$choice['room'];$insert->execute([$batch['id'],$x['section_id'],$x['subject_id'],$teacher,$room['id'],$sl['block']['id'],$batch['exam_type'],$sl['date'],$sl['block']['start_time'],$sl['block']['end_time'],$batch['academic_year'],$batch['semester'],'Generated as Draft by explainable constraint solver.',exwActor()]);$examId=(int)$pdo->lastInsertId();$assigned[]=['section_id'=>$x['section_id'],'teacher_id'=>$teacher,'room_id'=>$room['id'],'day_of_week'=>$sl['day'],'on_date'=>$sl['date'],'start_time'=>$sl['block']['start_time'],'end_time'=>$sl['block']['end_time']];$daily[$x['section_id'].':'.$sl['date']]=($daily[$x['section_id'].':'.$sl['date']]??0)+1;$daily[$sl['date']]=($daily[$sl['date']]??0)+1;$lastRoom[$x['section_id']]=$room['id'];$applied++;$decisions[]=['exam_id'=>$examId,'section'=>$x['section_code'],'subject'=>$x['subject_code'],'slot'=>$sl['date'].' '.$sl['block']['code'],'room'=>$room['room_code'],'reason'=>'First feasible candidate after configured balancing, gap, availability, capacity, section, faculty, and room checks.'];}
  else{$insert->execute([$batch['id'],$x['section_id'],$x['subject_id'],$teacher,null,null,$batch['exam_type'],null,null,null,$batch['academic_year'],$batch['semester'],'No feasible slot/room found; requires manual adjustment.',exwActor()]);$unscheduled++;}
 }
 return ['applied'=>$applied,'unscheduled'=>$unscheduled,'entries'=>count($pool),'slots'=>count($slots),'rooms'=>count($rooms),'decisions'=>$decisions,'engine'=>'Explainable deterministic fallback','engine_note'=>'Google OR-Tools CP-SAT was preferred but is unavailable on this host. No rule was bypassed.'];
}
function exwFreshIssues(PDO $pdo,int $batchId):array{
 $s=$pdo->prepare("SELECT ex.*,sec.current_students,r.capacity,r.status room_status,t.status teacher_status,tb.block_type,tb.is_active,tb.start_time block_start,tb.end_time block_end FROM exam_schedules ex JOIN sections sec ON sec.id=ex.section_id LEFT JOIN rooms r ON r.id=ex.room_id LEFT JOIN teachers t ON t.id=ex.proctor_id LEFT JOIN time_blocks tb ON tb.id=ex.time_block_id WHERE ex.batch_id=? AND ex.status<>'Cancelled'");
 $s->execute([$batchId]);
 $rows=$s->fetchAll(PDO::FETCH_ASSOC);$issues=[];
 $qualificationRules=(int)$pdo->query("SELECT COUNT(*) FROM teacher_subject_qualifications WHERE status='Active'")->fetchColumn();
 $qualified=$pdo->prepare("SELECT 1 FROM teacher_subject_qualifications WHERE teacher_id=? AND subject_id=? AND status='Active' LIMIT 1");
 $unavailable=$pdo->prepare("SELECT 1 FROM teacher_availability WHERE teacher_id=? AND day_of_week=? AND availability='Unavailable' AND (academic_year IS NULL OR academic_year=?) AND (semester IS NULL OR semester=?) AND start_time<? AND end_time>? LIMIT 1");
 $regular=$pdo->prepare("SELECT id,section_id,teacher_id,room_id FROM schedule_entries WHERE status IN ('Published','Validated') AND academic_year=? AND semester=? AND day_of_week=? AND start_time<? AND end_time>? AND (section_id=? OR teacher_id=? OR room_id=?)");
 $special=$pdo->prepare("SELECT id,section_id,teacher_id,room_id FROM special_classes WHERE status<>'Cancelled' AND academic_year=? AND semester=? AND class_date=? AND start_time<? AND end_time>? AND (section_id=? OR teacher_id=? OR room_id=?)");
 $otherExam=$pdo->prepare("SELECT id,section_id,proctor_id teacher_id,room_id FROM exam_schedules WHERE batch_id<>? AND status<>'Cancelled' AND academic_year=? AND semester=? AND exam_date=? AND start_time<? AND end_time>? AND (section_id=? OR proctor_id=? OR room_id=?)");
 foreach($rows as $r){
  $label='Exam #'.$r['id'];
  if(!$r['exam_date']||!$r['start_time']||!$r['end_time']){$issues[]="$label is not scheduled.";continue;}
  if(!$r['time_block_id']||$r['block_type']!=='Exam'||!(int)$r['is_active']||$r['block_start']!==$r['start_time']||$r['block_end']!==$r['end_time'])$issues[]="$label does not use a matching active exam time block.";
  if(!$r['room_id']||$r['room_status']!=='Available')$issues[]="$label has no available room.";elseif((int)$r['capacity']<(int)$r['current_students'])$issues[]="$label exceeds room capacity.";
  if(!$r['proctor_id']||$r['teacher_status']!=='Active')$issues[]="$label has no active proctor.";
  elseif($qualificationRules>0){$qualified->execute([$r['proctor_id'],$r['subject_id']]);if(!$qualified->fetchColumn())$issues[]="$label has a proctor who is not qualified for the subject.";}
  if($r['proctor_id']){$unavailable->execute([$r['proctor_id'],date('l',strtotime($r['exam_date'])),$r['academic_year'],$r['semester'],$r['end_time'],$r['start_time']]);if($unavailable->fetchColumn())$issues[]="$label overlaps the proctor's unavailable period.";}
  $checks=[];
  $regular->execute([$r['academic_year'],$r['semester'],date('l',strtotime($r['exam_date'])),$r['end_time'],$r['start_time'],$r['section_id'],$r['proctor_id'],$r['room_id']]);foreach($regular->fetchAll(PDO::FETCH_ASSOC) as $x)$checks[]=['Regular',$x];
  $special->execute([$r['academic_year'],$r['semester'],$r['exam_date'],$r['end_time'],$r['start_time'],$r['section_id'],$r['proctor_id'],$r['room_id']]);foreach($special->fetchAll(PDO::FETCH_ASSOC) as $x)$checks[]=['Special',$x];
  $otherExam->execute([$batchId,$r['academic_year'],$r['semester'],$r['exam_date'],$r['end_time'],$r['start_time'],$r['section_id'],$r['proctor_id'],$r['room_id']]);foreach($otherExam->fetchAll(PDO::FETCH_ASSOC) as $x)$checks[]=['Exam',$x];
  foreach($checks as [$source,$x]){if((int)$x['section_id']===(int)$r['section_id'])$issues[]="$label has a section conflict with $source schedule #{$x['id']}.";if($r['room_id']&&(int)$x['room_id']===(int)$r['room_id'])$issues[]="$label has a room conflict with $source schedule #{$x['id']}.";if($r['proctor_id']&&(int)$x['teacher_id']===(int)$r['proctor_id'])$issues[]="$label has a proctor conflict with $source schedule #{$x['id']}.";}
 }
 for($i=0;$i<count($rows);$i++)for($j=$i+1;$j<count($rows);$j++){$a=$rows[$i];$b=$rows[$j];if($a['exam_date']&&$a['exam_date']===$b['exam_date']&&exwOverlap((string)$a['start_time'],(string)$a['end_time'],(string)$b['start_time'],(string)$b['end_time'])){if($a['section_id']===$b['section_id'])$issues[]="Section conflict between exam #{$a['id']} and #{$b['id']}.";if($a['room_id']&&$a['room_id']===$b['room_id'])$issues[]="Room conflict between exam #{$a['id']} and #{$b['id']}.";if($a['proctor_id']&&$a['proctor_id']===$b['proctor_id'])$issues[]="Proctor conflict between exam #{$a['id']} and #{$b['id']}.";}}
 return array_values(array_unique($issues));
}

try{
 $pdo=getDatabaseConnection();$method=$_SERVER['REQUEST_METHOD'];
 if($method==='GET'){$action=trim((string)($_GET['action']??'bootstrap'));if($action==='bootstrap')exwOut(['ok'=>true]+exwDashboard($pdo)+['options'=>exwOptions($pdo)]);if($action==='batch'){$b=exwBatch($pdo,(int)($_GET['id']??0));if(!$b)throw new RuntimeException('Exam timetable was not found.');exwOut(['ok'=>true,'batch'=>$b]);}throw new InvalidArgumentException('Unknown action.');}
 if($method!=='POST')exwOut(['ok'=>false,'error'=>'Method not allowed.'],405);$p=exwBody();$action=trim((string)($p['action']??''));
 if($action==='save_setup'){$f=exwSetup($p);$id=(int)($p['id']??0);$pdo->beginTransaction();if($id){$b=exwBatch($pdo,$id);if(!$b)throw new RuntimeException('Exam timetable was not found.');if(in_array($b['status'],['Published','Cancelled'],true))throw new RuntimeException('Published or cancelled timetables cannot be reconfigured.');$st=$pdo->prepare('UPDATE exam_timetable_batches SET title=?,exam_type=?,academic_year=?,semester=?,date_from=?,date_to=?,status=\'Draft\',validation_run_id=NULL,validation_summary_json=NULL WHERE id=?');$st->execute([$f['title'],$f['exam_type'],$f['academic_year'],$f['semester'],$f['date_from'],$f['date_to'],$id]);exwHistory($pdo,$id,null,'Setup updated',$b['status'],'Draft','Exam details updated.',$f);}else{$st=$pdo->prepare("INSERT INTO exam_timetable_batches(reference_no,title,exam_type,academic_year,semester,date_from,date_to,status,created_by) VALUES(NULL,?,?,?,?,?,?,'Draft',?)");$st->execute([$f['title'],$f['exam_type'],$f['academic_year'],$f['semester'],$f['date_from'],$f['date_to'],exwActor()]);$id=(int)$pdo->lastInsertId();$ref='EXM-'.date('Y').'-'.str_pad((string)$id,6,'0',STR_PAD_LEFT);$pdo->prepare('UPDATE exam_timetable_batches SET reference_no=? WHERE id=?')->execute([$ref,$id]);exwHistory($pdo,$id,null,'Created',null,'Draft','Exam timetable setup created.',$f);}$pdo->commit();logActivity('Save exam setup',"Exam timetable #{$id} saved as Draft.",'scheduling');exwOut(['ok'=>true,'message'=>'Exam details saved as Draft. Configure generation options next.','batch'=>exwBatch($pdo,$id)]);}
 if($action==='generate'){$id=(int)($p['batch_id']??0);$b=exwBatch($pdo,$id);if(!$b)throw new RuntimeException('Exam timetable was not found.');if(in_array($b['status'],['Published','Cancelled'],true))throw new RuntimeException('This timetable cannot be regenerated.');$opt=exwOptionsPayload($pdo,$p);$pdo->beginTransaction();$result=exwGenerate($pdo,$b,$opt);$settings=$opt+['generation'=>$result];$pdo->prepare("UPDATE exam_timetable_batches SET options_json=?,solver_engine=?,status='Generated',validation_run_id=NULL,validation_summary_json=NULL WHERE id=?")->execute([json_encode($settings,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),$result['engine'],$id]);exwHistory($pdo,$id,null,'Generated',$b['status'],'Generated',"Generated {$result['applied']} scheduled draft(s); {$result['unscheduled']} require adjustment.",$result);$pdo->commit();logActivity('Generate exam timetable',"{$b['reference_no']} generated {$result['entries']} draft exam(s).",'scheduling');exwOut(['ok'=>true,'message'=>"Generated {$result['applied']} scheduled draft exam(s). Review the preview before validation.",'result'=>$result,'batch'=>exwBatch($pdo,$id)]);}
 if($action==='adjust'){$id=(int)($p['id']??0);$st=$pdo->prepare('SELECT ex.*,b.status batch_status FROM exam_schedules ex JOIN exam_timetable_batches b ON b.id=ex.batch_id WHERE ex.id=?');$st->execute([$id]);$r=$st->fetch(PDO::FETCH_ASSOC);if(!$r)throw new RuntimeException('Exam entry was not found.');if(in_array($r['batch_status'],['Published','Cancelled'],true))throw new RuntimeException('This timetable is read-only.');$date=exwDate((string)($p['exam_date']??''),'Exam date');$block=(int)($p['time_block_id']??0);$room=(int)($p['room_id']??0);$teacher=(int)($p['proctor_id']??0);$bs=$pdo->prepare("SELECT * FROM time_blocks WHERE id=? AND is_active=1 AND block_type='Exam'");$bs->execute([$block]);$tb=$bs->fetch(PDO::FETCH_ASSOC);if(!$tb)throw new RuntimeException('Select an active exam-specific time block.');$rs=$pdo->prepare("SELECT id FROM rooms WHERE id=? AND status='Available'");$rs->execute([$room]);if(!$rs->fetch())throw new RuntimeException('Select an available room.');$ts=$pdo->prepare("SELECT id FROM teachers WHERE id=? AND status='Active'");$ts->execute([$teacher]);if(!$ts->fetch())throw new RuntimeException('Select an active proctor.');$pdo->beginTransaction();$pdo->prepare("UPDATE exam_schedules SET exam_date=?,start_time=?,end_time=?,time_block_id=?,room_id=?,proctor_id=?,status='Draft',remarks=? WHERE id=?")->execute([$date,$tb['start_time'],$tb['end_time'],$block,$room,$teacher,trim((string)($p['remarks']??''))?:'Manually adjusted',$id]);$pdo->prepare("UPDATE exam_timetable_batches SET status='Generated',validation_run_id=NULL,validation_summary_json=NULL WHERE id=?")->execute([$r['batch_id']]);exwHistory($pdo,(int)$r['batch_id'],$id,'Adjusted',$r['status'],'Draft','Exam date, time block, room, or proctor adjusted.',$p);$pdo->commit();exwOut(['ok'=>true,'message'=>'Exam entry updated. Run conflict validation again.','batch'=>exwBatch($pdo,(int)$r['batch_id'])]);}
 if($action==='sync_validation'){$id=(int)($p['batch_id']??0);$runId=trim((string)($p['run_id']??''));$b=exwBatch($pdo,$id);if(!$b)throw new RuntimeException('Exam timetable was not found.');$s=$pdo->prepare('SELECT * FROM validation_runs WHERE run_id=?');$s->execute([$runId]);$run=$s->fetch(PDO::FETCH_ASSOC);if(!$run)throw new RuntimeException('Conflict Checker result was not found.');$recordCount=count($b['records']);$x=$pdo->prepare("SELECT COUNT(*) FROM validation_run_records WHERE run_id=? AND schedule_type='Exam' AND reference_id IN (SELECT id FROM exam_schedules WHERE batch_id=?)");$x->execute([$runId,$id]);if((int)$x->fetchColumn()!==$recordCount)throw new RuntimeException('The validation run does not cover every exam in this timetable.');$valid=(int)$run['critical_count']===0&&$run['status']==='Completed';$to=$valid?'Validated':'For Validation';$pdo->beginTransaction();$pdo->prepare('UPDATE exam_timetable_batches SET status=?,validation_run_id=?,validation_summary_json=? WHERE id=?')->execute([$to,$runId,json_encode($run,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),$id]);exwHistory($pdo,$id,null,'Conflict validation',$b['status'],$to,$valid?'Conflict Checker completed without critical findings.':$run['critical_count'].' critical finding(s) require resolution.',$run);$pdo->commit();exwOut(['ok'=>true,'message'=>$valid?'Conflict validation completed. The timetable is Validated.':'Critical conflicts must be resolved and rechecked.','batch'=>exwBatch($pdo,$id)]);}
 if($action==='mark_ready'){$id=(int)($p['batch_id']??0);$b=exwBatch($pdo,$id);if(!$b)throw new RuntimeException('Exam timetable was not found.');if($b['status']!=='Validated')throw new RuntimeException('Only a Validated timetable can be marked Ready to Publish.');$pdo->beginTransaction();$pdo->prepare("UPDATE exam_timetable_batches SET status='Ready to Publish' WHERE id=?")->execute([$id]);$pdo->prepare("UPDATE exam_schedules SET status='Ready to Publish' WHERE batch_id=? AND status='Validated'")->execute([$id]);exwHistory($pdo,$id,null,'Ready for publication','Validated','Ready to Publish','Final review completed.');$pdo->commit();exwOut(['ok'=>true,'message'=>'Timetable marked Ready to Publish.','batch'=>exwBatch($pdo,$id)]);}
 if($action==='publish'){$id=(int)($p['batch_id']??0);$b=exwBatch($pdo,$id);if(!$b)throw new RuntimeException('Exam timetable was not found.');if($b['status']!=='Ready to Publish')throw new RuntimeException('Complete validation and final review before publishing.');$issues=exwFreshIssues($pdo,$id);if($issues)throw new RuntimeException('Final validation stopped publication: '.implode(' ',array_slice($issues,0,3)));$pdo->beginTransaction();$pdo->prepare("UPDATE exam_schedules SET status='Published' WHERE batch_id=? AND status<>'Cancelled'")->execute([$id]);$pdo->prepare("UPDATE exam_timetable_batches SET status='Published',published_at=NOW() WHERE id=?")->execute([$id]);exwHistory($pdo,$id,null,'Published','Ready to Publish','Published','Published only after a fresh time block, faculty, room, capacity, and overlap recheck.');$pdo->commit();logActivity('Publish exam timetable',"{$b['reference_no']} published after final validation.",'scheduling');exwOut(['ok'=>true,'message'=>'Exam timetable published successfully.','batch'=>exwBatch($pdo,$id)]);}
 if($action==='share'){$id=(int)($p['batch_id']??0);$b=exwBatch($pdo,$id);if(!$b)throw new RuntimeException('Exam timetable was not found.');if($b['status']!=='Published')throw new RuntimeException('Only a Published timetable can be shared.');$aud=array_values(array_intersect(['Faculty','Students/Sections','Program Heads','Scheduling Staff'],array_map('strval',$p['audiences']??[])));if(!$aud)throw new InvalidArgumentException('Select at least one audience.');$message=mb_substr(trim((string)($p['message']??'')),0,500);$pdo->beginTransaction();$s=$pdo->prepare("INSERT INTO exam_timetable_shares(batch_id,audience,delivery_status,message,sent_by,sent_at) VALUES(?,?,'Sent',?,?,NOW())");foreach($aud as $a)$s->execute([$id,$a,$message?:null,exwActor()]);exwHistory($pdo,$id,null,'Shared','Published','Published','Notification/share record created for '.implode(', ',$aud).'.',['audiences'=>$aud,'message'=>$message]);$pdo->commit();logActivity('Share exam timetable',"{$b['reference_no']} shared with ".implode(', ',$aud).'.','scheduling');exwOut(['ok'=>true,'message'=>'Notification records created for '.count($aud).' audience(s).','batch'=>exwBatch($pdo,$id)]);}
 throw new InvalidArgumentException('Unknown action.');
}catch(Throwable $e){if(isset($pdo)&&$pdo instanceof PDO&&$pdo->inTransaction())$pdo->rollBack();error_log('Exam workflow API: '.$e->getMessage());$safe=!($e instanceof PDOException)&&($e instanceof InvalidArgumentException||$e instanceof RuntimeException)?$e->getMessage():'Exam timetable operation failed. Please try again or contact the administrator.';exwOut(['ok'=>false,'error'=>$safe],$e instanceof InvalidArgumentException?422:409);}
