<?php
declare(strict_types=1);

require_once __DIR__ . '/../../config/config.php';
require_once ROOT_PATH . '/config/database.php';
require_once ROOT_PATH . '/includes/authentication.php';
require_once ROOT_PATH . '/includes/audit.php';

header('Content-Type: application/json; charset=utf-8');
if(function_exists('isAuthenticated')&&!isAuthenticated()){http_response_code(401);echo json_encode(['ok'=>false,'error'=>'Authentication required.']);exit;}
if(function_exists('userCanAccessModule')&&!userCanAccessModule('scheduling')){http_response_code(403);echo json_encode(['ok'=>false,'error'=>'You do not have permission to access Class Scheduling.']);exit;}

const SA_STATUSES=['Pending','Assigned','Ongoing','Completed','Cancelled'];
function saOut(array $v,int $s=200):never{http_response_code($s);echo json_encode($v,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function saBody():array{$v=json_decode((string)file_get_contents('php://input'),true);if(!is_array($v))throw new InvalidArgumentException('A valid JSON request body is required.');return $v;}
function saDate(string $v):string{$d=DateTime::createFromFormat('Y-m-d',$v);if(!$d||$d->format('Y-m-d')!==$v)throw new InvalidArgumentException('Select a valid absence date.');return $v;}
function saDay(string $v):string{return(new DateTime($v))->format('l');}
function saTime(?string $v):?string{return$v?substr($v,0,5):null;}
function saUserId():?int{return function_exists('getCurrentUserId')?getCurrentUserId():null;}
function saQualificationConfigured(PDO $pdo):bool{return(int)$pdo->query("SELECT COUNT(*) FROM teacher_subject_qualifications WHERE status='Active'")->fetchColumn()>0;}
function saAvailabilityConfigured(PDO $pdo):bool{return(int)$pdo->query("SELECT COUNT(*) FROM teacher_availability")->fetchColumn()>0;}
function saClass(PDO $pdo,int $id,bool $lock=false):?array{
    $sql="SELECT se.id,se.section_id,se.subject_id,se.teacher_id original_teacher_id,se.room_id,se.time_block_id,
                 se.day_of_week,se.start_time,se.end_time,se.class_type,se.status,se.academic_year,se.semester,
                 sec.code section_code,sec.program,sec.current_students,sub.code subject_code,sub.name subject_name,
                 sub.units,t.employee_no original_employee_no,t.full_name original_teacher,t.department original_department,
                 r.room_code
          FROM schedule_entries se JOIN sections sec ON sec.id=se.section_id JOIN subjects sub ON sub.id=se.subject_id
          JOIN teachers t ON t.id=se.teacher_id LEFT JOIN rooms r ON r.id=se.room_id WHERE se.id=:id LIMIT 1".($lock?' FOR UPDATE':'');
    $st=$pdo->prepare($sql);$st->execute(['id'=>$id]);$r=$st->fetch(PDO::FETCH_ASSOC);if(!$r)return null;
    foreach(['id','section_id','subject_id','original_teacher_id','room_id','time_block_id','current_students'] as $k)$r[$k]=$r[$k]===null?null:(int)$r[$k];
    $r['units']=(float)$r['units'];$r['start_time']=saTime($r['start_time']);$r['end_time']=saTime($r['end_time']);return$r;
}
function saAssignmentRows(PDO $pdo,array $f=[]):array{
    $sql="SELECT sa.*,se.day_of_week,se.start_time,se.end_time,se.class_type,se.status class_status,
                 sec.code section_code,sec.program,sub.code subject_code,sub.name subject_name,r.room_code,
                 orig.full_name original_teacher,orig.department original_department,
                 repl.full_name substitute_teacher,repl.department substitute_department
          FROM substitute_assignments sa JOIN schedule_entries se ON se.id=sa.schedule_entry_id
          JOIN sections sec ON sec.id=se.section_id JOIN subjects sub ON sub.id=se.subject_id LEFT JOIN rooms r ON r.id=se.room_id
          JOIN teachers orig ON orig.id=sa.original_teacher_id LEFT JOIN teachers repl ON repl.id=sa.substitute_teacher_id WHERE 1=1";$p=[];
    if(!empty($f['status'])&&in_array($f['status'],SA_STATUSES,true)){$sql.=" AND sa.status=:status";$p['status']=$f['status'];}
    if(!empty($f['program'])){$sql.=" AND sec.program=:program";$p['program']=$f['program'];}
    if(!empty($f['section'])){$sql.=" AND sec.code=:section";$p['section']=$f['section'];}
    if(!empty($f['faculty'])){$sql.=" AND (orig.full_name LIKE :faculty OR repl.full_name LIKE :faculty)";$p['faculty']='%'.$f['faculty'].'%';}
    if(!empty($f['search'])){$sql.=" AND (sub.code LIKE :search OR sub.name LIKE :search OR sec.code LIKE :search OR sa.reference_no LIKE :search)";$p['search']='%'.$f['search'].'%';}
    if(!empty($f['from'])){$sql.=" AND sa.absence_date>=:from_date";$p['from_date']=saDate($f['from']);}
    if(!empty($f['to'])){$sql.=" AND sa.absence_date<=:to_date";$p['to_date']=saDate($f['to']);}
    $sql.=" ORDER BY sa.absence_date DESC,se.start_time,sa.id DESC LIMIT 250";$st=$pdo->prepare($sql);$st->execute($p);$rows=$st->fetchAll(PDO::FETCH_ASSOC);
    foreach($rows as &$r){foreach(['id','schedule_entry_id','original_teacher_id','substitute_teacher_id'] as $k)$r[$k]=$r[$k]===null?null:(int)$r[$k];$r['start_time']=saTime($r['start_time']);$r['end_time']=saTime($r['end_time']);$r['validation']=$r['validation_json']?json_decode($r['validation_json'],true):null;unset($r['validation_json']);}unset($r);return$rows;
}
function saClasses(PDO $pdo,array $f=[]):array{
    $sql="SELECT se.id FROM schedule_entries se JOIN sections sec ON sec.id=se.section_id JOIN subjects sub ON sub.id=se.subject_id JOIN teachers t ON t.id=se.teacher_id
          WHERE se.status IN ('Validated','Published') AND se.teacher_id IS NOT NULL AND se.day_of_week IS NOT NULL AND se.start_time IS NOT NULL";$p=[];
    if(!empty($f['program'])){$sql.=" AND sec.program=:program";$p['program']=$f['program'];}
    if(!empty($f['section'])){$sql.=" AND sec.code=:section";$p['section']=$f['section'];}
    if(!empty($f['faculty'])){$sql.=" AND t.full_name LIKE :faculty";$p['faculty']='%'.$f['faculty'].'%';}
    if(!empty($f['search'])){$sql.=" AND (sub.code LIKE :search OR sub.name LIKE :search OR sec.code LIKE :search OR t.full_name LIKE :search)";$p['search']='%'.$f['search'].'%';}
    $sql.=" ORDER BY sec.code,sub.code LIMIT 250";$st=$pdo->prepare($sql);$st->execute($p);$out=[];foreach($st->fetchAll(PDO::FETCH_COLUMN) as $id){$c=saClass($pdo,(int)$id);if($c)$out[]=$c;}return$out;
}
function saTeacherLoad(PDO $pdo,int $teacherId,?string $ay,?string $sem):float{
    $st=$pdo->prepare("SELECT COALESCE(SUM(sub.units),0) FROM schedule_entries se JOIN subjects sub ON sub.id=se.subject_id
        WHERE se.teacher_id=:teacher AND se.status IN ('Draft','Validated','Published') AND se.academic_year<=>:ay AND se.semester<=>:sem");
    $st->execute(['teacher'=>$teacherId,'ay'=>$ay,'sem'=>$sem]);return(float)$st->fetchColumn();
}
function saTeacherChecks(PDO $pdo,array $class,int $teacherId,string $date):array{
    $st=$pdo->prepare("SELECT id,employee_no,full_name,department,max_load_units,status FROM teachers WHERE id=:id LIMIT 1");$st->execute(['id'=>$teacherId]);$t=$st->fetch(PDO::FETCH_ASSOC);
    if(!$t)return['eligible'=>false,'score'=>0,'teacher'=>null,'checks'=>[['code'=>'exists','label'=>'Teacher record','passed'=>false,'level'=>'critical','detail'=>'Teacher record was not found.']],'conflicts'=>[]];
    $day=saDay($date);$start=$class['start_time'].':00';$end=$class['end_time'].':00';$qualConfigured=saQualificationConfigured($pdo);$availabilityConfigured=saAvailabilityConfigured($pdo);
    $qst=$pdo->prepare("SELECT specialization_label FROM teacher_subject_qualifications WHERE teacher_id=:teacher AND subject_id=:subject AND status='Active' LIMIT 1");$qst->execute(['teacher'=>$teacherId,'subject'=>$class['subject_id']]);$qual=$qst->fetch(PDO::FETCH_ASSOC)?:null;
    $ast=$pdo->prepare("SELECT availability,remarks FROM teacher_availability WHERE teacher_id=:teacher AND day_of_week=:day AND start_time<:end AND end_time>:start
        AND (academic_year IS NULL OR academic_year=:ay) AND (semester IS NULL OR semester=:sem) ORDER BY FIELD(availability,'Unavailable','Preferred','Available') LIMIT 1");
    $ast->execute(['teacher'=>$teacherId,'day'=>$day,'start'=>$start,'end'=>$end,'ay'=>$class['academic_year'],'sem'=>$class['semester']]);$availability=$ast->fetch(PDO::FETCH_ASSOC)?:null;
    $rst=$pdo->prepare("SELECT se.id,sec.code section_code,sub.code subject_code,se.start_time,se.end_time FROM schedule_entries se JOIN sections sec ON sec.id=se.section_id JOIN subjects sub ON sub.id=se.subject_id
        WHERE se.teacher_id=:teacher AND se.id<>:entry AND se.day_of_week=:day AND se.status IN ('Draft','Validated','Published') AND se.start_time<:end AND se.end_time>:start
        AND se.academic_year<=>:ay AND se.semester<=>:sem");$rst->execute(['teacher'=>$teacherId,'entry'=>$class['id'],'day'=>$day,'start'=>$start,'end'=>$end,'ay'=>$class['academic_year'],'sem'=>$class['semester']]);$conflicts=$rst->fetchAll(PDO::FETCH_ASSOC);
    $sst=$pdo->prepare("SELECT sc.id,sc.title,sc.start_time,sc.end_time FROM special_classes sc WHERE sc.teacher_id=:teacher AND sc.class_date=:date AND sc.status NOT IN ('Cancelled','Draft') AND sc.start_time<:end AND sc.end_time>:start");$sst->execute(['teacher'=>$teacherId,'date'=>$date,'start'=>$start,'end'=>$end]);foreach($sst->fetchAll(PDO::FETCH_ASSOC) as $x)$conflicts[]=['id'=>$x['id'],'section_code'=>'Special Class','subject_code'=>$x['title'],'start_time'=>$x['start_time'],'end_time'=>$x['end_time']];
    $est=$pdo->prepare("SELECT ex.id,sec.code section_code,sub.code subject_code,ex.start_time,ex.end_time FROM exam_schedules ex JOIN sections sec ON sec.id=ex.section_id JOIN subjects sub ON sub.id=ex.subject_id WHERE ex.proctor_id=:teacher AND ex.exam_date=:date AND ex.status<>'Cancelled' AND ex.start_time<:end AND ex.end_time>:start");$est->execute(['teacher'=>$teacherId,'date'=>$date,'start'=>$start,'end'=>$end]);$conflicts=array_merge($conflicts,$est->fetchAll(PDO::FETCH_ASSOC));
    $subst=$pdo->prepare("SELECT sa.id,sec.code section_code,sub.code subject_code,se.start_time,se.end_time FROM substitute_assignments sa JOIN schedule_entries se ON se.id=sa.schedule_entry_id JOIN sections sec ON sec.id=se.section_id JOIN subjects sub ON sub.id=se.subject_id WHERE sa.substitute_teacher_id=:teacher AND sa.absence_date=:date AND sa.status IN ('Assigned','Ongoing') AND sa.schedule_entry_id<>:entry AND se.start_time<:end AND se.end_time>:start");$subst->execute(['teacher'=>$teacherId,'date'=>$date,'entry'=>$class['id'],'start'=>$start,'end'=>$end]);$conflicts=array_merge($conflicts,$subst->fetchAll(PDO::FETCH_ASSOC));
    $load=saTeacherLoad($pdo,$teacherId,$class['academic_year'],$class['semester']);$max=(float)$t['max_load_units'];$within=$max<=0||$load<=$max;$active=$t['status']==='Active';$notOriginal=$teacherId!==$class['original_teacher_id'];$available=!$availability||$availability['availability']!=='Unavailable';$qualified=!$qualConfigured||$qual!==null;$free=count($conflicts)===0;
    $checks=[
      ['code'=>'active','label'=>'Active faculty','passed'=>$active,'level'=>'critical','detail'=>$active?'Faculty record is active.':'Faculty record is inactive.'],
      ['code'=>'different','label'=>'Different from absent faculty','passed'=>$notOriginal,'level'=>'critical','detail'=>$notOriginal?'Teacher is a valid replacement candidate.':'Absent faculty cannot substitute for the same class.'],
      ['code'=>'qualification','label'=>'Qualified for subject','passed'=>$qualified,'level'=>$qualConfigured?'critical':'warning','detail'=>$qualConfigured?($qual?'Qualification verified'.($qual['specialization_label']?' · '.$qual['specialization_label']:'').'.':'No active subject qualification found.'):'Qualification map is not configured; manual review is required.'],
      ['code'=>'availability','label'=>'Available at class time','passed'=>$available,'level'=>$availabilityConfigured?'critical':'warning','detail'=>$availability?('Declared '.$availability['availability'].($availability['remarks']?' · '.$availability['remarks']:'').'.'):($availabilityConfigured?'No conflicting unavailability declaration.':'Faculty availability declarations are not configured.')],
      ['code'=>'conflict','label'=>'No schedule conflict','passed'=>$free,'level'=>'critical','detail'=>$free?'No regular, special, exam, or substitute overlap found.':count($conflicts).' overlapping assignment(s) found.'],
      ['code'=>'load','label'=>'Load within limit','passed'=>$within,'level'=>'critical','detail'=>number_format($load,1).' / '.($max>0?number_format($max,1):'not configured').' units.'],
    ];
    $eligible=!array_filter($checks,fn($x)=>$x['level']==='critical'&&!$x['passed']);$score=0;if($eligible)$score+=40;if($qual)$score+=25;if($availability&&$availability['availability']==='Preferred')$score+=15;if($t['department']===$class['original_department'])$score+=10;if($max>0)$score+=max(0,min(10,(int)(($max-$load)/$max*10)));
    $t['id']=(int)$t['id'];$t['current_load_units']=$load;$t['max_load_units']=$max;$t['specialization']=$qual['specialization_label']??($qualConfigured?'No matching qualification':'Not configured');$t['availability']=$availability['availability']??($availabilityConfigured?'No restriction':'Not configured');
    return['eligible'=>$eligible,'score'=>$score,'recommended_reasons'=>array_values(array_filter([$qual?'Subject qualification verified':null,$availability&&$availability['availability']==='Preferred'?'Preferred availability':null,$t['department']===$class['original_department']?'Same department':null,$free?'No schedule overlap':null])),'teacher'=>$t,'checks'=>$checks,'conflicts'=>$conflicts];
}
function saCandidates(PDO $pdo,array $class,string $date,array $f=[]):array{
    $sql="SELECT id FROM teachers WHERE id<>:original";$p=['original'=>$class['original_teacher_id']];if(!empty($f['department'])){$sql.=" AND department=:department";$p['department']=$f['department'];}if(!empty($f['search'])){$sql.=" AND (full_name LIKE :search OR employee_no LIKE :search)";$p['search']='%'.$f['search'].'%';}$sql.=" ORDER BY full_name";$st=$pdo->prepare($sql);$st->execute($p);$out=[];foreach($st->fetchAll(PDO::FETCH_COLUMN) as $id)$out[]=saTeacherChecks($pdo,$class,(int)$id,$date);usort($out,fn($a,$b)=>(int)$b['eligible']<=>(int)$a['eligible']?:$b['score']<=>$a['score']?:strcmp($a['teacher']['full_name'],$b['teacher']['full_name']));return$out;
}
function saReference(int $id,string $date):string{return'SA-'.substr($date,0,4).'-'.str_pad((string)$id,6,'0',STR_PAD_LEFT);}
function saHistory(PDO $pdo,int $id,string $action,?string $from,?string $to,string $detail,array $snapshot=[]):void{$st=$pdo->prepare("INSERT INTO substitute_assignment_history(substitute_assignment_id,action,from_status,to_status,detail,snapshot_json,changed_by) VALUES(:id,:action,:from,:to,:detail,:snapshot,:user)");$st->execute(['id'=>$id,'action'=>$action,'from'=>$from,'to'=>$to,'detail'=>$detail,'snapshot'=>$snapshot?json_encode($snapshot,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE):null,'user'=>saUserId()]);}
function saNotify(PDO $pdo,int $assignmentId,array $class,int $substituteId,string $reference):int{
    $url=BASE_URL.'/modules/scheduling/pages/substitute-assignment-tracker.php?assignment_id='.$assignmentId;$message=$reference.': '.$class['subject_code'].' '.$class['section_code'].' on '.$class['day_of_week'].' '.$class['start_time'].'-'.$class['end_time'].'.';
    $items=[['Teacher',$substituteId,'Substitute Assignment Confirmed','You were assigned as substitute. '.$message],['Teacher',$class['original_teacher_id'],'Substitute Coverage Recorded','Substitute coverage was recorded for your class. '.$message],['Section',$class['section_id'],'Class Faculty Update','A substitute faculty member was assigned. '.$message],['Scheduling Staff',null,'Substitute Assignment Saved',$message]];$st=$pdo->prepare("INSERT IGNORE INTO scheduling_notifications(event_key,recipient_type,recipient_id,title,message,action_url,related_type,related_id,created_by) VALUES(:event,:type,:recipient,:title,:message,:url,'Substitute Assignment',:related,:user)");$count=0;foreach($items as $i=>$x){$st->execute(['event'=>'substitute-'.$assignmentId.'-'.$i,'type'=>$x[0],'recipient'=>$x[1],'title'=>$x[2],'message'=>$x[3],'url'=>$url,'related'=>$assignmentId,'user'=>saUserId()]);$count+=$st->rowCount();}return$count;
}

try{
 $pdo=getDatabaseConnection();$method=$_SERVER['REQUEST_METHOD']??'GET';$body=$method==='POST'?saBody():[];$action=$method==='GET'?trim((string)($_GET['action']??'dashboard')):trim((string)($body['action']??''));
 if($method==='GET'){
  if($action==='dashboard'){
    $f=['status'=>$_GET['status']??'','program'=>$_GET['program']??'','section'=>$_GET['section']??'','faculty'=>$_GET['faculty']??'','search'=>$_GET['search']??'','from'=>$_GET['from']??'','to'=>$_GET['to']??''];$records=saAssignmentRows($pdo,$f);$all=saAssignmentRows($pdo);$stats=array_fill_keys(SA_STATUSES,0);foreach($all as $r)$stats[$r['status']]++;
    $programs=$pdo->query("SELECT DISTINCT program FROM sections WHERE program<>'' ORDER BY program")->fetchAll(PDO::FETCH_COLUMN);$sections=$pdo->query("SELECT code FROM sections WHERE status='Active' ORDER BY code")->fetchAll(PDO::FETCH_COLUMN);
    saOut(['ok'=>true,'stats'=>$stats,'records'=>$records,'classes'=>saClasses($pdo,$f),'programs'=>$programs,'sections'=>$sections,'qualification_configured'=>saQualificationConfigured($pdo),'availability_configured'=>saAvailabilityConfigured($pdo)]);
  }
  if($action==='class'){$c=saClass($pdo,(int)($_GET['schedule_entry_id']??0));if(!$c)saOut(['ok'=>false,'error'=>'Scheduled class not found.'],404);saOut(['ok'=>true,'class'=>$c]);}
  if($action==='candidates'){$c=saClass($pdo,(int)($_GET['schedule_entry_id']??0));if(!$c)saOut(['ok'=>false,'error'=>'Scheduled class not found.'],404);$date=saDate((string)($_GET['absence_date']??''));if(saDay($date)!==$c['day_of_week'])throw new InvalidArgumentException('The absence date must fall on '.$c['day_of_week'].' for this class.');$f=['department'=>$_GET['department']??'','search'=>$_GET['search']??''];saOut(['ok'=>true,'class'=>$c,'absence_date'=>$date,'candidates'=>saCandidates($pdo,$c,$date,$f)]);}
  if($action==='teacher_schedule'){$id=(int)($_GET['teacher_id']??0);$date=saDate((string)($_GET['date']??''));$day=saDay($date);$st=$pdo->prepare("SELECT sub.code subject_code,sec.code section_code,se.start_time,se.end_time,r.room_code,'Regular' source FROM schedule_entries se JOIN subjects sub ON sub.id=se.subject_id JOIN sections sec ON sec.id=se.section_id LEFT JOIN rooms r ON r.id=se.room_id WHERE se.teacher_id=:id AND se.day_of_week=:day AND se.status IN ('Draft','Validated','Published') ORDER BY se.start_time");$st->execute(['id'=>$id,'day'=>$day]);$rows=$st->fetchAll(PDO::FETCH_ASSOC);foreach($rows as &$r){$r['start_time']=saTime($r['start_time']);$r['end_time']=saTime($r['end_time']);}unset($r);saOut(['ok'=>true,'date'=>$date,'day'=>$day,'schedule'=>$rows]);}
  if($action==='assignment'){$id=(int)($_GET['id']??0);$rows=saAssignmentRows($pdo);$record=null;foreach($rows as $x)if($x['id']===$id)$record=$x;if(!$record)saOut(['ok'=>false,'error'=>'Assignment not found.'],404);$st=$pdo->prepare("SELECT h.*,COALESCE(u.full_name,u.username,'System') changed_by_name FROM substitute_assignment_history h LEFT JOIN users u ON u.id=h.changed_by WHERE h.substitute_assignment_id=:id ORDER BY h.changed_at DESC,h.id DESC");$st->execute(['id'=>$id]);saOut(['ok'=>true,'assignment'=>$record,'history'=>$st->fetchAll(PDO::FETCH_ASSOC)]);}
  saOut(['ok'=>false,'error'=>'Unknown substitute assignment action.'],400);
 }
 if($method!=='POST')saOut(['ok'=>false,'error'=>'Method not allowed.'],405);
 if($action==='validate'){$c=saClass($pdo,(int)($body['schedule_entry_id']??0));if(!$c)saOut(['ok'=>false,'error'=>'Scheduled class not found.'],404);$date=saDate((string)($body['absence_date']??''));if(saDay($date)!==$c['day_of_week'])throw new InvalidArgumentException('The selected date is not a '.$c['day_of_week'].'.');$v=saTeacherChecks($pdo,$c,(int)($body['substitute_teacher_id']??0),$date);saOut(['ok'=>true,'class'=>$c,'absence_date'=>$date,'validation'=>$v]);}
 if(in_array($action,['save_draft','confirm'],true)){
    $entryId=(int)($body['schedule_entry_id']??0);$substituteId=(int)($body['substitute_teacher_id']??0);$date=saDate((string)($body['absence_date']??''));$end=trim((string)($body['absence_end_date']??''));$end=$end!==''?saDate($end):$date;if($end<$date)throw new InvalidArgumentException('Absence end date cannot be before the start date.');$reason=trim((string)($body['reason']??''));if($reason==='')throw new InvalidArgumentException('Reason for absence is required.');$duration=trim((string)($body['duration_label']??''));$remarks=trim((string)($body['remarks']??''));if($action==='confirm'&&$substituteId<=0)throw new InvalidArgumentException('Select a substitute faculty member before confirmation.');
    $pdo->beginTransaction();$c=saClass($pdo,$entryId,true);if(!$c)throw new RuntimeException('The scheduled class no longer exists.');if(!in_array($c['status'],['Validated','Published'],true))throw new RuntimeException('Only validated or published classes can receive a substitute assignment.');if(saDay($date)!==$c['day_of_week'])throw new RuntimeException('The absence date must fall on '.$c['day_of_week'].' for this class.');$validation=$substituteId>0?saTeacherChecks($pdo,$c,$substituteId,$date):null;if($action==='confirm'&&!$validation['eligible'])throw new RuntimeException('Final validation failed. Choose another substitute and recheck.');
    $find=$pdo->prepare("SELECT * FROM substitute_assignments WHERE schedule_entry_id=:entry AND absence_date=:date LIMIT 1 FOR UPDATE");$find->execute(['entry'=>$entryId,'date'=>$date]);$old=$find->fetch(PDO::FETCH_ASSOC)?:null;$status=$action==='confirm'?'Assigned':'Pending';$validationJson=$validation?json_encode($validation,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE):null;
    if($old){$id=(int)$old['id'];$st=$pdo->prepare("UPDATE substitute_assignments SET original_teacher_id=:original,substitute_teacher_id=:substitute,absence_end_date=:end,duration_label=:duration,reason=:reason,status=:status,remarks=:remarks,validation_json=:validation,assigned_at=:assigned,completed_at=NULL WHERE id=:id");$st->execute(['original'=>$c['original_teacher_id'],'substitute'=>$substituteId?:null,'end'=>$end,'duration'=>$duration?:null,'reason'=>mb_substr($reason,0,255),'status'=>$status,'remarks'=>$remarks?mb_substr($remarks,0,255):null,'validation'=>$validationJson,'assigned'=>$status==='Assigned'?date('Y-m-d H:i:s'):null,'id'=>$id]);$reference=$old['reference_no']?:saReference($id,$date);$pdo->prepare("UPDATE substitute_assignments SET reference_no=:ref WHERE id=:id")->execute(['ref'=>$reference,'id'=>$id]);}
    else{$st=$pdo->prepare("INSERT INTO substitute_assignments(schedule_entry_id,original_teacher_id,substitute_teacher_id,absence_date,absence_end_date,duration_label,reason,status,remarks,validation_json,assigned_at,created_by) VALUES(:entry,:original,:substitute,:date,:end,:duration,:reason,:status,:remarks,:validation,:assigned,:user)");$st->execute(['entry'=>$entryId,'original'=>$c['original_teacher_id'],'substitute'=>$substituteId?:null,'date'=>$date,'end'=>$end,'duration'=>$duration?:null,'reason'=>mb_substr($reason,0,255),'status'=>$status,'remarks'=>$remarks?mb_substr($remarks,0,255):null,'validation'=>$validationJson,'assigned'=>$status==='Assigned'?date('Y-m-d H:i:s'):null,'user'=>saUserId()]);$id=(int)$pdo->lastInsertId();$reference=saReference($id,$date);$pdo->prepare("UPDATE substitute_assignments SET reference_no=:ref WHERE id=:id")->execute(['ref'=>$reference,'id'=>$id]);}
    saHistory($pdo,$id,$action==='confirm'?'Confirmed':'Draft saved',$old['status']??null,$status,($action==='confirm'?'Substitute assignment confirmed.':'Substitute assignment saved as Pending.'),['class'=>$c,'validation'=>$validation]);$notified=0;if($action==='confirm'){$notified=saNotify($pdo,$id,$c,$substituteId,$reference);$pdo->prepare("UPDATE substitute_assignments SET notified_at=CURRENT_TIMESTAMP WHERE id=:id")->execute(['id'=>$id]);}$pdo->commit();if(function_exists('logActivity'))logActivity($action==='confirm'?'Confirm substitute':'Save substitute draft',"{$reference} for {$c['subject_code']} {$c['section_code']} on {$date}.",'scheduling');$record=null;foreach(saAssignmentRows($pdo) as $x)if($x['id']===$id)$record=$x;saOut(['ok'=>true,'message'=>$action==='confirm'?'Substitute assignment confirmed.':'Draft saved as Pending.','assignment'=>$record,'notifications_queued'=>$notified]);
 }
 if($action==='update_status'){$id=(int)($body['id']??0);$to=trim((string)($body['status']??''));if(!in_array($to,SA_STATUSES,true))throw new InvalidArgumentException('Invalid assignment status.');$pdo->beginTransaction();$st=$pdo->prepare("SELECT * FROM substitute_assignments WHERE id=:id LIMIT 1 FOR UPDATE");$st->execute(['id'=>$id]);$r=$st->fetch(PDO::FETCH_ASSOC);if(!$r)throw new RuntimeException('Assignment not found.');if(in_array($to,['Assigned','Ongoing','Completed'],true)&&empty($r['substitute_teacher_id']))throw new RuntimeException('A substitute is required for this status.');$allowed=['Pending'=>['Assigned','Cancelled'],'Assigned'=>['Ongoing','Completed','Cancelled'],'Ongoing'=>['Completed','Cancelled'],'Completed'=>[],'Cancelled'=>['Pending']];if(!in_array($to,$allowed[$r['status']]??[],true))throw new RuntimeException('Status cannot move from '.$r['status'].' to '.$to.'.');$pdo->prepare("UPDATE substitute_assignments SET status=:status,completed_at=:completed WHERE id=:id")->execute(['status'=>$to,'completed'=>$to==='Completed'?date('Y-m-d H:i:s'):null,'id'=>$id]);saHistory($pdo,$id,'Status updated',$r['status'],$to,'Assignment status changed to '.$to.'.',$r);$pdo->commit();if(function_exists('logActivity'))logActivity('Update substitute status',($r['reference_no']?:'Assignment #'.$id).' changed to '.$to.'.','scheduling');saOut(['ok'=>true,'message'=>'Status updated to '.$to.'.']);}
 saOut(['ok'=>false,'error'=>'Unknown substitute assignment action.'],400);
}catch(Throwable $e){if(isset($pdo)&&$pdo instanceof PDO&&$pdo->inTransaction())$pdo->rollBack();error_log('Substitute Assignment API error: '.$e->getMessage());$safe=(!($e instanceof PDOException)&&($e instanceof InvalidArgumentException||$e instanceof RuntimeException))?$e->getMessage():'Substitute assignment request failed. Please try again.';saOut(['ok'=>false,'error'=>$safe],$e instanceof InvalidArgumentException?422:500);}
